NARROW={'shoulder':0.93,'thorax_w':0.95,'pelvis_w':0.94,'leg_girth':0.94,'arm_girth':0.94,'hand':0.96,'foot':0.96,'tail_frame':0.95,'thorax_d':0.98}
BROAD={'shoulder':1.08,'thorax_w':1.05,'pelvis_w':1.07,'leg_girth':1.06,'arm_girth':1.06,'hand':1.04,'foot':1.04,'tail_frame':1.06,'thorax_d':1.02}
SINGLE=[  # id, label, group, params
 ('h_lo','Stature 168 cm','body',{'height':168.0}),('h_hi','Stature 208 cm','body',{'height':208.0}),
 ('hd_lo','Head proportion -8 %','body',{'head':0.92}),('hd_hi','Head proportion +8 %','body',{'head':1.08}),
 ('nk_lo','Neck length -15 %','body',{'neck_len':0.85}),('nk_hi','Neck length +15 %','body',{'neck_len':1.15}),
 ('nd_lo','Neck depth -10 %','body',{'neck_d':0.90}),('nd_hi','Neck depth +10 %','body',{'neck_d':1.10}),
 ('td_lo','Thoracic depth -8 %','body',{'thorax_d':0.92}),('td_hi','Thoracic depth +8 %','body',{'thorax_d':1.08}),
 ('tw_lo','Thoracic width -7 %','body',{'thorax_w':0.93}),('tw_hi','Thoracic width +7 %','body',{'thorax_w':1.07}),
 ('tl_lo','Axial trunk length -10 %','body',{'trunk_len':0.90}),('tl_hi','Axial trunk length +10 %','body',{'trunk_len':1.10}),
 ('sh_lo','Shoulder breadth -8 %','body',{'shoulder':0.92}),('sh_hi','Shoulder breadth +8 %','body',{'shoulder':1.08}),
 ('pw_lo','Pelvic width -7 %','body',{'pelvis_w':0.93}),('pw_hi','Pelvic width +7 %','body',{'pelvis_w':1.07}),
 ('al_lo','Arm length -6 %','body',{'arm_len':0.94}),('al_hi','Arm length +6 %','body',{'arm_len':1.06}),
 ('ll_lo','Leg length -6 %','body',{'leg_len':0.94}),('ll_hi','Leg length +6 %','body',{'leg_len':1.06}),
 ('ha_lo','Hand size -8 %','body',{'hand':0.92}),('ha_hi','Hand size +8 %','body',{'hand':1.08}),
 ('fo_lo','Foot size -8 %','body',{'foot':0.92}),('fo_hi','Foot size +8 %','body',{'foot':1.08}),
 ('fr_n','Frame: Narrow','frame',NARROW),('fr_b','Frame: Broad','frame',BROAD),
 ('mu_lo','Muscle low','comp',{'muscle':-1.0}),('mu_hi','Muscle high','comp',{'muscle':1.0}),
 ('fa_lo','Body fat low','comp',{'fat':-1.0}),('fa_hi','Body fat high','comp',{'fat':1.0}),
 ('tn_lo','Tail length 55 % H','tail',{'tail_len':55/64.613}),('tn_hi','Tail length 80 % H','tail',{'tail_len':80/64.613}),
 ('tb_lo','Tail base -15 %','tail',{'tail_base':0.85}),('tb_hi','Tail base +15 %','tail',{'tail_base':1.15}),
 ('tt_lo','Tail mid/distal fullness -15 %','tail',{'tail_taper':0.85}),('tt_hi','Tail mid/distal fullness +15 %','tail',{'tail_taper':1.15}),
 ('tc_lo','Tail carriage lifted 8 deg','tail',{'tail_curv':-8.0}),('tc_hi','Tail carriage drooped 10 deg','tail',{'tail_curv':10.0}),
 ('tx_lo','Tail section deeper (lat -10 %)','tail',{'tail_lat':0.90}),('tx_hi','Tail section broader (lat +10 %)','tail',{'tail_lat':1.10}),
 ('rl_lo','Rostrum length -15 %','head',{'ros_len':0.85}),('rl_hi','Rostrum length +20 %','head',{'ros_len':1.20}),
 ('rw_lo','Rostral base width -12 %','head',{'ros_w':0.88}),('rw_hi','Rostral base width +12 %','head',{'ros_w':1.12}),
 ('ra_lo','Anterior rostral width -15 %','head',{'ros_aw':0.85}),('ra_hi','Anterior rostral width +15 %','head',{'ros_aw':1.15}),
 ('rd_lo','Rostral depth -12 %','head',{'ros_d':0.88}),('rd_hi','Rostral depth +12 %','head',{'ros_d':1.12}),
 ('jd_lo','Posterior jaw depth -12 %','head',{'jaw_d':0.88}),('jd_hi','Posterior jaw depth +15 %','head',{'jaw_d':1.15}),
 ('cl_lo','Cranial length -8 %','head',{'cran_len':0.92}),('cl_hi','Cranial length +8 %','head',{'cran_len':1.08}),
 ('cw_lo','Cranial width -8 %','head',{'cran_w':0.92}),('cw_hi','Cranial width +8 %','head',{'cran_w':1.08}),
 ('cd_lo','Cranial depth -7 %','head',{'cran_d':0.93}),('cd_hi','Cranial depth +7 %','head',{'cran_d':1.07}),
 ('ob_lo','Orbit size -8 %','head',{'orbit':0.92}),('ob_hi','Orbit size +8 %','head',{'orbit':1.08}),
]
def M(*ds):
    o={}
    for d in ds: o.update(d)
    return o
COMBO=[
 ('x01','Shortest + broadest frame',M({'height':168.0},BROAD)),
 ('x02','Tallest + narrowest frame',M({'height':208.0},NARROW)),
 ('x03','Long tail (80 %) + minimum tail base',{'tail_len':80/64.613,'tail_base':0.85}),
 ('x04','Short tail (55 %) + maximum tail base',{'tail_len':55/64.613,'tail_base':1.15}),
 ('x05','Longest rostrum + narrow cranium',{'ros_len':1.20,'cran_w':0.92}),
 ('x06','Shortest rostrum + broad cranium',{'ros_len':0.85,'cran_w':1.08}),
 ('x07','Max head proportion + Narrow frame',M({'head':1.08},NARROW)),
 ('x08','Min head proportion + Broad frame',M({'head':0.92},BROAD)),
 ('x09','High muscle + low fat',{'muscle':1.0,'fat':-1.0}),
 ('x10','Low muscle + high fat',{'muscle':-1.0,'fat':1.0}),
 ('x13','Long tail (80 %) + drooped carriage',{'tail_len':80/64.613,'tail_curv':10.0}),
 ('x14','Tallest + longest tail + max base',{'height':208.0,'tail_len':80/64.613,'tail_base':1.15}),
 ('x15','Shortest + short tail + high fat',{'height':168.0,'tail_len':55/64.613,'fat':1.0}),
 ('x16','Long neck + max head',{'neck_len':1.15,'head':1.08}),
 ('x17','Long legs + short trunk + short neck',{'leg_len':1.06,'trunk_len':0.90,'neck_len':0.85}),
 ('x18','Narrow + high fat + long tail',M(NARROW,{'fat':1.0,'tail_len':80/64.613})),
 ('x19','Long rostrum + shallow jaw + shallow rostrum',{'ros_len':1.20,'jaw_d':0.88,'ros_d':0.88}),
 ('x20','Broad + high muscle + max tail base',M(BROAD,{'muscle':1.0,'tail_base':1.15})),
 ('x21','Long tail (80 %) + max base + low taper',{'tail_len':80/64.613,'tail_base':1.15,'tail_taper':0.85}),
 ('x23','Broad + shallow + wide thorax',M(BROAD,{'thorax_d':0.92,'thorax_w':1.07})),
 ('x24','Short rostrum + long cranium',{'ros_len':0.85,'cran_len':1.08}),
 ('x25','High fat, caudal fat concentrated at base',{'fat':1.0,'tail_fat_conc':1}),
 ('x26','Long tail (80 %) + coupled base (rule)',{'tail_len':80/64.613,'tail_base':1.22}),
 ('x27','Broad + long tail (80 %) + coupled base',M(BROAD,{'tail_len':80/64.613,'tail_base':1.16})),
 ('x28','Reference body: longest valid tail (78 %) + coupled base',{'tail_len':78/64.613,'tail_base':1.15}),
 ('x22','Short tail (55 %) + min base + full taper',{'tail_len':55/64.613,'tail_base':0.85,'tail_taper':1.15}),
]
