"""Generate the W1f evidence tables and ARM records from the evidence JSON (no hand-typed numbers).
Writes reviews/rac-w1f-evidence/tables.md and reviews/rac-w1f-arm/claude-rac-w1f-arm-<ID>.md."""
import json, os, hashlib
from collections import Counter
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
EV = os.path.join(R, "reviews", "rac-w1f-evidence"); ARM = os.path.join(R, "reviews", "rac-w1f-arm"); CFG = os.path.join(R, "tools", "rac", "w1", "cfg", "w1f")
E1 = os.path.join(R, "reviews", "rac-w1e-evidence")
def jl(*p): return json.load(open(os.path.join(*p)))
def f4(x): return "—" if x is None else (("[%.4f, %.4f]" % tuple(x)) if isinstance(x, list) else ("%.4f" % x if isinstance(x, (int, float)) else str(x)))
def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()[:16]
STRICT = (">", "<")
def res(x):
    if "result" in x: return x["result"]
    if x.get("report_only"): return "REPORT"
    if x.get("historical"): return "HISTORICAL (non-vetoing)"
    if not x["pass"]: return "FAIL"
    if x["op"] in STRICT and isinstance(x["vb"], float) and abs(x["va"] - x["vb"]) / max(abs(x["vb"]), 1e-9) < 0.01: return "NOT DEMONSTRATED"
    return "PASS"
def cnt(rows): c = Counter(res(x) for x in rows); return ", ".join("%s %d" % (k, v) for k, v in sorted(c.items()))
def rows_md(rows, by_t=False):
    h = "| Cand | Check | Canon | %s | Op | Comparator%s | Result |" % ("Value t=0 / 0.5 / 1.0" if by_t else "Value", " t=0 / 0.5 / 1.0" if by_t else "")
    out = [h, "|---|---|---|---|---|---|---|"]
    for x in rows:
        r = res(x); r = "**%s**" % r if r.split(" ")[0] in ("FAIL", "NOT", "MARGINAL", "T-SENSITIVE") else r
        if by_t and x.get("by_t"): v = " / ".join(f4(t["va"]) for t in x["by_t"].values())
        else: v = f4(x.get("va"))
        if by_t and x.get("by_t"): cv = " / ".join(f4(t["vb"]) for t in x["by_t"].values())
        else: cv = f4(x.get("vb")) if x.get("vb") is not None else ""
        out.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], x.get("canon", ""), v, x["op"], x.get("b", ""), cv, r))
    return out
KEYS = ["crest_share", "bitroch_share", "pelvic_depth_share", "pelvic_vertical_share", "hip_joint_breadth_share", "pelvic_depth_over_crest",
        "bitroch_over_crest", "pelvic_depth_over_thorax_depth", "thorax_breadth_share", "thorax_depth_share", "thorax_d_over_b", "gh_breadth_share",
        "biacromial_share", "S1_over_S2_b", "S3_over_S2_b", "S4_over_S2_b", "S3_over_S2_d", "S4_over_S2_d", "S5_over_S2_b", "S6_over_S2_b",
        "S5_over_S4_b", "S6_over_S4_b", "ribcage_vertical_over_S2_b", "hipjoint_scale_over_crest", "prox_femur_over_S6_b", "shaft_b_over_femur", "leg_share", "torso_share"]

def main():
    os.makedirs(ARM, exist_ok=True)
    SK = jl(EV, "skeletal", "skeletal_checks.json"); AI = jl(EV, "skeletal", "alpc_invariance.json"); A8 = jl(EV, "skeletal", "alpc8.json")
    CC = jl(EV, "skeletal", "contour_clearance.json"); DC = jl(EV, "directional_checks.json"); WC = jl(EV, "w1e_checks.json")
    OC = jl(EV, "ocular", "ocular_w1f.json"); EC = jl(EV, "ears", "ear_checks.json"); EA = jl(EV, "ears", "ears_attached.json")
    GOc = jl(CFG, "GO.json"); GRc = jl(CFG, "GR.json"); VAc = jl(CFG, "VA.json"); HS = jl(EV, "go-variants", "alpc6_human_tissue_sensitivity.json")
    skp = lambda i: jl(EV, "skeletal", i + "_skp.json")
    T = ["# RAC W1f — evidence tables", "", "Generated by `tools/rac/w1/gen_w1f_docs.py` from the JSON in this folder. Nothing here is canon. Skeletal-proxy readings are the PV-D16 / AD-G10 validation layer; skin readings are composition-inclusive diagnostics.", ""]
    # 1 construction
    sk_go = GOc["skeleton"]
    T += ["## 1. Builder-chosen construction values (R-14)", "",
          "**Skeletal proxy method:** skeleton = rig joint centres + the same body rebuilt at the generator minimum composition (muscle 0, weight 0; same skeleton construction), aligned to the reference rig joints by a uniform similarity, inset by an unmeasured soft-tissue allowance t swept over 0 / 0.5 / 1.0 cm x H/173.14; a direction counts only if it holds at every t. Glenohumeral centre = sphere fit to the skeletal-envelope shoulder cap; acromion = highest skeletal-envelope point over the shoulder; proximal-femur scale = hip-joint centre to greater-trochanter distance; shaft = skeletal-envelope thigh section at 20 % femur length.", "",
          "| Body | Item | Value |", "|---|---|---|",
          "| GO | generator inputs | W1c GO targets (`%s`), height macro %.4f (re-solved with the skeleton) |" % ("tools/rac/w1/cfg/GO.json", GOc["height_macro"]),
          "| GO | skeletal bone scales (X lateral, Y length, Z depth) | %s |" % "; ".join("%s %s" % kv for kv in sk_go["bone_scales"].items()),
          "| GO | skeletal trunk sculpt nodes r (hip joint = 0, suprasternal = 1) | %s |" % sk_go["trunk_sculpt"]["r"],
          "| GO | anterior depth factor ka | %s |" % sk_go["trunk_sculpt"]["ka"], "| GO | posterior depth factor kp | %s |" % sk_go["trunk_sculpt"]["kp"],
          "| GO | breadth factor kb | %s |" % sk_go["trunk_sculpt"]["kb"], "| GO | sculpt displacement smoothing | %d Laplacian iterations |" % sk_go["sculpt_displacement_smoothing_iters"],
          "| GO | tissue | %s |" % GOc["tissue_donor"]]
    for k, v in GOc["frames"].items(): T.append("| %s | frame / composition write | `%s` |" % (k, json.dumps(v)))
    T += ["| GOR-BODY-02 | 208 cm body | height macro %.4f, same skeleton construction |" % GOc["GOR-BODY-02"]["height_macro"],
          "| GR | construction | %s |" % GRc["route"], "| GR | scapula proxy (GR-G2 render review) | GR %s; MF and all other bodies %s |" % ({k: GRc["scapula_proxy"][k] for k in ("SUP", "INF", "MED")}, GRc["scapula_proxy"]["MF_and_others"]),
          "| VA | pelvic bone scale | %s (W1e: [1.02, 1.0, 1.0]; depth +3 %% added for PV-D6 on the skeletal proxy) |" % VAc.get("bone_scales"),
          "| SK Broad 229 / 208 | equal-height comparator frame write | `%s` |" % json.dumps(jl(CFG, "skarn_broad_frame_lean.json")["bone_scales"]),
          "| FN | O-1 ring increment | delta %.2f (accepted O-D2a); ring placement 0.8 cm forward at MF-M-R head size, carried with HH |" % OC["bodies"]["FN"]["delta"], ""]
    # 2 skeletal checks
    T += ["## 2. Skeletal / bony-landmark validation (PV-D16, AD-G10): accepted pelvic / girdle / ALPC relations (`skeletal/skeletal_checks.json`; %d rows: %s)" % (len(SK), cnt(SK)), "",
          "Rule: strict > / < must hold by >= 1 % (else NOT DEMONSTRATED); non-strict >= / <= missing by < 1 % = MARGINAL; '~' = W1c ±0.010; T-SENSITIVE = result changes with the soft-tissue allowance. ALPC-7 here is against the equal-height (229 cm) Broad Skarn. The ALPC-5 / -6 / -8 'NOT RUN' rows are run in §3.", ""] + rows_md(SK, by_t=True)
    # 3 ALPC
    T += ["", "## 3. ALPC-5 / -6 / -7 (208 cm) / -8", ""]
    for k, rows in AI["rows"].items():
        T += ["### %s (%s)" % (k, cnt(rows)), ""] + rows_md(rows, by_t="skin" not in k) + [""]
    hs = HS["rows"]; k6 = [k for k in hs if k.startswith("ALPC-6 GOR")][0]
    T += ["### Sensitivity (not adopted): GOR-BODY-16 with the human reference (MF-M-R) tissue distribution carried onto the GO skeleton (%s)" % cnt(hs[k6]), ""] + rows_md(hs[k6]) + [""]
    T += ["### ALPC-8 / GO L775 matched-display silhouette test (`skeletal/alpc8.json`, minimum composition, same displayed height)", "", "| Reading | GO | DU | GO > DU |", "|---|---|---|---|"]
    for k, v in A8["checks"].items():
        if isinstance(v, list): T.append("| %s | %s | %s | %s |" % (k, f4(v[0]), f4(v[1]), "yes" if v[2] else "**no**"))
    T += ["", "Silhouette IoU (1 = identical): front %.3f, side %.3f; identical silhouettes: %s." % (A8["checks"]["silhouette_IoU"]["front"], A8["checks"]["silhouette_IoU"]["side"], A8["checks"]["identical_silhouettes"]), ""]
    # 4 before / after
    T += ["## 4. Gorrund before / after (skeletal proxy, t = 0.5 cm x H/173)", "", "| Reading | MF-M-R | SK | SK Broad 229 | GO W1e (skin route) | GO W1e skin-only trial (rejected) | GO W1f |", "|---|---|---|---|---|---|---|"]
    S = {"MF-M-R": skp("MF-M-R"), "SK": skp("SK"), "SKB": skp("SKB229"), "W1e": skp("GO-W1e"), "trial": skp("GO-W1e-skintrial"), "W1f": skp("GO")}
    for k in KEYS:
        T.append("| %s | %s |" % (k, " | ".join(f4(S[n]["by_t"]["0.5"]["ratio"].get(k)) for n in ("MF-M-R", "SK", "SKB", "W1e", "trial", "W1f"))))
    T += ["", "Contour diagnostics (`skeletal/contour_clearance.json`; chest-lead > 0 = the chest leads the abdomen; buttock-lead = gluteal projection behind the lumbar back; both / stature):", "", "| Body | chest-lead | buttock-lead |", "|---|---|---|"]
    for k, v in CC["contour"].items(): T.append("| %s | %.4f | %.4f |" % (k, v["chest_lead"], v["buttock_lead"]))
    T += ["", "## 5. Grask before / after", "", "The W1f GR skeleton is the W1e GR skeleton (same inputs and bone scales); only the envelope route changed (unscaled tissue), so the skeletal readings are identical before and after and the skin readings differ only in the 4th decimal (`candidates/GR_meas.json` vs `reviews/rac-w1e-evidence/candidates/GR_meas.json`).", "",
          "| Reading | MF-M-R skeletal | GR skeletal (W1e = W1f) | GR skin W1e | GR skin W1f |", "|---|---|---|---|---|"]
    G = skp("GR"); g1 = jl(E1, "candidates", "GR_meas.json")["combined"]["ratio"]; g2 = jl(EV, "candidates", "GR_meas.json")["combined"]["ratio"]
    for k in ("thorax_breadth_share", "thorax_depth_share", "thorax_d_over_b", "gh_breadth_share", "biacromial_share", "S1_over_S2_b", "biacromial_over_S2_b", "ribcage_vertical_over_S2_b", "pelvis_over_thorax_breadth", "leg_share", "torso_share"):
        T.append("| %s | %s | %s | %s | %s |" % (k, f4(S["MF-M-R"]["by_t"]["0.5"]["ratio"].get(k)), f4(G["by_t"]["0.5"]["ratio"].get(k)), f4(g1.get(k)), f4(g2.get(k))))
    T += ["", "Arm clearance at the R-6 stance (GR-G3 support reading, left side):", "", "| Body | min arm-trunk gap (cm) | upper-arm vertices medial of the trunk wall |", "|---|---|---|"]
    for k, v in CC["arm_clearance"].items(): T.append("| %s | %.2f | %d of %d |" % (k, v["min_arm_trunk_gap_cm"], v["upperarm_verts_medial_of_trunk_wall"], v["n_upperarm"]))
    # 6 ocular
    T += ["", "## 6. Ocular (`ocular/ocular_w1f.json`)", "", "Source: " + OC["source"], "", "| Body | delta | Ring breadth x height (cm) | Ring inside skin | Ring-globe clearance (cm) | Landmark globe (cm) | Globe skin verts inside | ORB/HL vs MF | ORB/HH vs MF | globe/HH vs MF | IOD/HL vs MF | Fits |", "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for i, r in OC["bodies"].items():
        v = r["vs_MF"]; T.append("| %s | %.2f | %.3f x %.3f | %.0f %% | %.2f | %.3f | %d | %.3f | %.3f | %.3f | %.3f | %s |" % (i, r["delta"], r["ring_breadth_cm"], r["ring_height_cm"], 100 * r["ring_inside_skin_frac"], r["ring_globe_clearance_cm"], r["globe_cm"], r["globe_skin_verts_inside"], v["ORB_breadth"], v["ORB_height"], v["globe_over_HH"], v["IOD_over_HL"], r["fits"]))
    T += ["", "FN vs MF-F-R (female source ring): breadth x%.4f, height x%.4f." % (OC["FN_vs_MF-F-R"]["breadth"], OC["FN_vs_MF-F-R"]["height"]), ""]
    # 7 directional / skin / HV / ears
    nd = [x for x in DC if res(x) != "PASS"]
    T += ["## 7. Cross-race directional checks (`directional_checks.json`; %d rows: %s)" % (len(DC), cnt(DC)), ""] + rows_md(nd)
    T += ["", "HV source span (rebuilt FN, AE, VA as sources):", ""] + rows_md([x for x in DC if x["cand"] == "HV"])
    T += ["", "## 8. Skin diagnostics of the accepted relations (`w1e_checks.json`; composition-inclusive, PV-D16; %d rows: %s)" % (len(WC), cnt(WC)), "",
          "Skin layer only (reference composition). Rows marked NOT RUN here are skeletal-only items and were run on the skeletal proxy (§2–3); ALPC-7 on skin is against central Skarn. Non-PASS rows:", ""] + rows_md([x for x in WC if x["result"] not in ("PASS", "NOT RUN")])
    T += ["", "## 9. Ears on the W1f bodies (`ears/`; %s)" % cnt(EC), "", "| Body | Family | Scale | Height (cm) | Lateral extent (cm) |", "|---|---|---|---|---|"]
    for b, r in EA.items(): T.append("| %s | %s | %.3f | %.2f | %.2f |" % (b, r["family"], r["l"]["scale"], r["l"]["auricle_height_cm"], r["l"]["lateral_extent_from_skull_root_cm"]))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n")
    # ARM records for rebuilt candidates
    for i, desc in (("GO", "Gorrund central — AD-G14 skeletal-trunk proxy + sculpted envelope"), ("GR", "Grask central — AD-G14 skeleton + envelope"), ("VA", "Vael central — pelvic depth +3 % for PV-D6 on the skeletal proxy")):
        m = jl(EV, "candidates", i + "_meas.json"); geo = os.path.join(EV, "geometry", i + "_r6.npz"); sk = skp(i)
        L = ["# RAC W1f ARM record — %s (%s)" % (i, desc), "", "Generated by `tools/rac/w1/gen_w1f_docs.py`. Status: see `reviews/claude-rac-w1f-author-acceptance-gate.md`.", "",
             "- Geometry: `%s` (sha256 %s); skeleton: `reviews/rac-w1f-evidence/skeleton/%s-LEAN_r6.npz`" % (os.path.relpath(geo, R), sha(geo), i),
             "- Config: `tools/rac/w1/cfg/w1f/%s.json`" % i,
             "- Stature (R-6) %.2f cm; HH %.2f cm; landmark globe %.3f cm; largest rigid-set pose change %.3f cm" % (m["stature_r6"], m["combined"]["cranio"]["HH"], m["combined"]["cranio"]["eye_diam_cm"], max(v["max_abs_change_cm"] for v in m["invariance"]["rigid_sets"].values())),
             "- Skeletal-envelope alignment: scale %.4f, joint residual %.3f cm" % (sk["align_scale"], sk["align_joint_resid_cm"]), "",
             "## Skeletal checks", "", "(ALPC-5 / -6 / -7 at 208 cm / -8 are run in `reviews/rac-w1f-evidence/tables.md` §3; their placeholder rows are omitted here.)", ""] + rows_md([x for x in SK if x["cand"] == i and x["result"] != "NOT RUN"], by_t=True)
        L += ["", "## Directional checks", ""] + rows_md([x for x in DC if x["cand"] == i])
        L += ["", "## Skin diagnostics (accepted relations; composition-inclusive)", ""] + rows_md([x for x in WC if x["cand"] == i and x["result"] != "NOT RUN"])
        open(os.path.join(ARM, "claude-rac-w1f-arm-%s.md" % i), "w").write("\n".join(L) + "\n")
    print("tables + ARM records written")

if __name__ == "__main__":
    main()
