"""Generate the RAC W2I1 (Saurin closure) evidence tables from reviews/rac-w2i-sa-evidence/closure (no hand-typed numbers)."""
import json, os, collections
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2i-sa-evidence", "closure")
L = lambda f: json.load(open(os.path.join(EV, f)))
def f4(v):
    if isinstance(v, bool): return str(v)
    if isinstance(v, float): return "%.4f" % v
    if isinstance(v, (list, tuple)): return " / ".join(f4(x) for x in v)
    return "—" if v is None else str(v)
def caps(T, d, key, title):
    if key not in d: return
    T += ["### " + title, "", "| State | stature | same-state reference lean | reachable cap (% H) | binding | 55 % at this base |", "|---|---|---|---|---|---|"]
    for sn, s in d[key].items(): T.append("| %s | %s | %s | %s | %s | %s |" % (sn, f4(s['stature']), f4(s['lean_ref']), f4(s['reachable_cap_pct']), ", ".join(s['binding']) or "—", "fails " + ", ".join(s['low_end_55_fail']) if s['low_end_55_fail'] else "PASS"))
    T += ["", "| State | pct | base | RSI | taper | A50 | A25 | Δlean same-state | Δlean vs SA-M188 (secondary) | d/w | ok |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for sn, s in d[key].items():
        for r in s['rows']: T.append("| %s | %s | %.3f | %.3f | %.3f | %.3f | %.3f | %+.2f | %+.2f | %.3f | %s |" % (sn, f4(r['pct']), r['base'], r['RSI'], r['taper'], r['A50'], r['A25'], r['dlean_same_state'], r['dlean_SA_M188'], r['dw'], "OK" if r['ok'] else "x " + ",".join(k for k, v in r['guards'].items() if not v)))
    T.append("")
def named(T, d, title):
    T += ["### " + title, "", "| Case | state | base | tail % H | RSI | A50 | Δlean same-state | Δlean vs SA-M188 | result (same-state rule) |", "|---|---|---|---|---|---|---|---|---|"]
    for nm, r in d['named'].items(): T.append("| %s | %s | %s | %s | %s | %s | %+.2f | %+.2f | %s |" % (nm, r['state'], f4(r['base']), f4(r['tail_len_pct']), f4(r['RSI']), f4(r['A50']), r['dlean_same_state'], r['dlean_SA_M188'], "PASS" if r['ok'] else "FAIL (" + ", ".join(k for k, v in r['guards'].items() if not v) + ")"))
    T.append("")
def main():
    T = ["# RAC W2I1 — Saurin closure: evidence tables", "", "Generated by `tools/rac/w1/gen_w2i1_docs.py` from `reviews/rac-w2i-sa-evidence/closure/*.json`. NON-CANON diagnostics; the frozen SA-M (aff1b52) and SA-F (§263) are never written back.", ""]
    tc = L("tailcap2.json"); T += ["## 1. D2 — reachable tail cap, same-state balance reference (`sa_tailcap2.py`)", "", "State reference = same stature, same frame / composition, reference tail (64.613 %% H, base 1.0). Frozen SA-M188 lean %.3f° (secondary)." % tc['reference_SA-M188']['lean_scaled_deg'], ""]
    named(T, tc, "Named D2 / earlier non-pass cases (recorded bases)")
    caps(T, tc, "rsi119", "D2 (a) cap — most permissive admissible base (RSI 1.19)")
    caps(T, tc, "rsi100", "Report — constant sufficiency base (RSI 1.00)")
    j = L("joints.json"); a = j['audit']
    T += ["## 2. D3 — J-2 joint landmarks (`sa_joints.py`)", "", "Source: %s." % j['source'], "", "| Joint | point (x, f, u cm) | winding number | inside mesh | section centroid offset (cm) | section eq. radius (cm) | joint inside section |", "|---|---|---|---|---|---|---|"]
    for k, r in j['base'].items():
        s = r.get('section', {}); T.append("| %s | %s | %.3f | %s | %s | %s | %s |" % (k, " / ".join("%.2f" % x for x in r['point']), r['winding_number'], r['inside_mesh'], f4(s.get('centroid_offset_cm')), f4(s.get('eq_radius_cm')), f4(s.get('joint_inside_section'))))
    T += ["", "### Invariance audit", "", "| Check | Result |", "|---|---|",
          "| Base mesh V / F SHA-256 before = after | %s / %s |" % (a['mesh_sha_V_before_after'][0] == a['mesh_sha_V_before_after'][1], a['mesh_sha_F_before_after'][0] == a['mesh_sha_F_before_after'][1]),
          "| Base npz file SHA-256 before = after | %s (%s…) |" % (a['base_npz_sha256_before_after'][0] == a['base_npz_sha256_before_after'][1], a['base_npz_sha256_before_after'][0][:12]),
          "| All %d SA-M measure() readings before = after | max abs diff %s |" % (a['measure_readings_compared'], f4(float(a['measure_max_abs_diff']))),
          "| Every warped body unchanged by landmarking (array hash) | %s |" % all(b['body_unchanged_by_landmarking'] for b in j['bodies'].values()),
          "| Points deterministic / weights deterministic | %s / %s |" % (a['deterministic_points'], a['deterministic_weights']),
          "| Affine constraint residual / base reconstruction (cm) | %.1e / %.1e |" % (a['affine_constraint_residual_cm'], a['base_reconstruction_max_cm']),
          "| Affine-exactness test (arbitrary affine map, cm) | %.1e |" % a['affine_exactness_max_cm'],
          "| Transport control (ring-centroid displacement vs affine weights, max over bodies, cm) | %.3f |" % max(b['transport_control_max_cm'] for b in j['bodies'].values()), ""]
    T += ["| Reading | " + " | ".join(k for k in a['readings_checked']) + " |", "|---|" + "---|" * len(a['readings_checked']), "| before / after | " + " | ".join("%.4f / %.4f" % tuple(v) for v in a['readings_checked'].values()) + " |", ""]
    K = ["upperarm", "forearm", "hand", "hand_noclaw", "palm", "arm", "thigh", "shin", "leg_joint", "hip_height", "ankle_height", "elbow_breadth", "elbow_depth", "wrist_breadth", "wrist_depth", "knee_breadth", "knee_depth", "ankle_breadth", "ankle_depth", "S7_breadth", "S7_depth", "mid_humerus_breadth", "mid_forearm_breadth", "mid_shin_breadth"]
    T += ["### Saurin J-2 readings (cm, mean of sides)", "", "| Body | H | " + " | ".join(K) + " | S7 CIB b / d (t 0.5) |", "|---|---|" + "---|" * (len(K) + 1)]
    for bid, b in j['bodies'].items(): T.append("| %s | %.2f | %s | %.2f / %.2f |" % (bid, b['stature'], " | ".join("%.2f" % b['mean'][k] for k in K), b['S7_CIB']['0.5']['S7_breadth'], b['S7_CIB']['0.5']['S7_depth']))
    lc = L("limbcmp.json"); V = lc['values']
    RK = ["leg_share", "leg_share_station", "leg_joint_share", "thigh_share", "shin_share", "femur_over_leg", "arm_share", "span_der", "upperarm_share", "forearm_share", "hand_share", "forearm_over_arm", "distal_over_arm",
          "elbow_sec_share", "wrist_sec_share", "knee_sec_share", "ankle_sec_share", "ankle_height_share"]
    T += ["", "## 3. D3 — limb readings, Saurin and comparators (`sa_limbcmp.py`)", "", "| Body | H | " + " | ".join(RK) + " | S7 b / H (t 0 / 0.5 / 1) | S7 d / H (t 0.5) |", "|---|---|" + "---|" * (len(RK) + 2)]
    for k, v in V.items():
        if not (k.startswith("SA-") and k.count("-") <= 2 or not k.startswith("SA-")): continue
        T.append("| %s | %.2f | %s | %s | %s |" % (k, v['stature'], " | ".join(f4(v.get(x)) for x in RK), " / ".join("%.4f" % v['S7'][t]['b'] for t in ("0.0", "0.5", "1.0") if t in v['S7']), f4(v['S7'].get('0.5', {}).get('d'))))
    T += ["", "Control (recomputed exact-plane section / R-6 stature vs committed W2H evidence): " + "; ".join("%s %s %.5f vs %.5f" % (mk, jj, x[0], x[1]) for mk, d in lc['control'].items() for jj, x in d.items()), ""]
    T += ["### Vertical budget (share of standing height)", "", "| Pair | segment | Saurin | Marchfolk |", "|---|---|---|---|"]
    for pair, d in lc['budget'].items():
        sa, mf = list(d.values())
        T += ["| %s | ground → hip | %.4f (J-2) / %.4f (station u91) | %.4f |" % (pair, sa['ground -> hip (J-2 construction hip)'], sa['ground -> hip station u91'], mf['ground -> hip (rig)']),
              "| %s | hip → costal (LT1) | %.4f | %.4f |" % (pair, sa['hip station -> costal (LT1)'], mf['hip -> costal proxy (LT1)']), "| %s | costal → vertex | %.4f | %.4f |" % (pair, sa['costal -> vertex'], mf['costal -> vertex'])]
    T += ["", "### Validator rows", "", "| Code | Check | A | Value | Op | B | Value | Δ % | Raw class | Surface structural reading |", "|---|---|---|---|---|---|---|---|---|---|"]
    for r in lc['rows']: T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (r['code'], r['check'], r['a'], f4(r.get('va')), r.get('op'), r['b'], f4(r.get('vb')), "%+.1f" % r['margin_pct'] if r.get('margin_pct') is not None else "—", r['result'], "yes" if r.get('structural_surface') else ""))
    T += ["", "Row counts: " + ", ".join("%s %s %d" % (a_, b_, n) for (a_, b_), n in sorted(collections.Counter((r['code'], r['result']) for r in lc['rows']).items())), ""]
    c = L("carriage.json"); T += ["## 4. D4 — neutral-carriage test (`sa_carriage.py`)", "", "| Body / lift | visible extent below crotch (cm) | covered share of gap | max visible width (cm) | lowest tail vertex u | crotch u | tip u | distal 20 cm elevation (°) | root tangent change 10 cm (°) | Δlean vs 0° | non-tail max shift (cm) | root shift (cm) | max |Δ| tail readings (%) |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for k, r in c.items():
        s = r['silhouette']; t = r['tail']; dd = r.get('tail_readings_delta_pct', {})
        T.append("| %s | %.1f | %.4f | %.1f | %.1f | %.1f | %.1f | %.1f | %.2f | %s | %s | %s | %s |" % (k, s['visible_extent_cm'], s['covered_share'] or 0, r['max_visible_width_cm'], t['lowest_tail_vertex_u'], s['crotch_u'], t['tip_u'], t['distal20_elevation_deg'], t['root_tangent_change_10cm_deg'],
                 "%+.3f" % r['dlean_vs_0deg'] if 'dlean_vs_0deg' in r else "0", "%.1e" % r['nontail_vertices_max_shift_cm'] if 'nontail_vertices_max_shift_cm' in r else "0", "%.1e" % r['root_point_shift_cm'] if 'root_point_shift_cm' in r else "0",
                 "%.4f" % max(abs(x) for x in dd.values()) if dd else "0"))
    if os.path.exists(os.path.join(EV, "tailcap2_lift8.json")):
        t8 = L("tailcap2_lift8.json"); T += ["", "## 5. Tail-cap regression at +8° carriage (information; no carriage recommended)", ""]; named(T, t8, "Named cases at +8°"); caps(T, t8, "rsi119", "Cap at +8° (RSI 1.19 base)")
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
