"""Generate the RAC W2B (Skarn boundary foundation) evidence tables from the JSON in reviews/rac-w2b-sk-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2b-sk-evidence")
fv = lambda v: " / ".join("%.4f" % x for x in v) if isinstance(v, list) else ("%.4f" % v if isinstance(v, float) else str(v))
GROUPS = [("Stature foundation", ["SK-M183", "SK-M208", "SK-M229", "SK-F183", "SK-F208", "SK-F229"]),
          ("Marchfolk overlap", ["SK-M190", "MF-M190", "SK-M203", "MF-M203", "SK-F190", "MF-F190", "SK-F203", "MF-F203"]),
          ("Frames and bridge", ["SK-M Narrow", "SK-M208", "SK-M Broad", "SK-F Narrow", "SK-F208", "SK-F Broad", "SK W1 Broad (SKB208)", "GO-H208", "SG"]),
          ("Composition and named extremes", ["SK-M LOWMUS", "SK-M HIMUS", "SK-M HIFAT", "SK-M HIBOTH", "SK-F LOWMUS", "SK-F HIMUS", "SK-F HIFAT", "SK-F HIBOTH", "SK-02", "SK-04"])]
CODES = {"U": "no uniform scaling", "C": "continuity", "K": "joints vs allometric expectation", "O": "Marchfolk overlap (190 / 203)", "P": "canonical pair MF 203 vs SK 183",
         "D": "frame domains", "L": "frame keeps lengths", "N": "Narrow stays Skarn", "G": "Broad not Gorrund", "A7": "ALPC-7 re-check", "M": "composition invariance", "X": "named extremes"}
def main():
    d = json.load(open(os.path.join(EV, "w2b.json"))); V = d["values"]
    T = ["# RAC W2B — Skarn boundary foundation: evidence tables", "", "Generated by `tools/rac/w1/gen_w2b_docs.py` from `w2b.json`. NON-CANON diagnostics. Skeletal readings: CIB grids (t = 0 shown; t = 0.5 / 1.0 in the JSON). Joints: stature-scaled slab. Rule: AD-G10.", ""]
    if os.path.exists(os.path.join(EV, "construction.json")):
        T += ["## Construction", "", "```json", json.dumps(json.load(open(os.path.join(EV, "construction.json"))), indent=1)[:12000], "```", ""]
    for title, cols in GROUPS:
        cols = [c for c in cols if c in V]
        keys = [k for k in V[cols[0]] if "[t=0.5]" not in k and "[t=1.0]" not in k and not k.startswith("ALPC")] if cols else []
        T += ["## %s" % title, "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for k in keys: T.append("| %s | %s |" % (k.replace(" [t=0.0]", " (skeletal)"), " | ".join(("%.4f" % V[c][k]) if k in V[c] else "—" for c in cols)))
        T.append("")
    T += ["## Checks", ""]
    for code, name in CODES.items():
        cc = [c for c in d["checks"] if c["code"] == code]
        if not cc: continue
        T += ["### %s — %s (%d; not PASS: %d)" % (code, name, len(cc), sum(c["result"] not in ("PASS",) and not c["result"].startswith("REPORT") for c in cc)), "", "| Check | A | Value | Op | B | Value | Result | Note |", "|---|---|---|---|---|---|---|---|"]
        for c in cc: T.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (c["check"], c["a"], fv(c["va"]), c["op"], c["b"], fv(c["vb"]) if c["vb"] is not None else "", c["result"] if c["result"] == "PASS" or c["result"].startswith("REPORT") else "**%s**" % c["result"], c["note"]))
        T.append("")
    T += ["## Diagnostic envelope candidates (NON-CANON)", "", "| Reading | min | body | max | body |", "|---|---|---|---|---|"]
    for k, e in d["envelope_candidates"].items():
        if "[t=0.5]" in k or "[t=1.0]" in k: continue
        T.append("| %s | %.4f | %s | %.4f | %s |" % (k, e["min"], e["min_body"], e["max"], e["max_body"]))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
