"""Generate the RAC W2I2 (Saurin canon-restoration candidate study) evidence tables from reviews/rac-w2i2-sa-evidence (no hand-typed numbers)."""
import json, os, glob, collections
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2i2-sa-evidence")
L = lambda f: json.load(open(os.path.join(EV, f)))
def f4(v):
    if isinstance(v, bool): return str(v)
    if isinstance(v, float): return "%.4f" % v
    return "—" if v is None else str(v)
SEG = ["ground_ankle", "ankle_knee", "knee_hip", "hip_pelvic_transition", "lower_axial_trunk", "thoracic", "neck", "head_height"]
def main():
    T = ["# RAC W2I2 — Saurin canon-restoration candidate study: evidence tables", "", "Generated by `tools/rac/w1/gen_w2i2_docs.py`. Candidates are COPIES; the frozen SA-M (aff1b52) / SA-F (§263) are unchanged.", ""]
    lg = L("ledger.json"); T += ["## 1. Stature-budget ledger (share of standing height)", "", "Saurin hip = Gate 4 B1-axis hip (J-2); 'hip → pelvic transition' = B1 hip → pelvic hip-joint station u 91. MPFB: rig joints (transition 0 by definition).", "",
                                  "| Body | H | " + " | ".join(SEG) + " | sum check |", "|---|---|" + "---|" * (len(SEG) + 1)]
    for grp in ("saurin", "comparators"):
        for b, d in lg[grp].items(): T.append("| %s | %.2f | %s | %.1e |" % (b, d['height'], " | ".join("%.4f" % d['share'][k] for k in SEG), d['sum_check']))
    T += ["", "## 2. Candidates at 188 cm (male / female centre) — hip = pelvic station", ""]
    K = ["leg_share", "B1_hip_share", "leg_joint_share", "femur_over_leg", "shin_over_leg", "LT_share", "TV_share", "neck_share", "head_height_share", "height", "head_len", "dw",
         "upperarm_share", "forearm_share", "arm_to_wrist_share", "arm_share", "forearm_over_arm", "forearm_over_upperarm", "hand_over_arm", "elbow_u", "elbow_sec_share", "wrist_sec_share", "span_der", "lean"]
    T += ["| Candidate | body | " + " | ".join(K) + " |", "|---|---|" + "---|" * len(K)]
    for c in ("AS", "L1", "L2", "L3", "F1", "F2", "F3", "L1F2"):
        fn = "eval_%s.json" % c
        if not os.path.exists(os.path.join(EV, fn)): continue
        V = L(fn)['values']
        for b in ("SA-M188", "SA-F188", "SA-M168", "SA-M208"):
            if b in V: T.append("| %s | %s | %s |" % (c, b, " | ".join(f4(V[b].get(k)) for k in K)))
    T += ["", "## 3. Candidate rows (counts; non-pass listed)", ""]
    for c in ("AS", "L1", "L2", "L3", "F1", "F2", "F3", "L1F2"):
        fn = "eval_%s.json" % c
        if not os.path.exists(os.path.join(EV, fn)): continue
        e = L(fn); T += ["### %s" % c, "", "Candidate rows: " + ", ".join("%s %d" % (k, n) for k, n in sorted(e['counts'].items())), "",
                        "Accepted W2I comparison script (`sa_compare.py`) on the candidate set: " + "; ".join("%s %s" % (k, v) for k, v in e['compare_counts'].items()) + " — non-pass %d" % len(e['compare_nonpass']), ""]
        nps = [r for r in e['rows'] if r['result'] in ('FAIL', 'NOT DEMONSTRATED')]
        if nps:
            T += ["| Code | Check | value | vs | Δ % | class |", "|---|---|---|---|---|---|"]
            for r in nps: T.append("| %s | %s | %.4f | %.4f | %+.2f | %s |" % (r['code'], r['check'], r['va'], r['vb'], r['margin_pct'], r['result']))
            T.append("")
        T += ["<details><summary>all %s rows</summary>" % c, "", "| Code | Check | value | op | vs | Δ % | class |", "|---|---|---|---|---|---|---|"]
        for r in e['rows']:
            if r['code'] == 'BUD': continue
            T.append("| %s | %s | %s | %s | %s | %s | %s |" % (r['code'], r['check'], f4(r['va']), r['op'], f4(r['vb']), "%+.2f" % r['margin_pct'] if r.get('margin_pct') is not None else "—", r['result']))
        T += ["", "</details>", ""]
    if os.path.exists(os.path.join(EV, "saeval_L1F2.json")):
        for c in ("ASfull", "L1F2"):
            d = L("saeval_%s.json" % c); cnt = collections.Counter((x['code'], x['result']) for x in d['checks'])
            T += ["## 4. Accepted W2I internal checks (`sa_eval.py`) — %s" % c, "", ", ".join("%s %s %d" % (a, b, n) for (a, b), n in sorted(cnt.items())), ""]
            T += ["| Code | Check | Value | Op | Limit / B | Result | Note |", "|---|---|---|---|---|---|---|"]
            for x in d['checks']:
                if x['result'] not in ('PASS', 'REPORT'): T.append("| %s | %s | %s | %s | %s | %s | %s |" % (x['code'], x['check'], f4(x.get('va')), x.get('op'), f4(x.get('vb')), x['result'], str(x.get('note', '')).replace('|', '/')))
            T.append("")
    rc = L("rootcarriage.json"); T += ["## 5. Root-carriage family (`sa_rootcarriage.py`)", "", "Bend length LP = %s cm (choice rows below)." % rc['LP'], "", "| LP test | max smoothed curvature in bend zone (deg/cm) | as-built free-tail max | centreline min u | ok |", "|---|---|---|---|---|"]
    for k, v in rc['LP_choice'].items():
        if k != 'as_built': T.append("| %s | %.3f | %.3f | %.2f | %s |" % (k, v['max_curv_zone'], rc['LP_choice']['as_built']['max_curv_free'], v['centreline_min_u'], v['ok']))
    T += ["", "| Body / pitch | visible extent (cm) | gap share | max width (cm) | lowest tail u | crotch u | tip u | distal elevation (°) | tangent 10 cm (Δ vs 0°) | max bend curvature | Δlean | non-tail shift | root shift | max |Δ| tail readings % |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    base = {}
    for k, r in rc.items():
        if not isinstance(r, dict) or 'silhouette' not in r: continue
        b = k.split('|')[0]; base.setdefault(b, r['root']['tangent_10cm_deg'])
        s = r['silhouette']; t = r['tail']; dd = r.get('tail_readings_delta_pct', {})
        T.append("| %s | %.1f | %.4f | %.1f | %.1f | %.1f | %.1f | %.1f | %+.2f | %.2f | %s | %s | %s | %s |" % (k, s['visible_extent_cm'], s['covered_share'] or 0, r['max_visible_width_cm'], t['lowest_tail_vertex_u'], s['crotch_u'], t['tip_u'], t['distal20_elevation_deg'],
                 r['root']['tangent_10cm_deg'] - base[b], r['root']['max_curv_zone'], "%+.3f" % r['dlean_vs_0deg'] if 'dlean_vs_0deg' in r else "0", "%.1e" % r['nontail_vertices_max_shift_cm'] if 'nontail_vertices_max_shift_cm' in r else "0",
                 "%.1e" % r['root_point_shift_cm'] if 'root_point_shift_cm' in r else "0", "%.4f" % max(abs(x) for x in dd.values()) if dd else "0"))
    if os.path.exists(os.path.join(EV, "tailcap_L1F2.json")):
        tc = L("tailcap_L1F2.json"); T += ["", "## 6. Same-state tail caps on L1 + F2 (`run_tailcap_cand.py` -> W2I1 `sa_tailcap2.py`, RSI 1.19 base)", "",
                                           "| Named case | state | base | Δlean same-state | Δlean vs candidate SA-M188 | result |", "|---|---|---|---|---|---|"]
        for nm, r in tc['named'].items(): T.append("| %s | %s | %s | %+.2f | %+.2f | %s |" % (nm, r['state'], r['base'], r['dlean_same_state'], r['dlean_SA_M188'], "PASS" if r['ok'] else "FAIL"))
        T += ["", "| State | cap (% H) | binding | 55 % on this base |", "|---|---|---|---|"]
        for sn, d in tc['rsi119'].items(): T.append("| %s | %s | %s | %s |" % (sn, d['reachable_cap_pct'], ", ".join(d['binding']), ", ".join(d['low_end_55_fail']) or "PASS"))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
