"""Generate the RAC W2A (Marchfolk boundary foundation, RM-UB-07) evidence tables from the JSON in reviews/rac-w2a-mf-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2a-mf-evidence")
jl = lambda *p: json.load(open(os.path.join(*p)))
ex = lambda f: os.path.exists(os.path.join(EV, f))
fv = lambda v: " / ".join("%.4f" % x for x in v) if isinstance(v, list) else ("%.4f" % v if isinstance(v, float) else str(v))
def main():
    B = jl(EV, "boundary.json"); V = B["values"]
    T = ["# RAC W2A — Marchfolk boundary foundation (RM-UB-07): evidence tables", "", "Generated by `tools/rac/w1/gen_w2a_docs.py` from the JSON in this folder. **Every value is a NON-CANON diagnostic.** M = configuration 1 (MF-M-R), F = configuration 2 (MF-F-R). Routes: 147 cm native short-adult regional route; 173 cm accepted W1 ARMs; 203 cm generator height macro re-solved. Skeletal readings: CIB stations (t = 0 / 0.5 / 1.0). Joint readings: stature-scaled slab. Rule: AD-G10.", ""]
    cols = [c for c in ("M147", "M173", "M203", "F147", "F173", "F203", "SK", "AE", "FN", "CHILD147") if c in V]
    T += ["## 1. Measurements", "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
    for k in V["M173"]: T.append("| %s | %s |" % (k, " | ".join(("%.4f" % V[c][k]) if k in V[c] else "—" for c in cols)))
    T += ["", "## 2. RM-UB-07 checks", "", "| Code | Check | A | Value(s) | Op | B | Value | Result | Note |", "|---|---|---|---|---|---|---|---|---|"]
    for c in B["checks"]: T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (c["code"], c["check"], c["a"], fv(c["va"]), c["op"], c["b"], fv(c["vb"]) if c["vb"] is not None else "", c["result"] if c["result"] in ("PASS", "REPORT") else "**%s**" % c["result"], c["note"]))
    if "route_crosscheck" in B:
        T += ["", "## 3. Route cross-checks (% difference)", ""]
        for k, d in B["route_crosscheck"].items():
            T += ["### %s" % k, "", "| Reading | % |", "|---|---|"] + ["| %s | %+.1f %% |" % kv for kv in d.items()] + [""]
    T += ["## 4. Diagnostic envelope candidates (NON-CANON; min / max over the six boundary-set bodies)", "", "| Reading | min | body | max | body |", "|---|---|---|---|---|"]
    for k, e in B["envelope_candidates"].items(): T.append("| %s | %.4f | %s | %.4f | %s |" % (k, e["min"], e["min_body"], e["max"], e["max_body"]))
    if ex("frames_comp.json"):
        F = jl(EV, "frames_comp.json")
        T += ["", "## 5. Central-stature frames and composition (skin and skeletal)", "", "| Body | " + " | ".join(F["readings"]) + " |", "|---|" + "---|" * len(F["readings"])]
        for b, v in F["values"].items(): T.append("| %s | %s |" % (b, " | ".join(("%.4f" % v[k]) if k in v else "—" for k in F["readings"])))
        T += ["", "| Check | Result | Note |", "|---|---|---|"] + ["| %s | %s | %s |" % (c["check"], c["result"] if c["result"] in ("PASS", "REPORT") else "**%s**" % c["result"], c.get("note", "")) for c in F["checks"]]
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
