"""Generate the RAC W2I4 (Saurin final asset finish / canonicalization prep) evidence tables from reviews/rac-w2i4-sa-evidence."""
import json, os, collections
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2i4-sa-evidence")
E3 = os.path.join(R, "reviews", "rac-w2i3-sa-evidence"); E2 = os.path.join(R, "reviews", "rac-w2i2-sa-evidence")
L = lambda f, d=EV: json.load(open(os.path.join(d, f)))
def f4(v):
    if isinstance(v, bool): return str(v)
    if isinstance(v, float): return "%.4f" % v
    return "—" if v is None else str(v)
SEG = ["ground_ankle", "ankle_knee", "knee_hip_station", "lower_axial_trunk", "thoracic", "neck", "head_height"]
K = ["leg_share", "femur_over_leg", "LT_share", "TV_share", "neck_share", "head_height_share", "height", "head_len", "dw", "forearm_over_arm", "arm_share", "span_der", "lean", "tail_len_pct", "tail_root_area", "tail_RSI_raw"]
def main():
    T = ["# RAC W2I4 — Saurin final asset finish / canonicalization prep: evidence tables", "",
         "Generated by `tools/rac/w1/gen_w2i4_docs.py`. Final candidates are COPIES; the frozen SA-M (aff1b52) / SA-F (§263) and canon are unchanged.", ""]
    BA = L("bodies_AS.json", E2); BR = L("bodies_R.json", E3); BF = L("bodies_F.json")
    T += ["## 1. Stature-budget ledger: frozen vs W2I3 rebuild vs W2I4 final (share of H; hip = pelvic station)", "", "| Body | version | " + " | ".join(SEG) + " | sum check |", "|---|---|" + "---|" * (len(SEG) + 1)]
    for b in ("SA-M188", "SA-F188", "SA-M168", "SA-M203", "SA-M208"):
        for nm, BB in (("frozen", BA), ("W2I3 rebuild", BR), ("W2I4 final", BF)):
            lg = BB[b]['ledger']; T.append("| %s | %s | %s | %.1e |" % (b, nm, " | ".join("%.4f" % lg['share'][k] for k in SEG), lg['sum_check']))
    VA = L("eval_AS.json", E2)['values']; VR = L("eval_R.json", E3)['values']; VF = L("eval_F.json")['values']
    T += ["", "## 2. Limb / body readings: frozen vs W2I3 rebuild vs W2I4 final", "", "| Body | version | " + " | ".join(K) + " |", "|---|---|" + "---|" * len(K)]
    for b in ("SA-M188", "SA-F188", "SA-M168", "SA-F168", "SA-M203", "SA-M208", "SA-F208"):
        for nm, VV in (("frozen", VA), ("W2I3", VR), ("W2I4", VF)):
            if b in VV: T.append("| %s | %s | %s |" % (b, nm, " | ".join(f4(VV[b].get(k)) for k in K)))
    # W2I3 -> W2I4 measurement drift over the whole body list
    mx = 0; worst = None; cnt = 0
    for b in BR:
        for k, x in BR[b].items():
            y = BF[b].get(k)
            if isinstance(x, (int, float)) and not isinstance(x, bool) and isinstance(y, (int, float)) and abs(x) > 1e-3 and k != 'd_com_f':
                cnt += 1; d = abs(y / x - 1)
                if d > mx: mx = d; worst = (b, k, x, y)
    T += ["", "W2I3 → W2I4 drift over %d scalar body measurements (62 bodies; excluding `d_com_f`, a difference of two near-equal numbers): max |Δ| = %.4f %% (%s `%s` %.4f → %.4f)." % (cnt, mx * 100, worst[0], worst[1], worst[2], worst[3])]
    a = L("saeval_R.json", E3)['checks']; b = L("saeval_F.json")['checks']; A = {(x['code'], x['check']): x['result'] for x in a}
    diffs = [(x['code'], x['check'], A.get((x['code'], x['check'])), x['result']) for x in b if A.get((x['code'], x['check'])) != x['result']]
    cnt = collections.Counter((x['code'], x['result']) for x in b)
    T += ["", "## 3. Accepted W2I internal checks (`sa_eval.py`, unchanged) — W2I4 final vs W2I3", "", ", ".join("%s %s %d" % (p, q, n) for (p, q), n in sorted(cnt.items())), "",
          "Result changes vs W2I3: **%d** (of %d checks)." % (len(diffs), len(b))]
    for d in diffs: T.append("- %s %s: %s → %s" % d)
    for x in b:
        if x['result'] not in ('PASS', 'REPORT'): T.append("- non-pass (same as W2I3): %s %s: %s" % (x['code'], x['check'][:140], x['result']))
    e = L("eval_F.json"); er = L("eval_R.json", E3); ra = {(r['code'], r['check']): r['result'] for r in er['rows']}
    T += ["", "## 4. Limb / cross-race rows (`sa_w2i2_eval.py`, unchanged) and `sa_compare.py`", "", "Rows: " + ", ".join("%s %d" % (k, n) for k, n in sorted(e['counts'].items())),
          "", "Identical to W2I3: %s; row-result changes: %d." % (e['counts'] == er['counts'], sum(ra.get((r['code'], r['check'])) != r['result'] for r in e['rows'])), "",
          "Accepted `sa_compare.py`: " + "; ".join("%s %s" % (k, v) for k, v in e['compare_counts'].items()) + " — non-pass %d" % len(e['compare_nonpass']), "",
          "| Code | Check | value | op | vs | Δ % | class |", "|---|---|---|---|---|---|---|"]
    for r in e['rows']:
        if r['code'] == 'BUD': continue
        T.append("| %s | %s | %s | %s | %s | %s | %s |" % (r['code'], r['check'], f4(r['va']), r['op'], f4(r['vb']), "%+.2f" % r['margin_pct'] if r.get('margin_pct') is not None else "—", r['result']))
    t2 = L("tailcap_L1F2.json", E2); t4 = L("tailcap_F.json"); t3 = L("tailcap_R_control.json")
    T += ["", "## 5. Tail-coupling confirmation (W1 `sa_tailcap2.py`, same-state rule, RSI 1.19 base convention)", "",
          "W2I2 = the L1 + F2 study warp (`tailcap_L1F2.json`); W2I3 = the clean rebuild without the W2I4 finish (control run, `FINISH=0`); W2I4 = the final asset.", "",
          "| State | W2I2 cap % | W2I3 rebuild cap % | W2I4 final cap % | W2I4 − W2I3 | binding | 55 % low end |", "|---|---|---|---|---|---|---|"]
    for s in t4['rsi119']:
        x = t2['rsi119'].get(s, {}); c = t3['rsi119'].get(s, {}); y = t4['rsi119'][s]
        T.append("| %s | %s | %s | %.3f | %s | %s | %s |" % (s, "%.3f" % x['reachable_cap_pct'] if x else "—", "%.3f" % c['reachable_cap_pct'] if c else "—", y['reachable_cap_pct'], "%+.3f" % (y['reachable_cap_pct'] - c['reachable_cap_pct']) if c else "—", ", ".join(y['binding']), ", ".join(y['low_end_55_fail']) or "ok"))
    T += ["", "| Named case | W2I2 dlean | W2I3 rebuild dlean | W2I4 final dlean | W2I4 − W2I3 | W2I4 failing guards | W2I4 ok |", "|---|---|---|---|---|---|---|"]
    for k, y in t4['named'].items():
        x = t2['named'].get(k, {}); c = t3['named'].get(k, {})
        T.append("| %s | %s | %s | %.4f | %s | %s | %s |" % (k, "%.4f" % x['dlean_same_state'] if x else "—", "%.4f" % c['dlean_same_state'] if c else "—", y['dlean_same_state'], "%+.4f" % (y['dlean_same_state'] - c['dlean_same_state']) if c else "—", ", ".join(g for g, v in y['guards'].items() if not v) or "none", y['ok']))
    fc = L("fieldcheck.json")
    T += ["", "## 6. Scale-field continuity (`sa_fieldcheck.py`): vertical / horizontal correlation-length ratio of the scale relief, and regenerated seed spacing", "",
          "| Region | median R (cm) | frozen field on frozen body (control) | BEFORE: frozen field carried onto L1 + F2 | AFTER: regenerated | after seed NN / R |", "|---|---|---|---|---|---|"]
    for k, v in fc.items():
        if k == 'all_seeds_nn_over_R': continue
        T.append("| %s | %.2f | %.3f | %.3f | %.3f | %.3f |" % (k, v['median_R_cm'], v['frozen']['v_over_h'], v['before']['v_over_h'], v['after']['v_over_h'], v['after_seed_nn_over_R_median']))
    T += ["", "All regenerated seeds: nearest-neighbour spacing / R p10 %.3f, p50 %.3f, p90 %.3f." % tuple(fc['all_seeds_nn_over_R'][k] for k in ('p10', 'p50', 'p90'))]
    q = L("quality.json")
    T += ["", "## 7. Asset quality (`sa_quality.py`)", "", "### 7a. Edge-length strain vs the frozen body (p1 / p50 / p99 / min / max) and flipped faces", "", "| Body | comparison | region | p1 | p50 | p99 | min | max |", "|---|---|---|---|---|---|---|---|"]
    for bb in ("SA-M188", "SA-F188"):
        for nm in ("W2I3_vs_frozen", "finished_vs_frozen", "finished_vs_W2I3"):
            for rg, d in q[bb][nm].items():
                if rg == 'flipped_faces': continue
                T.append("| %s | %s | %s | %.3f | %.3f | %.3f | %.3f | %.3f |" % (bb, nm, rg, d['p1'], d['p50'], d['p99'], d['min'], d['max']))
            T.append("| %s | %s | flipped faces | %s | | | | |" % (bb, nm, q[bb][nm]['flipped_faces']))
    T += ["", "### 7b. Flip census over the 62-body list", "", "Totals: " + ", ".join("%s %d" % kv for kv in q['flip_census_totals'].items()), "",
          "Bodies with any pre-existing W2I3 flips: " + (", ".join("%s (%d)" % (b, v['W2I3_vs_frozen']) for b, v in q['flip_census'].items() if v['W2I3_vs_frozen']) or "none")]
    tp = q['topology_SA-M188_surfaced']
    T += ["", "### 7c. Topology of the final surfaced SA-M188", "", "| Item | value |", "|---|---|"] + ["| %s | %s |" % kv for kv in tp.items()]
    T += ["", "### 7d. Thigh fine relief (1.5 cm split) correlation length (cm)", "", "| Version | vertical | horizontal | v / h |", "|---|---|---|---|"]
    for nm, c in q['thigh_fine_relief_corrlen_cm'].items(): T.append("| %s | %.2f | %.2f | %.2f |" % (nm, c['vertical'], c['horizontal'], c['v_over_h']))
    tr = L("thigh_relief.json")
    T += ["", "### 7d'. Thigh fine relief by sector (`sa_thighrelief.py`; vertical correlation length, cm; native = frozen)", "", "| Version | whole mid-thigh | anterior / lateral (re-modelled) | medial / posterior (kept) |", "|---|---|---|---|"]
    for nm, c in tr.items(): T.append("| %s | %.2f | %.2f | %.2f |" % (nm, c['whole']['vertical'], c['anterolateral']['vertical'], c['medial_posterior']['vertical']))
    T += ["", "### 7e. Finish delta", "", "```", json.dumps(dict(by_zone_max_cm=q['finish_delta_by_zone_max_cm'], outside_zones_and_thigh_max_cm=q['finish_delta_outside_zones_and_thigh_max_cm'], info=q['finish_delta']), indent=1), "```"]
    cp = L("canon_prep.json")
    T += ["", "## 8. Canonicalization prep — exact candidate files (scratch stage; nothing overwritten)", "", "| File | SHA-256 | array SHA-256 | bytes |", "|---|---|---|---|"]
    for k, v in cp.items():
        if isinstance(v, dict) and 'file_sha256' in v: T.append("| `%s` | `%s` | %s | %s |" % (k, v['file_sha256'], "`%s`" % (v.get('v_sha256') or v.get('s_sha256')) if (v.get('v_sha256') or v.get('s_sha256')) else "—", v.get('bytes', '—')))
    T += ["", "Final surfaced SA-M188 vertex SHA-256 `%s` (%d vertices, %d faces, height %.3f cm)." % (cp['final_surface']['v_sha256'], cp['final_surface']['n_vertices'], cp['final_surface']['n_faces'], cp['final_surface']['height']),
          "", "Frozen provenance (kept): " + "; ".join("`%s` %s" % kv for kv in cp['frozen_provenance'].items()),
          "", "Checks: upsample reproduction max %.1e cm; relief-vs-delta reconstruction max %.1e cm; faces identical to the frozen base: %s." % (cp['upsample_check_max_cm'], cp['relief_vs_delta_reconstruction_max_cm'], cp['saurin_w2i4_base.npz']['f_identical_to_frozen'])]
    si = L("surface_info.json")
    T += ["", "## 9. Surface regeneration", "", "```", json.dumps(si, indent=1), "```"]
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
