"""Generate the RAC W2I3 (Saurin reference-quality rebuild / caudal-base closure) evidence tables from reviews/rac-w2i3-sa-evidence."""
import json, os, collections
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2i3-sa-evidence"); E2 = os.path.join(R, "reviews", "rac-w2i2-sa-evidence")
L = lambda f, d=EV: json.load(open(os.path.join(d, f)))
def f4(v):
    if isinstance(v, bool): return str(v)
    if isinstance(v, float): return "%.4f" % v
    return "—" if v is None else str(v)
SEG = ["ground_ankle", "ankle_knee", "knee_hip_station", "lower_axial_trunk", "thoracic", "neck", "head_height"]
K = ["leg_share", "leg_joint_share", "femur_over_leg", "shin_over_leg", "LT_share", "TV_share", "neck_share", "head_height_share", "height", "head_len", "dw",
     "upperarm_share", "forearm_share", "arm_to_wrist_share", "arm_share", "forearm_over_arm", "forearm_over_upperarm", "hand_over_arm", "elbow_u", "span_der", "lean", "tail_len_pct", "tail_root_area", "tail_RSI_raw"]
def main():
    T = ["# RAC W2I3 — Saurin reference-quality rebuild / caudal-base closure: evidence tables", "", "Generated by `tools/rac/w1/gen_w2i3_docs.py`. Candidates are COPIES; the frozen SA-M (aff1b52) / SA-F (§263) are unchanged.", ""]
    BA = L("bodies_AS.json", E2); BD = L("bodies_L1F2.json", E2); BR = L("bodies_R.json")
    T += ["## 1. Stature-budget ledger: frozen vs W2I2 diagnostic vs W2I3 rebuild (share of H; hip = pelvic station)", "", "| Body | version | " + " | ".join(SEG) + " | sum check |", "|---|---|" + "---|" * (len(SEG) + 1)]
    for b in ("SA-M188", "SA-F188", "SA-M168", "SA-M203", "SA-M208"):
        for nm, BB in (("frozen", BA), ("W2I2 diagnostic", BD), ("W2I3 rebuild", BR)):
            lg = BB[b]['ledger']; T.append("| %s | %s | %s | %.1e |" % (b, nm, " | ".join("%.4f" % lg['share'][k] for k in SEG), lg['sum_check']))
    VA = L("eval_AS.json", E2)['values']; VD = L("eval_L1F2.json", E2)['values']; VR = L("eval_R.json")['values']
    T += ["", "## 2. Limb / body readings: frozen vs W2I2 diagnostic vs W2I3 rebuild", "", "| Body | version | " + " | ".join(K) + " |", "|---|---|" + "---|" * len(K)]
    for b in ("SA-M188", "SA-F188", "SA-M168", "SA-F168", "SA-M203", "SA-M208", "SA-F208"):
        for nm, VV in (("frozen", VA), ("W2I2 diag", VD), ("W2I3 rebuild", VR)):
            if b in VV: T.append("| %s | %s | %s |" % (b, nm, " | ".join(f4(VV[b].get(k)) for k in K)))
    e = L("eval_R.json"); T += ["", "## 3. Rebuilt candidate: limb / cross-race rows", "", "Rows: " + ", ".join("%s %d" % (k, n) for k, n in sorted(e['counts'].items())), "",
                                "Accepted `sa_compare.py`: " + "; ".join("%s %s" % (k, v) for k, v in e['compare_counts'].items()) + " — non-pass %d" % len(e['compare_nonpass']), "",
                                "| Code | Check | value | op | vs | Δ % | class |", "|---|---|---|---|---|---|---|"]
    for r in e['rows']:
        if r['code'] == 'BUD': continue
        T.append("| %s | %s | %s | %s | %s | %s | %s |" % (r['code'], r['check'], f4(r['va']), r['op'], f4(r['vb']), "%+.2f" % r['margin_pct'] if r.get('margin_pct') is not None else "—", r['result']))
    for nm, fn, d in (("frozen (as-built re-run)", "saeval_ASfull.json", E2), ("W2I2 diagnostic", "saeval_L1F2.json", E2), ("W2I3 rebuild", "saeval_R.json", EV)):
        c = L(fn, d)['checks']; cnt = collections.Counter((x['code'], x['result']) for x in c)
        T += ["", "## 4. Accepted W2I internal checks (`sa_eval.py`) — %s" % nm, "", ", ".join("%s %s %d" % (a, b, n) for (a, b), n in sorted(cnt.items()))]
        for x in c:
            if x['result'] not in ('PASS', 'REPORT'): T.append("- %s %s: %s (%s)" % (x['code'], x['check'], x['result'], str(x.get('note', ''))[:120]))
    st = L("strain.json"); T += ["", "## 5. Surface strain vs the frozen body (edge-length ratio p1 / p50 / p99 / min / max; flipped faces)", "", "| Body | version | region | p1 | p50 | p99 | min | max |", "|---|---|---|---|---|---|---|---|"]
    for b, v in st.items():
        for nm in ("W2I2_diagnostic", "W2I3_rebuild"):
            for rg, d in v[nm].items():
                if rg == 'flipped_faces': continue
                T.append("| %s | %s | %s | %.3f | %.3f | %.3f | %.3f | %.3f |" % (b, nm, rg, d['p1'], d['p50'], d['p99'], d['min'], d['max']))
            T.append("| %s | %s | flipped faces | %s | | | | |" % (b, nm, v[nm].get('flipped_faces')))
    cd = L("caudal.json"); T += ["", "## 6. Caudal-base contour family C0-C3 (`sa_caudal.py`)", "", "| Body / case | alpha | visible extent (cm) | gap share | max width | lowest tail u | crotch u | gap pixels: zone / free tail / posterior body | lowest visible zone u | root area | RSI raw | Δ tail readings max % | dorsal rise 10 / 20 / 30 cm | ventral rise 10 / 20 / 30 cm | landmark shift | outside-zone shift | Δlean |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for k, r in cd.items():
        s = r['silhouette']; g = r['gap']['share']; dr = r.get('dorsal_rise_cm', {}); vr = r.get('ventral_rise_cm', {}); dd = r.get('tail_delta_pct', {})
        T.append("| %s | %.2f | %.1f | %.4f | %.1f | %.1f | %.1f | %.2f / %.2f / %.2f | %s | %.1f | %.2f | %s | %s | %s | %s | %s | %s |" % (k, r['alpha'], s['visible_extent_cm'], s['covered_share'] or 0, r['max_visible_width_cm'], r['lowest_tail_vertex_u'], s['crotch_u'],
                 g['zone'], g['free_tail'], g['posterior_body'], r['gap']['lowest_visible_zone_u'], r['tail']['tail_root_area'], r['tail']['tail_RSI_raw'], "%.2f" % max(abs(x) for x in dd.values()) if dd else "0",
                 " / ".join("%.1f" % dr.get(x, 0) for x in ("10", "20", "30")) if dr else "—", " / ".join("%.1f" % vr.get(x, 0) for x in ("10", "20", "30")) if vr else "—",
                 "%.1e" % r['landmark_shift_cm'] if 'landmark_shift_cm' in r else "0", "%.1e" % r['pelvis_outside_zone_max_shift_cm'] if 'pelvis_outside_zone_max_shift_cm' in r else "0", "%+.3f" % r['dlean'] if 'dlean' in r else "0"))
    if os.path.exists(os.path.join(EV, "canon_preview.json")):
        cp = L("canon_preview.json"); T += ["", "## 7. Canonicalization preview (hashes only; nothing overwritten)", "", "| Item | file SHA-256 | vertex SHA-256 | vertices | height |", "|---|---|---|---|---|",
                                           "| frozen saurin_final_base.npz | %s | — | — | — |" % cp['frozen']['sha256']]
        for nm in ("SA-M188_rebuilt_base", "SA-F188_rebuilt_realization"): T.append("| %s | %s | %s | %d | %.3f |" % (nm, cp[nm]['file_sha256'], cp[nm]['v_sha256'], cp[nm]['n_vertices'], cp[nm]['height']))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
