"""Generate the RAC W2I (Saurin) evidence tables from reviews/rac-w2i-sa-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2i-sa-evidence")
L = lambda f: json.load(open(os.path.join(EV, f)))
def f4(v):
    if isinstance(v, float): return "%.4f" % v
    if isinstance(v, list): return " / ".join(f4(x) for x in v)
    if isinstance(v, dict): return ", ".join("%s %s" % (k, f4(x)) for k, x in v.items())
    return "—" if v is None else str(v)
def main():
    T = ["# RAC W2I — Saurin: evidence tables", "", "Generated by `tools/rac/w1/gen_w2i_docs.py`. NON-CANON diagnostics. The frozen SA-M (aff1b52) and SA-F (§263) are never written back.", ""]
    rp = L("repro.json"); T += ["## 1. Reproduction (SA-M vs frozen Part 7 reference metrics)", "", "| Reading | W2I | Part 7 | Δ % |", "|---|---|---|---|"]
    for k, (a, b, d) in rp["SA-M_vs_ref_metrics"].items(): T.append("| %s | %s | %s | %s |" % (k, f4(a), f4(b), "%+.3f" % (d or 0)))
    B = L("sa_bodies.json"); B.update(L("sa_extra.json"))
    KEYS = ["height", "k_len", "lower_trunk_costal_hip", "lower_trunk_costal_hip_over_H", "lower_trunk_costal_platform_over_H", "thoracic_vertical_over_H", "thorax_d_over_w", "thorax_d_over_H", "thorax_w_over_H",
            "shoulder_b_over_H", "pelvis_w_over_H", "head_len_ratio", "tail_len_pct", "tail_mass_share", "tail_RSI_raw", "tail_A50", "lean_scaled_deg", "foot_len_over_H"]
    T += ["", "## 2. Saurin bodies (sa_build.py / sa_build_extra.py)", "", "| Body | note | " + " | ".join(KEYS) + " |", "|---|---|" + "---|" * len(KEYS)]
    for b, M in B.items(): T.append("| %s | %s | %s |" % (b, M.get("note", ""), " | ".join(f4(M.get(k)) for k in KEYS)))
    for fn, title in (("sa_eval.json", "3. Internal checks (stature, frames, composition, sex, tails, balance)"), ("compare.json", "4. Cross-race comparisons (common readings; real matched height)")):
        d = L(fn); T += ["", "## " + title, "", "| Code | Check | A | Value | Op | B / limit | Result | Note |", "|---|---|---|---|---|---|---|---|"]
        for c in d["checks"]: T.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (c["code"], c["check"], c.get("a"), f4(c.get("va")), c.get("op"), f4(c.get("vb")) if c.get("vb") is not None else c.get("b", ""), c["result"], str(c.get("note", "")).replace("|", "/")))
    d = L("compare.json"); T += ["", "## 5. Common readings", "", "| Body | stature | " + " | ".join(d["keys"]) + " |", "|---|---|" + "---|" * len(d["keys"])]
    for b, v in d["values"].items():
        if b.startswith("SA") or any(b.startswith(p) for p in ("MF", "SG", "FN", "AE", "VA", "HV", "SK", "GO")) and any(ch.isdigit() for ch in b) and len(b) <= 7:
            T.append("| %s | %s | %s |" % (b, f4(v.get("stature")), " | ".join(f4(v.get(k)) for k in d["keys"])))
    tc = L("tailcap.json"); T += ["", "## 6. RM-UB-04 reachable tail cap", ""]
    for key in ("states_rsi100", "states_rsi120"):
        if key not in tc: continue
        T += ["### %s" % key, "", "| State | cap (% H) | binding guard | rows (pct: base, RSI, taper, A50, A25, Δlean vs SA-M, ok) |", "|---|---|---|---|"]
        for sn, s in tc[key].items():
            T.append("| %s | %s | %s | %s |" % (sn, f4(s["reachable_cap_pct"]), ", ".join(s["binding"]), "; ".join("%s: %.3f, %.3f, %.3f, %.3f, %.3f, %+.2f, %s" % (r["pct"], r["base"], r["RSI"], r["taper"], r["A50"], r["A25"], r["dlean_ref"], "OK" if r["ok"] else "x") for r in s["rows"])))
        T.append("")
    T += ["## 7. SAU-SILHOUETTE (front thigh-gap tail visibility)", "", "| Case | crotch u | covered area cm² | gap area cm² | share | visible extent cm |", "|---|---|---|---|---|---|"]
    for k, v in L("silhouette.json").items(): T.append("| %s | %s | %s | %s | %s | %s |" % (k, f4(v["crotch_u"]), f4(v["covered_area_cm2"]), f4(v["gap_area_cm2"]), f4(v["covered_share"]), f4(v["visible_extent_cm"])))
    fl = L("fields.json"); T += ["", "## 8. RM-UB-08 body scale fields (as built, area-weighted p5 / p50 / p95)", "", "| Field | area cm² | spacing cm | relief cm | elongation |", "|---|---|---|---|---|"]
    for k, v in fl["families"].items(): T.append("| %s | %.0f | %s | %s | %s |" % (k, v["area_cm2"], f4(v["spacing_cm_p5_50_95"]), f4(v["relief_cm_p5_50_95"]), f4(v["elongation_p5_50_95"])))
    cl = L("claws.json"); T += ["", "## 9. Claw / digit coupling (reproduced Part 7 diagnostic)", "", "| Claw length | foot-claw min u (cm) | forefoot envelope change (cm) |", "|---|---|---|"]
    for k in ("k0.80", "k0.90", "k1.00", "k1.15", "k1.30", "k1.50"): T.append("| %s | %s | %s |" % (k, cl[k]["foot_claw_min_u"], cl[k]["foot_length_change_cm"]))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
