"""Generate the RAC W2G (Halvren central envelope) evidence tables from reviews/rac-w2g-hv-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2g-hv-evidence")
f4 = lambda v: "%.4f" % v if isinstance(v, float) else ("—" if v is None else str(v))
GROUPS = [("Halvren central stature family (native < macro 0.40; HV178 = W1 anchor HVC1)", ["HV152", "HV163", "HV173", "HV178", "HV181", "HV190", "HV203", "HV213"]),
          ("Route check: macro builds at 152 / 163 (not used)", ["HV152M", "HV152", "HV163M", "HV163"]),
          ("Accepted source families at 152-163 cm", ["MF152", "SG152", "FN157", "VA157", "MF163", "SG163", "FN163", "VA163"]),
          ("Accepted source families at 173-181 cm", ["MF173", "SG173", "FN173", "AE173", "VA173", "MF178", "SG178", "FN178", "AE178", "VA178", "SK183", "MF181", "SG181", "FN181", "AE181", "VA181"]),
          ("Accepted source families at 190-213 cm", ["MF190", "SG190", "FN190", "AE190", "VA190", "SK190", "MF203", "SG203", "FN203", "AE203", "VA203", "SK203", "SG208", "SK208", "SKB208", "FN211", "AE211"]),
          ("Frames (accepted Halvren breadth-only rule)", ["HVN152", "HV152", "HVB152", "HVN178", "HV178", "HVB178", "HVN213", "HV213", "HVB213"]),
          ("Source-influenced expressions at 178 cm (diagnostic, builder-chosen) + probe", ["HV178", "HVXFN", "HVXAE", "HVXAEc", "HVXVA", "HVXSK", "HVXSG", "HVXMF", "W1HVH3", "W1HVE3"]),
          ("Composition at 173 cm", ["HV173", "HV173-LOWMUS", "HV173-HIMUS", "HV173-HIFAT", "HV173-HIBOTH", "HV173-LOW", "HV173-MIN"]),
          ("Stress combinations HV-36...43, HV-08 / 09", ["HV36", "HV37", "HV38", "HV39", "HV40", "HV41", "HV42", "HV43", "HV08", "HV09"])]
CODES = {"U": "allometry", "C": "continuity (central series)", "O": "source-plausible spans at matched height", "A": "axial / pelvic spans (REPORT)", "P": "body-only source passing",
         "X": "source-influenced expression", "F": "frames", "M": "composition", "S": "stress combinations", "K": "large-human (Skarn) guard (REPORT)", "D": "route check (REPORT)",
         "G": "accepted W1 rows per body (fixed W1 references; REPORT under the boundary-stature rule)"}
def main():
    src = os.environ.get("W2G_JSON", "w2g.json"); out = os.environ.get("W2G_TABLES", "tables.md")     # closure: W2F_JSON=closure/w2f_closure.json W2G_TABLES=closure/tables_closure.md
    d = json.load(open(os.path.join(EV, src))); V = d["values"]
    T = ["# RAC W2G — Halvren central envelope: evidence tables", "", "Generated by `tools/rac/w1/gen_w2g_docs.py`. NON-CANON diagnostics. Skeletal: CIB grids, exact-plane S7 (t = 0 shown in the value tables; rows sweep t = 0 / 0.5 / 1). "
         "Joints: exact-plane section (REFERENCE_ANATOMY_V1 §10). Rule: AD-G10. Halvren rows: the accepted W1 'within source span (MF, SG, FN, AE, VA)' rows read at matched height; spans follow AD-G10 (outside by < 1 % = MARGINAL).", ""]
    for title, cols in GROUPS:
        cols = [c for c in cols if c in V]
        keys = []
        for c in cols: keys += [k for k in V[c] if k not in keys and "[t=0.5]" not in k and "[t=1.0]" not in k]
        T += ["## %s" % title, "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for k in keys: T.append("| %s | %s |" % (k, " | ".join(f4(V[c].get(k)) for c in cols)))
        T.append("")
    T += ["## Checks", ""]
    for code, name in CODES.items():
        cc = [c for c in d["checks"] if c["code"] == code]
        if not cc: continue
        T += ["### %s — %s (%d; not PASS / REPORT: %d)" % (code, name, len(cc), sum(c["result"] not in ("PASS", "OVERSHOOT") and not c["result"].startswith("REPORT") for c in cc) + sum(c["result"] == "OVERSHOOT" for c in cc)), "",
              "| Check | A | Value | Op | B | Value | Margin | Result | Note |", "|---|---|---|---|---|---|---|---|---|"]
        for c in cc:
            va = " / ".join("%.4f" % x for x in c["va"]) if isinstance(c["va"], list) else f4(c["va"])
            vb = " / ".join("%.4f" % x for x in c["vb"]) if isinstance(c["vb"], list) else f4(c["vb"])
            T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (c["check"], c["a"], va, c["op"], c["b"], vb, ("%+.2f %%" % c["margin_pct"]) if isinstance(c.get("margin_pct"), float) else "",
                                                                c["result"] if c["result"] == "PASS" or c["result"].startswith("REPORT") else "**%s**" % c["result"], str(c.get("note", "")).replace("|", "/")))
        T.append("")
    T += ["## Accepted W1 rows per body (not PASS only; fixed W1 references)", "", "| Body | Layer | Row | Result | Value | Reference |", "|---|---|---|---|---|---|"]
    for b, rows in d["canonical_rows"].items():
        if not b.startswith(("HV", "W1HV")): continue
        for x in rows:
            if x["result"] != "PASS": T.append("| %s | %s | %s | %s | %s | %s |" % (b, x["layer"], x["check"], x["result"], f4(x.get("va")), f4(x.get("vb"))))
    open(os.path.join(EV, out), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
