"""Generate the RAC W2D (Gorrund W2) evidence tables from reviews/rac-w2d-go-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2d-go-evidence")
f4 = lambda v: "%.4f" % v if isinstance(v, float) else ("—" if v is None else str(v))
GROUPS = [("Stature family (height macro; no uniform scaling)", ["GO208", "GO218", "GO229", "GOREF", "GO239", "GO251"]),
          ("Matched-height Grask comparators (W2C)", ["GR208", "GR218", "GR229", "GR239", "GR-BODY-10", "GRB2", "GRN5"]),
          ("Matched-height Skarn / Broad Skarn / Marchfolk comparators", ["SK208", "SK218", "SK229", "SKB208", "SKB218", "SKB229", "MF173", "MF203"]),
          ("Frames, named extremes and AD-3 bodies", ["GON5", "GOREF", "GOB7", "GON5_218", "GO218", "GOB7_218", "GOD14_9", "GOD14_9_218", "GOLP218"]),
          ("Composition (reference skeleton)", ["GOREF", "GOR-BODY-06", "GOR-BODY-07", "GOR-BODY-08", "GOR-BODY-09", "GOR-BODY-10", "GOR-BODY-11", "GOR-BODY-16"]),
          ("Composition at 208 cm (vs Skarn states) and 218 cm (vs Grask states)", ["GOR-BODY-06_208", "SK-LOWMUS", "GOR-BODY-07_208", "SK-HIMUS", "GOR-BODY-09_208", "SK-HIFAT", "GOR-BODY-10_208", "SK-HIBOTH",
                                                                                     "GOR-BODY-16_208", "SK-LOW", "GOR-BODY-06_218", "GR-BODY-06", "GOR-BODY-07_218", "GR-BODY-07", "GOR-BODY-09_218", "GR-BODY-08",
                                                                                     "GOR-BODY-10_218", "GR-BODY-09", "GOR-BODY-16_218", "GR-LOW", "MF-LOW"])]
CODES = {"U": "head allometry", "C": "continuity 208 -> 218 -> 229 -> 239 -> 251", "G": "canonical Gorrund rows per body", "S": "matched-height Gorrund vs Grask",
         "K": "matched-height Gorrund vs Skarn", "B": "Broad Skarn (AD-1, ALPC-7)", "F": "frames", "M": "composition", "X": "named extremes GOR-BODY-12 / -14 and RM-LR-03",
         "AD3": "AD-3 closure", "D": "fixed-reference W1 rows at the boundaries (REPORT)"}
def main():
    d = json.load(open(os.path.join(EV, "w2d.json"))); V = d["values"]
    T = ["# RAC W2D — Gorrund W2: evidence tables", "", "Generated by `tools/rac/w1/gen_w2d_docs.py`. NON-CANON diagnostics. Skeletal: CIB grids, exact-plane S7 (t = 0 shown in the value tables; rows sweep t = 0 / 0.5 / 1). "
         "Joints: exact-plane section (REFERENCE_ANATOMY_V1 §10). Rule: AD-G10. G rows count only non-PASS rows that are NEW relative to the accepted reference (GOREF reproduces the accepted W1 Gorrund; GOR-BODY-16 for the ALPC-6 skin half).", ""]
    for title, cols in GROUPS:
        cols = [c for c in cols if c in V]
        keys = []
        for c in cols: keys += [k for k in V[c] if k not in keys and "[t=0.5]" not in k and "[t=1.0]" not in k]
        T += ["## %s" % title, "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for k in keys: T.append("| %s | %s |" % (k, " | ".join(f4(V[c].get(k)) for c in cols)))
        T.append("")
    T += ["## Checks", ""]
    for code, name in CODES.items():
        cc = [c for c in d["checks"] if c["code"] == code]
        if not cc: continue
        T += ["### %s — %s (%d; not PASS / REPORT: %d)" % (code, name, len(cc), sum(c["result"] != "PASS" and not c["result"].startswith("REPORT") for c in cc)), "",
              "| Check | A | Value | Op | B | Value | Margin | Result | Note |", "|---|---|---|---|---|---|---|---|---|"]
        for c in cc:
            va = " / ".join("%.4f" % x for x in c["va"]) if isinstance(c["va"], list) else f4(c["va"])
            vb = " / ".join("%.4f" % x for x in c["vb"]) if isinstance(c["vb"], list) else f4(c["vb"])
            T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (c["check"], c["a"], va, c["op"], c["b"], vb, ("%+.2f %%" % c["margin_pct"]) if isinstance(c.get("margin_pct"), float) else "",
                                                                c["result"] if c["result"] == "PASS" or c["result"].startswith("REPORT") else "**%s**" % c["result"], str(c.get("note", "")).replace("|", "/")))
        T.append("")
    T += ["## Canonical Gorrund rows per body (not PASS only)", "", "| Body | Layer | Row | Result | Shared with accepted reference | Values |", "|---|---|---|---|---|---|"]
    base = {(x["kind"], x["check"]) for b in ("GOREF", "GOR-BODY-16") for x in d["canonical_rows"].get(b, []) if x["result"] not in ("PASS", "REPORT", "NOT RUN")}
    for b, rows in d["canonical_rows"].items():
        for x in rows:
            if x["result"] in ("PASS", "REPORT", "NOT RUN", None): continue
            if x.get("by_t"): v = "; ".join("t%s: %s / %s" % (t, f4(w["va"]), f4(w["vb"])) for t, w in x["by_t"].items())
            else: v = "%s / %s" % (f4(x.get("va")), f4(x.get("vb")))
            T.append("| %s | %s | %s | %s | %s | %s |" % (b, x["kind"], x["check"], x["result"], "yes" if (x["kind"], x["check"]) in base else "**new**", v))
    T += ["", "## Frame and named-extreme probes (skeletal Gorrund rows, reference macro unless named _218)", "", "| Probe | Frame write | Stature | Non-PASS skeletal rows |", "|---|---|---|---|"]
    for n, p in json.load(open(os.path.join(EV, "probes.json"))).items():
        T.append("| %s | `%s` | %.1f | %s |" % (n, json.dumps(p["frame"]), p["stature"], "; ".join("%s %s" % (x["result"], x["check"]) for x in p["non_pass"]) or "— (all pass)"))
    T += ["", "## AD-3 limb-present proportion probes at 218 cm (go_search.py; vs GR-BODY-10)", "", "| Probe | Targets | leg | arm | span | torso | non-PASS directional / skin rows |", "|---|---|---|---|---|---|---|"]
    for n, p in json.load(open(os.path.join(EV, "search_ad3.json"))).items():
        q = p["vs_GR_BODY_10_pct"]
        T.append("| %s | `%s` | %+.1f %% | %+.1f %% | %+.1f %% | %+.1f %% | %s |" % (n, json.dumps(p["targets"]), q["leg_share"], q["arm_share"], q["span_der"], q["torso_share"],
                                                                     "; ".join("%s %s" % tuple(x) for x in p["non_pass"] if x[1] != "NOT RUN")))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
