"""Generate the RAC W1m (Aelari W1 acceptance gate) evidence tables from the JSON in reviews/rac-w1m-ae-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w1m-ae-evidence")
jl = lambda *p: json.load(open(os.path.join(*p)))
def res(r): return r.get("result") or r.get("result_ADG10") or ("PASS" if r.get("pass") else "FAIL")
def fv(v):
    if isinstance(v, (list, tuple)): return " / ".join("%.4f" % x if isinstance(x, (int, float)) else str(x) for x in v)
    return "%.4f" % v if isinstance(v, (int, float)) else str(v)
def margin(r):
    va, vb, op = r.get("va"), r.get("vb"), r.get("op", "")
    if isinstance(va, list) or isinstance(vb, list) or not isinstance(va, (int, float)) or not isinstance(vb, (int, float)) or op not in (">", "<", ">=", "<="): return "—"
    return "%+.2f %%" % (100 * (va - vb) / abs(vb) * (1 if op in (">", ">=") else -1))
def rows_md(rows):
    T = ["| Cand | Check | Value | Op | Comparator | Margin | Result |", "|---|---|---|---|---|---|---|"]
    for r in rows: T.append("| %s | %s | %s | %s | %s %s | %s | %s |" % (r.get("cand"), r.get("check"), fv(r.get("va")), r.get("op"), r.get("b", ""), fv(r.get("vb")), margin(r), res(r) if res(r) in ("PASS", "REPORT") else "**%s**" % res(r)))
    return T
def main():
    T = ["# RAC W1m — Aelari W1 acceptance gate: evidence tables", "", "Generated by `tools/rac/w1/gen_w1m_docs.py` from the JSON in this folder. Nothing here is canon. Rule: AD-G10 (strict > / < PASS beyond 1 %, else NOT DEMONSTRATED; ≥ / ≤ MARGINAL within 1 %; '~' / '≈' ±0.010; T-SENSITIVE = changes with t). Comparators: accepted MF-M-R, SK, SG, Gorrund (W1i/W1j) and Grask (W1l); FN and VA as built in W1g (not yet accepted). Skeletal rows: CIB validation layer (W1h method) on the W1i skeletal base. Skin rows: composition-inclusive diagnostics only.", ""]
    C = {t: jl(EV, "central_%s.json" % t) for t in ("W1g", "AEL1", "NARROW", "BROAD", "LOWMUS", "HIMUS", "HIFAT", "HIBOTH", "LOW")}
    names = {"W1g": "AE as built (W1g geometry)", "AEL1": "AE candidate AEL1 (lower leg / thigh rebalanced)", "NARROW": "AE Narrow (AEL1 + diagnostic frame write)", "BROAD": "AE Broad (AEL1 + Broad Skarn frame write)",
             "LOWMUS": "AE low muscle 0 / 0.5 (AEL1 skeleton)", "HIMUS": "AE high muscle 1 / 0.5", "HIFAT": "AE higher fat 0.5 / 1", "HIBOTH": "AE high muscle + fat 1 / 1", "LOW": "AE low composition 0.25 / 0.25"}
    skel = {"W1g": "skeletal_W1g.json", "AEL1": "skeletal_AEL1.json", "NARROW": "skeletal_NARROW.json", "BROAD": "skeletal_BROAD.json"}
    T += ["## 1. Leg evenness (W1m added row: lower leg ÷ thigh ≈ MF-M-R ±0.010, the arm row's convention; AE L58, L167)", "", "| Body | AE | MF-M-R | FN | VA | SG | SK | Result |", "|---|---|---|---|---|---|---|---|"]
    for t, c in C.items():
        e = c["leg_evenness"]; T.append("| %s | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f | %s |" % (names[t], e["AE"], e["MF-M-R"], e["FN"], e["VA"], e["SG"], e["SK"], e["result"] if e["result"] == "PASS" else "**%s**" % e["result"]))
    T += ["", "## 2. Elongation distribution (shares of stature; AE as built vs AEL1 vs comparators)", "", "| Reading | AE as built | AE AEL1 | MF-M-R | FN | VA | SG | SK |", "|---|---|---|---|---|---|---|---|"]
    D0, D1 = C["W1g"]["distribution"], C["AEL1"]["distribution"]
    for k in D0["AE"]: T.append("| %s | %.4f | %.4f | %s |" % (k, D0["AE"][k], D1["AE"][k], " | ".join("%.4f" % D0[b][k] for b in ("MF-M-R", "FN", "VA", "SG", "SK"))))
    for i, t in enumerate(C):
        c = C[t]; T += ["", "## 3.%d %s" % (i + 1, names[t]), ""]
        if t in skel:
            s = jl(EV, skel[t]); T += ["### skeletal (CIB; %d rows: %d not PASS)" % (len(s), sum(res(r) not in ("PASS", "REPORT") for r in s)), ""] + rows_md(s) + [""]
        else: T += ["Skeleton = AEL1's (generator composition macros change tissue only); skeletal rows = §3.2.", ""]
        for L in ("skin", "directional"):
            T += ["### %s (%d rows: %d not PASS)%s" % (L, len(c[L]), sum(res(r) not in ("PASS", "REPORT") for r in c[L]), " — scored against REFERENCE-composition comparators, not like for like" if t in ("LOWMUS", "HIMUS", "HIFAT", "HIBOTH", "LOW") else ""), ""] + rows_md(c[L]) + [""]
    P = jl(EV, "composition.json")
    T += ["## 4. Low composition at the SAME composition (AE low vs MF-M-R-LOW / SK-LOW, 0.25 / 0.25; skin diagnostics)", ""] + rows_md(P["low_same_composition_skin"])
    T += ["", "## 5. Trunk continuity readings (W1i/W1j `gn6.cont`, `waist_rise`)", "", "| Body | hip / thorax | waist / thorax | waist / hip | d2b | waist rise |", "|---|---|---|---|---|---|"]
    for k, v in P["continuity"].items(): T.append("| %s | %.3f | %.3f | %.3f | %.4f | %.3f |" % (k, v["hip_over_thorax"], v["waist_over_thorax"], v["waist_over_hip"], v["d2b"], v["waist_rise"]))
    SEP = jl(EV, "separation.json")
    T += ["", "## 6. Separation: % difference of AE (AEL1) from each body (report only)", "", "Statures: " + ", ".join("%s %.1f cm" % (k, v) for k, v in SEP["stature"].items()) + ".", "", "| Reading | " + " | ".join(SEP["pct_AE_vs"]) + " |", "|---|" + "---|" * len(SEP["pct_AE_vs"])]
    for k in next(iter(SEP["pct_AE_vs"].values())): T.append("| %s | %s |" % (k, " | ".join("%+.1f %%" % SEP["pct_AE_vs"][b][k] for b in SEP["pct_AE_vs"])))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written")
if __name__ == "__main__": main()
