"""Generate the W1h evidence tables and ARM records from the evidence JSON (no hand-typed numbers).
Writes reviews/rac-w1h-evidence/tables.md and reviews/rac-w1h-arm/claude-rac-w1h-arm-<ID>.md (GO, GR).
Before = W1g evidence (reviews/rac-w1g-evidence); after = W1h evidence (reviews/rac-w1h-evidence)."""
import json, os, hashlib, sys
from collections import Counter
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
EV = os.path.join(R, "reviews", "rac-w1h-evidence"); ARM = os.path.join(R, "reviews", "rac-w1h-arm"); CFG = os.path.join(R, "tools", "rac", "w1", "cfg", "w1h")
EG = os.path.join(R, "reviews", "rac-w1g-evidence")
sys.path.insert(0, os.path.join(R, "tools", "rac", "w1", "w1h_drivers"))
def jl(*p): return json.load(open(os.path.join(*p)))
def rows_of(d): return d if isinstance(d, list) else d["rows"]
def f4(x): return "—" if x is None else (("[%.4f, %.4f]" % tuple(x)) if isinstance(x, list) else ("%.4f" % x if isinstance(x, (int, float)) else str(x)))
def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()[:16]
STRICT = (">", "<")
def res(x):   # same rule as gen_w1g_docs.res (AD-G10 1 % demonstration convention for rows that carry only pass / fail)
    if "result" in x: return x["result"]
    if x.get("report_only"): return "REPORT"
    if "HISTORICAL" in x.get("check", ""): return "HISTORICAL (non-vetoing)"
    if not x["pass"]: return "FAIL"
    if x["op"] in STRICT and isinstance(x["vb"], float) and abs(x["va"] - x["vb"]) / max(abs(x["vb"]), 1e-9) < 0.01: return "NOT DEMONSTRATED"
    return "PASS"
def cnt(rows): c = Counter(res(x) for x in rows); return ", ".join("%s %d" % (k, v) for k, v in sorted(c.items()))
def bold(r): return "**%s**" % r if r.split(" ")[0] in ("FAIL", "NOT", "MARGINAL", "T-SENSITIVE") else r
def tv(x, k):
    return " / ".join(f4(t[k]) for t in x["by_t"].values()) if x.get("by_t") else f4(x.get(k))
def rows_md(rows, by_t=False):
    out = ["| Cand | Check | %s | Op | Comparator%s | Result |" % ("Value t=0 / 0.5 / 1.0" if by_t else "Value", " t=0 / 0.5 / 1.0" if by_t else ""), "|---|---|---|---|---|---|"]
    for x in rows:
        v = tv(x, "va") if by_t else f4(x.get("va")); cv = tv(x, "vb") if by_t else (f4(x.get("vb")) if x.get("vb") is not None else "")
        out.append("| %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], v, x["op"], x.get("b", ""), cv, bold(res(x))))
    return out
def key(x): return (x["cand"], x["check"], x.get("b"))
def mid(x, k="va"):
    if x.get("by_t"): return list(x["by_t"].values())[1][k]
    return x.get(k)

def main():
    os.makedirs(ARM, exist_ok=True)
    import gn5
    SK = rows_of(jl(EV, "skeletal", "skeletal_checks.json")); SKg = rows_of(jl(EG, "skeletal", "skeletal_checks.json"))
    AL = jl(EV, "skeletal", "alpc_w1h.json"); ALg = jl(EG, "skeletal", "alpc_w1g.json"); A8 = jl(EV, "skeletal", "alpc8.json")
    CC = jl(EV, "skeletal", "contour_clearance.json"); CCg = jl(EG, "skeletal", "contour_clearance.json")
    DC = rows_of(jl(EV, "directional_checks.json")); DCg = rows_of(jl(EG, "directional_checks.json"))
    WC = rows_of(jl(EV, "w1e_checks.json")); WCg = rows_of(jl(EG, "w1e_checks.json"))
    OC = jl(EV, "ocular", "ocular_w1h.json"); EC = jl(EV, "ears", "ear_checks.json"); AEB = jl(EV, "ae_vertical_budget.json")
    GOc = jl(CFG, "GO.json"); GRc = jl(CFG, "GR.json"); SB = {k: v["stature"] for k, v in jl(EV, "go-variants", "stress_builds.json").items()}
    SEN = jl(EV, "solver", "sensitivity.json") if os.path.exists(os.path.join(EV, "solver", "sensitivity.json")) else None
    T = ["# RAC W1h — evidence tables", "", "Generated by `tools/rac/w1/gen_w1h_docs.py` from the JSON in this folder (before = `reviews/rac-w1g-evidence`). Nothing here is canon. Skeletal rows = CIB validation layer (AD-W1H-1: upper-bound proxy); skin rows = composition-inclusive diagnostics.", ""]
    # 1 method
    T += ["## 1. Method changes in W1h (validation-method parameters, not anatomy; AD-W1H-1)", "",
          "| Change | Where | Why |", "|---|---|---|",
          "| Trunk stations read on exact plane sections of the trunk faces (was: vertex slabs ±1 cm) | `bony_envelope.SECTION` | Vertex slabs miss whole vertex rings where the mesh is stretched (tall / broad bodies); one grid body could then set the infimum alone |",
          "| S2 (thorax maximum) and S4 (waist) read at the reference body's levels in every grid body (was: re-searched per body) | `bony_envelope.FIXED_LEVELS` | A per-body re-search jumped to a different anatomical level in some grid bodies (GOR-BODY-03 W1g crest / shaft diagnosis) |",
          "| No clamp to the minimum-composition (LEAN) body when levels are fixed | `skeletal_proxy.py` (`no_lean_clamp`) | With fixed levels the minimum-composition body is a grid member read at the same levels |",
          "| Trunk sculpt kept out of the thigh (`confine_legs`) | `skeleton_envelope.trunk_sculpt` | Keeps a soft-tissue construction from moving the thigh vertices that the shaft station (20 % down the femur) reads. Related W1g frame diagnosis (`skeletal/frame_shaft_diagnostic_W1g.log`): the frame's pelvis-breadth write lowers the shaft section through pelvis skin weights (GOR-BODY-04 shaft 18.65 cm, 18.91 cm without the pelvis write; GOR-BODY-12 18.50 / 18.90 cm) |",
          "| Skin flank flare = (S5 − line S4→hip-level breadth) / H | `profile_bump.flank_flare` | Measures the isolated crest bulge named in AD-W1H-2 |",
          "| Arm-tube test: trunk vertices inside closed sections of the upper-arm tube | `arm_clearance.arm_tube_test` | Second interpenetration test for AD-W1H-6, independent of trunk-section closure |", "",
          "The W1g Gorrund parameters read with the W1h method (with `confine_legs`) fail several rows (`solver/p0.log`), so the W1h results below come from both the method change and the re-solve; they are not separable by one switch.", ""]
    # 2 construction values
    xg = GOc["w1g"]["solver_x"]; xh = GOc["w1h"]["solver_x"]; bd = GOc["w1h"]["solver_bounds"]
    T += ["## 2. Gorrund construction values (R-14; all CONSTRAINED, AD-W1H-12)", "", "| Parameter | W1g | W1h | W1h bound [lo, hi] | distance to nearest bound (relative) |", "|---|---|---|---|---|"]
    for n in gn5.NAMES:
        g = xg.get(n, {"kb60": GOc["w1g"]["kb_upper_nodes_0.6_0.8"][0], "kb80": GOc["w1g"]["kb_upper_nodes_0.6_0.8"][1]}.get(n)); h = xh[n]; lo, hi = bd[n]
        dist = min(abs(h - lo), abs(hi - h)) / max(abs(h), 1e-9)
        d_txt = ("**outside the bound (post-solve step T9)**" if (h > hi + 1e-9 or h < lo - 1e-9) else ("**%.2f %%**" if dist < 0.005 else "%.2f %%") % (100 * dist))
        T.append("| %s | %s | %.4f | [%.2f, %.2f] | %s |" % (n, f4(g), h, lo, hi, d_txt))
    T += ["", "Names: pelvisX/Y/Z = pelvis bone scale (lateral / length / depth); thigh = femur length and breadth; clavY = clavicle length; s03Y = upper-thorax (spine_03) length; Aka = anterior trunk depth amplitude; kp<r> / kb<r> = posterior depth / breadth sculpt factor at trunk height fraction r (0 = hip, 0.18 crest, 0.31 waist, 0.44 lower thorax, 0.6 / 0.8 upper thorax).", "",
          "GR: W1g pelvis %s → W1h pelvis %s; clavicle %s unchanged. %s" % (GRc["w1g"]["pelvis"], GRc["w1h"]["pelvis"], GRc["w1h"]["LR:clavicle"], GRc["w1h"]["note"]), ""]
    # 3 skeletal checks
    T += ["## 3. Skeletal / bony-landmark validation, reference bodies (`skeletal/skeletal_checks.json`; %d rows: %s)" % (len(SK), cnt(SK)), "",
          "Rule (AD-G10): strict > / < must hold by ≥ 1 % (else NOT DEMONSTRATED); ≥ / ≤ missing by < 1 % = MARGINAL; '~' = ±0.010; T-SENSITIVE = result changes with t.", ""] + rows_md(SK, by_t=True)
    # 4 before/after
    F = {key(x): x for x in SKg}
    T += ["", "## 4. Before / after (W1g → W1h) for every W1g residual and every changed result", "", "### Skeletal rows, reference bodies", "", "| Cand | Check | W1g value (t=0.5) | W1g result | W1h value (t=0.5) | W1h comparator | W1h result |", "|---|---|---|---|---|---|---|"]
    for x in SK:
        y = F.get(key(x))
        if y and (res(y) != "PASS" or res(x) != "PASS") and res(y) not in ("REPORT", "NOT RUN"):
            T.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], f4(mid(y)), bold(res(y)), f4(mid(x)), x["op"], f4(mid(x, "vb")), bold(res(x))))
    if T[-1].startswith("|---"): T.append("| — | No reference-body skeletal row is non-PASS in W1g or in W1h (values for every row: §3) | | | | | |")
    T += ["", "### ALPC stress rows (non-PASS in W1g or W1h)", "", "| Test | Check | W1g t=0 / 0.5 / 1.0 | W1g result | W1h t=0 / 0.5 / 1.0 | W1h comparator t=0 / 0.5 / 1.0 | W1h result |", "|---|---|---|---|---|---|---|"]
    for k, rows in AL["rows"].items():
        G = {r["check"]: r for r in ALg["rows"].get(k, [])}
        for r in rows:
            y = G.get(r["check"])
            if res(r) != "PASS" or (y and res(y) != "PASS"):
                T.append("| %s | %s | %s | %s | %s | %s | %s |" % (k, r["check"], tv(y, "va") if y else "— (not run in W1g)", bold(res(y)) if y else "—", tv(r, "va"), tv(r, "vb"), bold(res(r))))
        for c, y in G.items():
            if c not in {r["check"] for r in rows} and res(y) != "PASS": T.append("| %s | %s | %s | %s | — | — | row not produced in W1h |" % (k, c, tv(y, "va"), bold(res(y))))
    # 5 ALPC
    T += ["", "## 5. Gorrund ALPC tests (`skeletal/alpc_w1h.json`)", "", "| Test | W1g | W1h |", "|---|---|---|"]
    for k, rows in AL["rows"].items(): T.append("| %s | %s | %s |" % (k, cnt(ALg["rows"][k]) if k in ALg["rows"] else "not run", cnt(rows)))
    for k, rows in AL["rows"].items():
        bad = [r for r in rows if res(r) != "PASS"]
        if bad: T += ["", "### %s — non-PASS rows" % k, ""] + rows_md(bad, by_t="skin" not in k)
    T += ["", "### ALPC-8 (`skeletal/alpc8.json`)", "", "| Reading | GO | DU | GO > DU |", "|---|---|---|---|"]
    for k, v in A8["checks"].items():
        if isinstance(v, list): T.append("| %s | %s | %s | %s (GO/DU − 1 = %+.1f %%) |" % (k, f4(v[0]), f4(v[1]), "yes" if v[2] else "**no**", 100 * (v[0] / v[1] - 1)))
    T += ["", "Silhouette IoU: front %.3f, side %.3f; identical: %s." % (A8["checks"]["silhouette_IoU"]["front"], A8["checks"]["silhouette_IoU"]["side"], A8["checks"]["identical_silhouettes"]), ""]
    # 6 GO bodies table
    T += ["## 6. Gorrund reference / frame / stature bodies", "", "| Body | Role | Stature R-6 (cm) | Skeletal ALPC result (ALPC-0…4; frames ALPC-5; GOR-BODY-16 = ALPC-6 skin half) | Solver target? | skin flank flare | arm-tube: trunk vertices inside (l / r) | section clearance in band (cm) |", "|---|---|---|---|---|---|---|---|"]
    meas = jl(EV, "candidates", "GO_meas.json")
    roles = [("GO W1h", "reference", meas["stature_r6"], "ALPC-6 skeletal half (reference GO skeleton = GOR-BODY-16 skeleton)", "yes (gn5 H1–H8; final step T9 checked on this body only)"), ("GOR-BODY-02 (208)", "stature 208", SB["GOR-BODY-02"], "Stature stress GOR-BODY-02: ALPC-0...4", "yes in gn5 H8; not in step T9"),
             ("GO 215", "stature intermediate", SB["GO-H215"], "Stature stress GO-H215: ALPC-0...4", "no"), ("GO 222", "stature intermediate", SB["GO-H222"], "Stature stress GO-H222: ALPC-0...4", "no"),
             ("GOR-BODY-03 (251)", "maximum generator-reachable stature", SB["GOR-BODY-03"], "Stature stress GOR-BODY-03: ALPC-0...4", "yes in gn5 H1–H8 (lower-thorax-depth row excluded); not in step T9"),
             ("GOR-BODY-04", "frame (narrow)", SB["GOR-BODY-04"], "ALPC-5 GOR-BODY-04", "no"), ("GOR-BODY-12", "frame", SB["GOR-BODY-12"], "ALPC-5 GOR-BODY-12", "no"), ("GOR-BODY-14", "frame (depth vs MF)", SB["GOR-BODY-14"], "ALPC-5 GOR-BODY-14", "no"),
             ("GOR-BODY-05 (Broad)", "broad-frame render stress", SB["GOR-BODY-05"], None, "no"), ("GOR-BODY-16", "composition 0.25 / 0.25", None, "ALPC-6 skin half: GOR-BODY-16 skin vs MF and SK at the same low composition", "no")]
    for b, role, H, k, tgt in roles:
        a = CC["arm_tube"][b]; c = CC["arm_clearance"][b]
        T.append("| %s | %s | %s | %s | %s | %.4f | %d / %d | %.2f |" % (b, role, f4(H), cnt(AL["rows"][k]) if k else "not an ALPC body (render review only)", tgt, CC["contour"][b]["flank_flare"], a["l"]["trunk_verts_inside_arm_tube"], a["r"]["trunk_verts_inside_arm_tube"], c["signed_clearance_both_sides_cm"]))
    T += ["", "GOR-BODY-16 flank flare 0.0000 is degenerate: on that skin the waist search lands on the crest level (S4 = S5), so the flare line has no span.", "", "Equal-height Broad Skarn comparators: SKB215 %.2f cm, SKB222 %.2f cm (W1g SKB208 / SKB229 reused)." % (SB["SKB215"], SB["SKB222"]), ""]
    # 7 contour/clearance
    T += ["## 7. Contour, flank flare and arm clearance (`skeletal/contour_clearance.json`)", "",
          "Two interpenetration tests. (a) Trunk-section test: each upper-arm vertex against the trunk's closed cross-section at its height (decidable only where the section is closed; band below). (b) Arm-tube test: trunk vertices inside the closed sections of the upper-arm tube, from the shoulder joint down the humerus (tested range below). Neither reaches the top of the axilla.", "",
          "| Body | chest-lead | buttock-lead | flank flare | (a) vertices inside / testable | (a) band (cm) | (a) clearance (cm) | (b) inside l / r | (b) tested range below shoulder (cm) | min vertex gap (cm) |", "|---|---|---|---|---|---|---|---|---|---|"]
    for k in CC["contour"]:
        a = CC["arm_clearance"][k]; t = CC["arm_tube"][k]; c = CC["contour"][k]
        T.append("| %s | %.4f | %.4f | %.4f | %d / %d | %.1f–%.1f | %.3f | %d / %d | %.1f–%.1f | %.2f |" % (k, c["chest_lead"], c["buttock_lead"], c["flank_flare"], a["verts_inside_trunk_section"], a["n_testable_closed_section"], a["testable_band_cm"][0], a["testable_band_cm"][1], a["signed_clearance_both_sides_cm"],
                 t["l"]["trunk_verts_inside_arm_tube"], t["r"]["trunk_verts_inside_arm_tube"], t["l"]["tested_range_cm_below_shoulder"][0], t["l"]["tested_range_cm_below_shoulder"][1], a["min_arm_trunk_gap_cm"]))
    # 8 AE budget
    cu = AEB["current"]
    T += ["", "## 8. Aelari vertical budget (AD-W1H-5; `ae_vertical_budget.json`)", "", AEB["note"], "",
          "Current shares (fraction of stature): AE leg %.4f, AE torso %.4f, AE neck %.4f, remaining %.4f; VA leg %.4f, MF leg %.4f, FN torso %.4f, MF neck %.4f." % (cu["AE_leg"], cu["AE_torso"], cu["AE_neck"], cu["remaining_share"], cu["VA_leg"], cu["MF_leg"], cu["FN_torso"], cu["MF_neck"]), "",
          "Current margin over each 1 %% threshold: AE leg / VA %+.3f %%, VA leg / MF %+.3f %%, AE torso / FN %+.3f %%, AE neck / MF %+.3f %%." % (100 * (cu["AE_leg"] / cu["VA_leg"] / 1.01 - 1), 100 * (cu["VA_leg"] / cu["MF_leg"] / 1.01 - 1), 100 * (cu["AE_torso"] / cu["FN_torso"] / 1.01 - 1), 100 * (cu["AE_neck"] / cu["MF_neck"] / 1.01 - 1)), "",
          "| Uniform extra margin over every 1 % threshold | AE leg min | VA leg min | AE torso min | AE neck min | max remaining share | change vs current remaining share |", "|---|---|---|---|---|---|---|"]
    for r in AEB["rows"]:
        T.append("| %.2f %% | %.4f | %.4f | %.4f | %.4f | %.4f | %+.1f %% |" % (100 * r["margin_over_each_1pct_threshold"], r["AE_leg_min"], r["VA_leg_min"], r["AE_torso_min"], r["AE_neck_min"], r["max_remaining_share_head_and_neck_base"], 100 * r["change_vs_current_remaining_share"]))
    if "max_uniform_margin_at_current_remaining_share" in AEB: T += ["", "Largest uniform margin at the current remaining share: %.3f %%." % (100 * AEB["max_uniform_margin_at_current_remaining_share"])]
    # 9 sensitivity
    if SEN:
        b = SEN["base"]
        T += ["", "## 9. R-14 sensitivity (AD-W1H-12; `solver/sensitivity.json`)", "",
              "Each Gorrund solver parameter perturbed one at a time: factor × (1 ± %.0f %%), Aka ± 0.05. The reference body and GOR-BODY-03 are rebuilt and every GO skeletal row is re-checked with the ordinary AD-G10 rule. Base: not-PASS rows reference %d, 251 cm %d; skin TB vs SK %+.2f %% (directional-check reading; %+.2f %% on the plane-section reading that gn5 H1–H8 used before the correction); flank flare %.4f; arm clearance %.2f cm; stature %.2f cm." % (100 * SEN["step"], len(b["not_pass_ref"]), len(b["not_pass_251"]), 100 * b["skin_TB_vs_SK_measure_layer"], 100 * b["skin_TB_vs_SK"], b["flank_flare"], b["arm_clearance_cm"], b["stature"]), "",
              "| Perturbation | Value | Reference rows not PASS | 251 cm rows not PASS | skin TB vs SK (directional reading) | flank flare | arm clearance (cm) |", "|---|---|---|---|---|---|---|"]
        for k, v in SEN["perturb"].items():
            T.append("| %s | %.4f | %s | %s | %+.2f %% | %.4f | %.2f |" % (k, v["value"], "; ".join(v["not_pass_ref"]) or "0", "; ".join(v["not_pass_251"]) or "0", 100 * v["skin_TB_vs_SK_measure_layer"], v["flank_flare"], v["arm_clearance_cm"]))
    # 10 directional, skin, ocular, ears
    Dg = {key(x): x for x in DCg}
    T += ["", "## 10. Directional checks (`directional_checks.json`; %d rows: %s)" % (len(DC), cnt(DC)), "", "| Cand | Check | W1g value | W1g result | W1h value | Comparator | W1h result |", "|---|---|---|---|---|---|---|"]
    for x in DC:
        y = Dg.get(key(x))
        if res(x) != "PASS" or (y and res(y) != "PASS") or (x["cand"] == "GO" and "thoracic breadth" in x["check"]):
            T.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], f4(y["va"]) if y else "—", bold(res(y)) if y else "—", f4(x["va"]), x["op"], f4(x["vb"]), bold(res(x))))
    Wg = {key(x): x for x in WCg}
    T += ["", "## 11. Skin diagnostics (`w1e_checks.json`; composition-inclusive, never a pass condition; %d rows: %s)" % (len(WC), cnt(WC)), "", "| Cand | Check | W1g value | W1g result | W1h value | Comparator | W1h result |", "|---|---|---|---|---|---|---|"]
    for x in WC:
        y = Wg.get(key(x))
        if res(x) in ("PASS", "NOT RUN") and (y is None or res(y) in ("PASS", "NOT RUN")): continue
        T.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], f4(y["va"]) if y else "—", bold(res(y)) if y else "—", f4(x["va"]), x["op"], f4(x["vb"]) if isinstance(x.get("vb"), float) else x.get("vb"), bold(res(x))))
    T += ["", "## 12. Ocular (`ocular/ocular_w1h.json`; geometry unchanged except GO / GR bodies)", "", "| Body | Ring (cm) | Ring-globe clr (cm) | Globe (cm) | globe/HH vs MF | Fits |", "|---|---|---|---|---|---|"]
    for i, r in OC["bodies"].items():
        T.append("| %s | %.3f × %.3f | %.2f | %.3f | %.3f | %s |" % (i, r["ring_breadth_cm"], r["ring_height_cm"], r["ring_globe_clearance_cm"], r["globe_cm"], r["vs_MF"]["globe_over_HH"], r["fits"]))
    er = rows_of(EC) if not isinstance(EC, dict) or "rows" in EC else EC
    T += ["", "## 13. Ears (`ears/ear_checks.json`; v2 families unchanged, re-attached to the W1h set): %d rows, %s" % (len(er), cnt(er)), ""]
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n")
    for i, desc in (("GO", "Gorrund central — W1h re-solve (lower-trunk continuity, thoracic breadth, frame / stature)"), ("GR", "Grask central — pelvis X re-tuned under the W1h station method")):
        m = jl(EV, "candidates", i + "_meas.json"); geo = os.path.join(EV, "geometry", i + "_r6.npz")
        L = ["# RAC W1h ARM record — %s (%s)" % (i, desc), "", "Generated by `tools/rac/w1/gen_w1h_docs.py`. Status: see `reviews/claude-rac-w1h-author-acceptance-gate.md`. Nothing here is accepted.", "",
             "- Geometry: `%s` (sha256 %s); skeleton: `reviews/rac-w1h-evidence/skeleton/%s-LEAN_r6.npz`; config `tools/rac/w1/cfg/w1h/%s.json`" % (os.path.relpath(geo, R), sha(geo), i, i),
             "- Stature (R-6) %.2f cm; HH %.2f cm" % (m["stature_r6"], m["combined"]["cranio"]["HH"]),
             "- Bony stations: CIB with W1h fixed-level plane sections (`reviews/rac-w1h-evidence/cib/%s_cib.json`)" % i, "",
             "## Skeletal checks", ""] + rows_md([x for x in SK if x["cand"] == i and res(x) != "NOT RUN"], by_t=True)
        L += ["", "## Directional checks", ""] + rows_md([x for x in DC if x["cand"] == i])
        L += ["", "## Skin diagnostics (composition-inclusive)", ""] + rows_md([x for x in WC if x["cand"] == i and res(x) != "NOT RUN"])
        open(os.path.join(ARM, "claude-rac-w1h-arm-%s.md" % i), "w").write("\n".join(L) + "\n")
    print("tables + ARM records written")

if __name__ == "__main__":
    main()
