"""Generate the W1i evidence tables and the GO ARM record from the evidence JSON (no hand-typed numbers).
Writes reviews/rac-w1i-evidence/tables.md and reviews/rac-w1i-arm/claude-rac-w1i-arm-GO.md.
Before = W1h evidence (reviews/rac-w1h-evidence); after = W1i evidence (reviews/rac-w1i-evidence)."""
import json, os, hashlib, sys
from collections import Counter
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
EV = os.path.join(R, "reviews", "rac-w1i-evidence"); ARM = os.path.join(R, "reviews", "rac-w1i-arm"); CFG = os.path.join(R, "tools", "rac", "w1", "cfg", "w1i")
EH = os.path.join(R, "reviews", "rac-w1h-evidence")
sys.path.insert(0, os.path.join(R, "tools", "rac", "w1", "w1i_drivers"))
def jl(*p): return json.load(open(os.path.join(*p)))
def rows_of(d): return d if isinstance(d, list) else d["rows"]
def f4(x): return "—" if x is None else (("[%.4f, %.4f]" % tuple(x)) if isinstance(x, list) else ("%.4f" % x if isinstance(x, (int, float)) else str(x)))
def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()[:16]
STRICT = (">", "<")
def res(x):   # AD-G10 1 % demonstration convention for rows that carry only pass / fail (same as gen_w1g_docs / gen_w1h_docs)
    if "result" in x: return x["result"]
    if x.get("report_only"): return "REPORT"
    if "HISTORICAL" in x.get("check", ""): return "HISTORICAL (non-vetoing)"
    if not x["pass"]: return "FAIL"
    if x["op"] in STRICT and isinstance(x["vb"], float) and abs(x["va"] - x["vb"]) / max(abs(x["vb"]), 1e-9) < 0.01: return "NOT DEMONSTRATED"
    return "PASS"
def cnt(rows): c = Counter(res(x) for x in rows); return ", ".join("%s %d" % (k, v) for k, v in sorted(c.items())) or "—"
def bold(r): return "**%s**" % r if r.split(" ")[0] in ("FAIL", "NOT", "MARGINAL", "T-SENSITIVE") else r
def tv(x, k): return " / ".join(f4(t[k]) for t in x["by_t"].values()) if x.get("by_t") else f4(x.get(k))
def key(x): return (x["cand"], x["check"], x.get("b"))
def mid(x, k="va"): return list(x["by_t"].values())[1][k] if x.get("by_t") else x.get(k)
def margin(x):
    """worst-t margin over the PASS threshold of the 1 % convention (relative): strict -> a/b-1-0.01; >= -> a/b-1; '~' -> (0.010-|a-b|)/b"""
    if "ALPC-0" in x.get("check", ""): return None      # a 1 / 0 shape flag has no margin
    ts = list(x["by_t"].values()) if x.get("by_t") else [x]; out = []
    for t in ts:
        a, b = t.get("va"), t.get("vb")
        if not isinstance(a, (int, float)) or not isinstance(b, (int, float)) or b == 0: return None
        op = x["op"]
        if op == ">": out.append(a / b - 1 - 0.01)
        elif op == "<": out.append(1 - a / b - 0.01)
        elif op == ">=": out.append(a / b - 1)
        elif op == "<=": out.append(1 - a / b)
        elif op == "~": out.append((0.010 - abs(a - b)) / abs(b))
        else: return None
    return min(out)
def pm(v): return "—" if v is None else "%+.2f %%" % (100 * v)
def rows_md(rows, by_t=False, with_margin=False):
    out = ["| Cand | Check | %s | Op | Comparator%s | Result |%s" % ("Value t=0 / 0.5 / 1.0" if by_t else "Value", " t=0 / 0.5 / 1.0" if by_t else "", " Margin over the pass threshold (worst t) |" if with_margin else ""),
           "|---|---|---|---|---|---|" + ("---|" if with_margin else "")]
    for x in rows:
        v = tv(x, "va") if by_t else f4(x.get("va")); cv = tv(x, "vb") if by_t else (f4(x.get("vb")) if x.get("vb") is not None else "")
        out.append("| %s | %s | %s | %s | %s %s | %s |%s" % (x["cand"], x["check"], v, x["op"], x.get("b", ""), cv, bold(res(x)), (" %s |" % pm(margin(x))) if with_margin else ""))
    return out

def main():
    os.makedirs(ARM, exist_ok=True)
    import gn6
    SK = rows_of(jl(EV, "skeletal", "skeletal_checks.json")); SKh = rows_of(jl(EH, "skeletal", "skeletal_checks.json"))
    AL = jl(EV, "skeletal", "alpc_w1i.json"); ALh = jl(EH, "skeletal", "alpc_w1h.json"); A8 = jl(EV, "skeletal", "alpc8.json"); A8h = jl(EH, "skeletal", "alpc8.json")
    CC = jl(EV, "skeletal", "contour_clearance.json"); CCh = jl(EH, "skeletal", "contour_clearance.json")
    DC = rows_of(jl(EV, "directional_checks.json")); DCh = rows_of(jl(EH, "directional_checks.json"))
    WC = rows_of(jl(EV, "w1e_checks.json")); WCh = rows_of(jl(EH, "w1e_checks.json"))
    OC = jl(EV, "ocular", "ocular_w1i.json"); EC = jl(EV, "ears", "ear_checks.json")
    GOc = jl(CFG, "GO.json"); SB = {k: v["stature"] for k, v in jl(EV, "go-variants", "stress_builds.json").items()}
    meas0 = jl(EV, "candidates", "GO_meas.json")
    SEN = jl(EV, "solver", "sensitivity_w1i.json") if os.path.exists(os.path.join(EV, "solver", "sensitivity_w1i.json")) else None
    LOGS = sorted(f for f in os.listdir(os.path.join(EV, "solver")) if f.startswith("gn6_") and f.endswith(".log"))
    T = ["# RAC W1i — evidence tables", "", "Generated by `tools/rac/w1/gen_w1i_docs.py` from the JSON in this folder (before = `reviews/rac-w1h-evidence`). Nothing here is canon. Skeletal rows = CIB validation layer (upper-bound proxy, AD-W1H-1); skin rows = composition-inclusive diagnostics; continuity readings and solver margins are validation-method readings, not anatomy.", ""]
    # 1 solver
    L = CC["continuity_limits"]
    T += ["## 1. W1i solve (`tools/rac/w1/w1i_drivers/gn6.py`; logs %s)" % ", ".join("`solver/%s`" % l for l in LOGS), "",
          "Changes from W1h: (a) the reference AND all four stature bodies (208 / 215 / 222 / 251 cm) and every cross-height ALPC-7 pair are in the loop; (b) robustness margins larger than the 1 %% convention: strict > / < by %.1f %%, ≥ / ≤ by %.1f %%, '~' within %.3f; arm clearance ≥ %.1f cm; skin thoracic breadth > SK by %.1f %% on the directional reading; (c) the trunk-sculpt profile is a C1 monotone cubic (PCHIP) between nodes, so no slope break at a node; posterior depth uses 2 values (lower r 0.18 / 0.31, upper r 0.44 / 0.6) instead of 4; (d) continuity constraints with limits taken from the accepted references (§7); (e) a low-composition waist constraint (§7); (f) a barrier pushes values away from the outer 3 %% of each bound range (a penalty, not a hard limit: Aka, kb44, kb60 and kb80 end inside that zone; §2). The femur-robusticity bound was raised from 1.25 to 1.40 in run I6, so femur 1.386 is inside the W1i bound but outside the W1h one; kb80 is back inside its W1h bound. The final point is the I9 solver point plus a manual centering step C2 (`solver/i9point/center2.py`; 8 of 16 values moved)." % (100 * gn6.M_STRICT, 100 * gn6.M_GE, gn6.M_TILDE, gn6.CLR, 100 * gn6.M_STRICT), ""]
    # 2 values
    xh = GOc["w1h"]["solver_x"]; xi = GOc["w1i"]["solver_x"]; bd = GOc["w1i"]["solver_bounds"]
    hmap = dict(xh); hmap["kpL"] = "%.4f / %.4f" % (xh["kp18"], xh["kp31"]); hmap["kpU"] = "%.4f / %.4f" % (xh["kp44"], xh["kp60"])
    T += ["## 2. Gorrund construction values (R-14; all CONSTRAINED)", "", "| Parameter | W1h | W1i | W1i bound [lo, hi] | distance to nearest bound (relative) |", "|---|---|---|---|---|"]
    for n in gn6.NAMES:
        h = xi[n]; lo, hi = bd[n]; dist = min(abs(h - lo), abs(hi - h)) / max(abs(h), 1e-9)
        d_txt = "**outside the bound**" if (h > hi + 1e-9 or h < lo - 1e-9) else (("**%.2f %%**" if dist < 0.01 else "%.2f %%") % (100 * dist))
        T.append("| %s | %s | %.4f | [%.2f, %.2f] | %s |" % (n, f4(hmap.get(n)), h, lo, hi, d_txt))
    T += ["", "Names: pelvisX/Y/Z = pelvis bone scale (lateral / length / depth); thigh = femur robusticity (breadth and depth; length unchanged); clavY = clavicle length; s03Y = upper-thorax (spine_03) length; Aka = anterior trunk depth amplitude; kpL / kpU = posterior depth sculpt at r 0.18 + 0.31 / 0.44 + 0.6 (W1h had 4 separate values, shown as pairs); kb<r> = breadth sculpt at trunk height fraction r (0 = hip joints, 0.18 crest, 0.31 waist, 0.44 lower thorax, 0.6 / 0.8 upper thorax).", ""]
    # 3 skeletal checks
    T += ["## 3. Skeletal / bony-landmark validation, reference bodies (`skeletal/skeletal_checks.json`; %d rows: %s)" % (len(SK), cnt(SK)), "",
          "Rule (AD-G10): strict > / < must hold by ≥ 1 % (else NOT DEMONSTRATED); ≥ / ≤ missing by < 1 % = MARGINAL; '~' = ±0.010; T-SENSITIVE = result changes with t. The last column is the worst-t margin over the pass threshold (robustness reading).", ""] + rows_md(SK, by_t=True, with_margin=True)
    # 4 before / after
    Fh = {key(x): x for x in SKh}
    T += ["", "## 4. Before / after (W1h → W1i)", "", "### Gorrund reference skeletal rows: worst-t margin over the pass threshold", "", "| Check | W1h result | W1h margin | W1i result | W1i margin |", "|---|---|---|---|---|"]
    for x in SK:
        if x["cand"] != "GO" and x.get("b") != "GO": continue
        y = Fh.get(key(x))
        if res(x) in ("NOT RUN", "REPORT"): continue
        T.append("| %s%s | %s | %s | %s | %s |" % (x["check"], (" (" + x["cand"] + ")") if x["cand"] != "GO" else "", bold(res(y)) if y else "—", pm(margin(y)) if y else "—", bold(res(x)), pm(margin(x))))
    T += ["", "### Every ALPC stress row non-PASS in W1h or W1i", "", "| Test | Check | W1h t=0 / 0.5 / 1.0 | W1h result | W1i t=0 / 0.5 / 1.0 | W1i comparator t=0 / 0.5 / 1.0 | W1i result |", "|---|---|---|---|---|---|---|"]
    n0 = len(T)
    for k, rows in AL["rows"].items():
        Gh = {r["check"]: r for r in ALh["rows"].get(k, [])}
        for r in rows:
            y = Gh.get(r["check"])
            if res(r) != "PASS" or (y and res(y) != "PASS"):
                T.append("| %s | %s | %s | %s | %s | %s | %s |" % (k, r["check"], tv(y, "va") if y else "—", bold(res(y)) if y else "—", tv(r, "va"), tv(r, "vb"), bold(res(r))))
    if len(T) == n0: T.append("| — | none | | | | | |")
    # 5 ALPC
    T += ["", "## 5. Gorrund ALPC tests (`skeletal/alpc_w1i.json`)", "", "| Test | W1h | W1i |", "|---|---|---|"]
    for k, rows in AL["rows"].items(): T.append("| %s | %s | %s |" % (k, cnt(ALh["rows"][k]) if k in ALh["rows"] else "not run", cnt(rows)))
    T += ["", "### ALPC-7 matrix (GO height × Broad Skarn height; worst row margin over the pass threshold, worst t)", "", "| GO \\ Broad Skarn | 208 | 215 | 222 | 229 |", "|---|---|---|---|---|"]
    for hg in (208, 215, 222, 229):
        cells = []
        for hs in (208, 215, 222, 229):
            k = "ALPC-7 GO %d cm vs Broad Skarn %d cm" % (hg, hs)
            if k not in AL["rows"]: cells.append("—"); continue
            rows = AL["rows"][k]; ms = [margin(r) for r in rows if margin(r) is not None]
            cells.append("%s; %s" % (cnt(rows), pm(min(ms)) if ms else "—"))
        T.append("| %d | %s |" % (hg, " | ".join(cells)))
    T += ["", "Row labels follow the donor heights: GO '208' = GOR-BODY-02 (%.1f cm), '215' = %.1f cm, '222' = %.1f cm, '229' = the reference (%.1f cm). The true 208 cm body is in §6." % (SB["GOR-BODY-02"], SB["GO-H215"], SB["GO-H222"], meas0["stature_r6"])]
    for k, rows in AL["rows"].items():
        bad = [r for r in rows if res(r) != "PASS"]
        if bad: T += ["", "### %s — non-PASS rows" % k, ""] + rows_md(bad, by_t="skin" not in k)
    for tag in ("W1h", "W1i"):
        fp = os.path.join(EV, "skeletal", "alpc6_attrib_%s.json" % tag)
        if not os.path.exists(fp): continue
        A6 = jl(fp)
        T += ["", "### ALPC-6 skin half, method attribution, GOR-BODY-16 %s (`skeletal/alpc6_attrib_%s.json`; `w1i_drivers/alpc6_attrib.py`)" % (tag, tag), "",
              "Same rows, same three bodies (GOR-BODY-16, MF-M-R and SK at muscle 0.25 / weight 0.25). Row 1 = official measurement layer (±1 cm vertex slabs); row 2 = the same stations re-read on exact plane sections at the same levels and masks (`w1i_drivers/restation.py`; the W1h CIB section method). Slab vs section breadths at the waist levels: `skeletal/waist_slab_vs_section.log`.", "",
              "| Reading | Result | Non-PASS rows |", "|---|---|---|"]
        for k, rows in A6["rows"].items():
            T.append("| %s | %s | %s |" % (k, cnt(rows), "; ".join("%s %s (%.4f %s %.4f)" % (res(r), r["check"][:60], r["va"], r["op"], r["vb"]) for r in rows if res(r) != "PASS") or "—"))
    T += ["", "### ALPC-8 (`skeletal/alpc8.json`)", "", "| Reading | GO W1h | GO W1i | DU | GO W1i > DU |", "|---|---|---|---|---|"]
    for k, v in A8["checks"].items():
        if isinstance(v, list):
            vh = A8h["checks"].get(k); T.append("| %s | %s | %s | %s | %s (GO/DU − 1 = %+.1f %%) |" % (k, f4(vh[0]) if vh else "—", f4(v[0]), f4(v[1]), "yes" if v[2] else "**no**", 100 * (v[0] / v[1] - 1)))
    T += ["", "Silhouette IoU: front %.3f, side %.3f (W1h %.3f / %.3f); identical: %s." % (A8["checks"]["silhouette_IoU"]["front"], A8["checks"]["silhouette_IoU"]["side"], A8h["checks"]["silhouette_IoU"]["front"], A8h["checks"]["silhouette_IoU"]["side"], A8["checks"]["identical_silhouettes"]), ""]
    # 6 bodies
    T += ["## 6. Gorrund reference / frame / stature / composition bodies", "", "| Body | Role | Stature R-6 (cm) | ALPC result (W1i; skeletal, except GOR-BODY-16 = ALPC-6 skin half) | W1h | In the W1i solve? | skin flank flare | arm-tube inside (l / r) | section clearance (cm) |", "|---|---|---|---|---|---|---|---|---|"]
    meas = jl(EV, "candidates", "GO_meas.json")
    roles = [("GO W1i", "GO W1h", "reference", meas["stature_r6"], "ALPC-6 skeletal half (reference GO skeleton = GOR-BODY-16 skeleton)", "yes (gn6 I1–I9; final centering step C2 not solved, re-checked)"),
             ("GOR-BODY-02 (208)", "GOR-BODY-02 (208)", "minimum stature", SB["GOR-BODY-02"], "Stature stress GOR-BODY-02: ALPC-0...4", "yes (I1–I9); C2 re-checked"),
             ("GO 215", "GO 215", "intermediate stature", SB["GO-H215"], "Stature stress GO-H215: ALPC-0...4", "yes (I1–I9); C2 re-checked"), ("GO 222", "GO 222", "intermediate stature", SB["GO-H222"], "Stature stress GO-H222: ALPC-0...4", "yes (I1–I9); C2 re-checked"),
             ("GOR-BODY-03 (251)", "GOR-BODY-03 (251)", "maximum generator-reachable stature", SB["GOR-BODY-03"], "Stature stress GOR-BODY-03: ALPC-0...4", "yes (I1–I9); C2 re-checked"),
             ("GOR-BODY-04", "GOR-BODY-04", "Narrow frame", SB["GOR-BODY-04"], "ALPC-5 GOR-BODY-04", "no"), ("GOR-BODY-12", "GOR-BODY-12", "frame", SB["GOR-BODY-12"], "ALPC-5 GOR-BODY-12", "no"),
             ("GOR-BODY-14", "GOR-BODY-14", "frame (depth vs MF)", SB["GOR-BODY-14"], "ALPC-5 GOR-BODY-14", "no"), ("GOR-BODY-05 (Broad)", "GOR-BODY-05 (Broad)", "Broad frame (render)", SB["GOR-BODY-05"], None, "no"),
             ("GOR-BODY-16", "GOR-BODY-16", "low composition 0.25 / 0.25", None, "ALPC-6 skin half: GOR-BODY-16 skin vs MF and SK at the same low composition", "waist reading only (§7)")]
    for b, bh, role, H, k, tgt in roles:
        a = CC["arm_tube"][b]; c = CC["arm_clearance"][b]
        T.append("| %s | %s | %s | %s | %s | %s | %.4f | %d / %d | %.2f |" % (b, role, f4(H), cnt(AL["rows"][k]) if k else "not an ALPC body (render)", cnt(ALh["rows"][k]) if k and k in ALh["rows"] else "—", tgt, CC["contour"][b]["flank_flare"], a["l"]["trunk_verts_inside_arm_tube"], a["r"]["trunk_verts_inside_arm_tube"], c["signed_clearance_both_sides_cm"]))
    fp = os.path.join(EV, "skeletal", "true208.json")
    if os.path.exists(fp):
        t8 = jl(fp)
        T += ["", "### True minimum stature body GO-H208 (`skeletal/true208.json`; `w1i_drivers/true208.py`)", "",
              "GOR-BODY-02 keeps the W1f 208 cm donor (height macro 0.7019), but the W1i skeleton lands it at %.1f cm. GO-H208 uses a donor at height macro %.3f so the same W1i skeleton lands at %.2f cm. Not a solver body." % (SB["GOR-BODY-02"], t8["height_macro"], t8["stature"]), "",
              "| Reading | Result |", "|---|---|", "| ALPC-0…4 (ordinary rule) | %s |" % ("all PASS" if not t8["not_pass_ALPC_0_4"] else "; ".join(t8["not_pass_ALPC_0_4"]))]
        for hs in (208, 215, 222, 229):
            v = t8["ALPC-7 vs SKB%d" % hs]; T.append("| ALPC-7 vs Broad Skarn %d cm (%d rows) | %s |" % (hs, v["n"], "all PASS" if not v["not_pass"] else "; ".join(v["not_pass"])))
        T += ["| skin flank flare | %.4f |" % t8["flank_flare"], "| arm: section clearance / arm-tube trunk vertices inside (l / r) | %.2f cm / %d / %d |" % (t8["arm_clearance_cm"], t8["arm_tube"]["l"]["trunk_verts_inside_arm_tube"], t8["arm_tube"]["r"]["trunk_verts_inside_arm_tube"]),
              "| skin continuity hip/thorax, waist/thorax, waist/hip | %.3f, %.3f, %.3f |" % (t8["continuity_skin"]["hip_over_thorax"], t8["continuity_skin"]["waist_over_thorax"], t8["continuity_skin"]["waist_over_hip"]),
              "| skeleton continuity hip/thorax, waist/thorax, waist/hip | %.3f, %.3f, %.3f |" % (t8["continuity_skeleton"]["hip_over_thorax"], t8["continuity_skeleton"]["waist_over_thorax"], t8["continuity_skeleton"]["waist_over_hip"])]
    # 7 continuity
    RCt = CC["continuity_references"]
    T += ["", "## 7. Structural-continuity readings (W1i §2, §5, §6; `skeletal/contour_clearance.json` → continuity)", "",
          "Trunk-only plane sections at r = (u − hip-joint height) / (suprasternal − hip-joint height), r 0 … 0.8 in 0.025 steps (`w1i_drivers/trunk_profile.py`). hip/thorax = widest section r 0–0.2 ÷ widest r 0.4–0.72; waist/thorax and waist/hip use the narrowest section r 0.15–0.45; d2 = largest |second difference| of the breadth (b) or depth (d) profile ÷ stature over r 0.1–0.7 (a crease reading). Solver limits from the accepted references (not invented), as active from run I8: skeleton waist/thorax ≥ %.3f (least-pinched reference), skeleton waist/hip ≥ %.3f (least-shelved reference), skeleton d2 b / d ≤ %.4f / %.4f (largest reference), skin waist/hip ≥ %.3f (lowest reference), applied to the reference body only. Skeleton hip/thorax ≤ %.3f (largest reference) was active in runs I1–I7 and dropped in I8; it is reported, not enforced. Broad Skarn readings on the same metric: `skeletal/skb_continuity.json`." % (L["lean_waist_min"], L["lean_shelf_min"], L["lean_d2b_max"], L["lean_d2d_max"], L["skin_shelf_min"], L["lean_hip_max"]), "",
          "| Body | hip / thorax | waist / thorax | waist / hip | d2 b | d2 d |", "|---|---|---|---|---|---|"]
    for k, v in RCt.items():
        for lay in ("skeleton", "skin"):
            c = v[lay]; T.append("| %s %s (reference) | %.3f | %.3f | %s | %.4f | %.4f |" % (k, lay, c["hip_over_thorax"], c["waist_over_thorax"], f4(c.get("waist_over_hip")), c["d2b"], c["d2d"]))
    for k, c in CC["continuity"].items():
        if k.startswith("GO") or k.startswith("GOR"):
            T.append("| %s | %.3f | %.3f | %.3f | %.4f | %.4f |" % (k, c["hip_over_thorax"], c["waist_over_thorax"], c["waist_over_hip"], c["d2b"], c["d2d"]))
    if "low_comp_waist" in CC:
        T += ["", "Low-composition waist (GOR-BODY-16; plane-section breadth at the measurement layer's crest level ÷ narrowest of its 8 levels above it (the slab readings are in `skeletal/waist_slab_vs_section.log`), ≥ 1 = a waist above the crest; `gn6.waist_rise`): " + ", ".join("%s %.4f" % (k, v) for k, v in CC["low_comp_waist"].items()) + "."]
    # 8 arm
    T += ["", "## 8. Contour, flank flare and arm clearance (`skeletal/contour_clearance.json`)", "",
          "(a) Trunk-section test (upper-arm vertices vs the trunk's closed section; band below). (b) Arm-tube test (trunk vertices inside the closed upper-arm tube; tested range below the shoulder joint). Neither reaches the top of the axilla; `sheets/axilla_close.jpg` shows that band.", "",
          "| Body | chest-lead | buttock-lead | flank flare | (a) inside / testable | (a) band (cm) | (a) clearance (cm) | (b) inside l / r | (b) range below shoulder (cm) | min vertex gap (cm) |", "|---|---|---|---|---|---|---|---|---|---|"]
    for k in CC["contour"]:
        a = CC["arm_clearance"][k]; t = CC["arm_tube"][k]; c = CC["contour"][k]
        T.append("| %s | %.4f | %.4f | %.4f | %d / %d | %.1f–%.1f | %.3f | %d / %d | %.1f–%.1f | %.2f |" % (k, c["chest_lead"], c["buttock_lead"], c["flank_flare"], a["verts_inside_trunk_section"], a["n_testable_closed_section"], a["testable_band_cm"][0], a["testable_band_cm"][1], a["signed_clearance_both_sides_cm"],
                 t["l"]["trunk_verts_inside_arm_tube"], t["r"]["trunk_verts_inside_arm_tube"], t["l"]["tested_range_cm_below_shoulder"][0], t["l"]["tested_range_cm_below_shoulder"][1], a["min_arm_trunk_gap_cm"]))
    # 9 sensitivity
    if SEN:
        def summ(v):
            n = sum(len(a) for a in v["not_pass"].values()); f = sum(1 for a in v["not_pass"].values() for s in a if s.startswith("FAIL")); return n, f
        b = SEN["base"]; P = SEN["perturb"]
        keep_all = [k for k, v in P.items() if summ(v)[0] == 0 and v["skin_TB_vs_SK"] >= 0.01]
        fails = [k for k, v in P.items() if summ(v)[1] > 0]
        T += ["", "## 9. R-14 sensitivity (`solver/sensitivity_w1i.json`; `w1i_drivers/sens6.py`)", "",
              "Each of the %d gn6 values perturbed alone by factor × (1 ± %.0f %%) (Aka ± 0.05). The reference and all four stature bodies are rebuilt and re-checked with the ordinary AD-G10 rule: every GO reference skeletal row, ALPC-0…4 at 208 / 215 / 222 / 251 cm, ALPC-7 at every cross-height pair, and thoracic breadth > SK at the 1 %% convention." % (len(gn6.NAMES), 100 * SEN["step"]), "",
              "**%d of %d perturbations preserve every accepted relation; %d reach FAIL.** Base: %d non-PASS rows; thoracic breadth vs SK %+.2f %%; flank flare %.4f; arm clearance %.2f cm; low-composition waist %.4f." % (len(keep_all), len(P), len(fails), summ(b)[0], 100 * b["skin_TB_vs_SK"], b["flank_flare"], b["arm_clearance_cm"], b["low_comp_waist_rise"]), "",
              "| Perturbation | Value | Rows not PASS (body: rows) | TB vs SK | flank flare | arm clearance (cm) | skeleton hip / thorax | low-comp waist |", "|---|---|---|---|---|---|---|---|"]
        fp = os.path.join(EV, "solver", "i9point", "sensitivity_I9point.json")
        if os.path.exists(fp):
            P9 = jl(fp)["perturb"]; k9 = [k for k, v in P9.items() if summ(v)[0] == 0 and v["skin_TB_vs_SK"] >= 0.01]; f9 = [k for k, v in P9.items() if summ(v)[1] > 0]
            T[-2:-2] = ["Before the centering step (the I9 solver point, `solver/i9point/sensitivity_I9point.json`, same test): %d of %d preserve every accepted relation; %d reach FAIL (%s)." % (len(k9), len(P9), len(f9), ", ".join(f9)), ""]
        for k, v in P.items():
            np_ = "; ".join("%s: %s" % (kk, ", ".join(a)) for kk, a in v["not_pass"].items() if a) or "0"
            T.append("| %s | %.4f | %s | %+.2f %% | %.4f | %.2f | %.3f | %.4f |" % (k, v["value"], np_, 100 * v["skin_TB_vs_SK"], v["flank_flare"], v["arm_clearance_cm"], v["skeleton"]["hip_over_thorax"], v["low_comp_waist_rise"]))
    # 10 directional / skin / ocular / ears
    Dh = {key(x): x for x in DCh}
    T += ["", "## 10. Directional checks (`directional_checks.json`; %d rows: %s)" % (len(DC), cnt(DC)), "", "| Cand | Check | W1h value | W1h result | W1i value | Comparator | W1i result | margin |", "|---|---|---|---|---|---|---|---|"]
    for x in DC:
        y = Dh.get(key(x))
        if res(x) != "PASS" or (y and res(y) != "PASS") or x["cand"] == "GO" or x.get("b") == "GO":
            T.append("| %s | %s | %s | %s | %s | %s %s | %s | %s |" % (x["cand"], x["check"], f4(y["va"]) if y else "—", bold(res(y)) if y else "—", f4(x["va"]), x["op"], f4(x["vb"]), bold(res(x)), pm(margin(x))))
    Wh = {key(x): x for x in WCh}
    T += ["", "## 11. Skin diagnostics (`w1e_checks.json`; composition-inclusive, never a pass condition; %d rows: %s)" % (len(WC), cnt(WC)), "", "| Cand | Check | W1h value | W1h result | W1i value | Comparator | W1i result |", "|---|---|---|---|---|---|---|"]
    for x in WC:
        y = Wh.get(key(x))
        if res(x) in ("PASS", "NOT RUN") and (y is None or res(y) in ("PASS", "NOT RUN")): continue
        T.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], f4(y["va"]) if y else "—", bold(res(y)) if y else "—", f4(x["va"]), x["op"], f4(x["vb"]) if isinstance(x.get("vb"), float) else x.get("vb"), bold(res(x))))
    T += ["", "## 12. Ocular (`ocular/ocular_w1i.json`; only the GO body changed)", "", "| Body | Ring (cm) | Ring-globe clr (cm) | Globe (cm) | globe/HH vs MF | Fits |", "|---|---|---|---|---|---|"]
    for i, r in OC["bodies"].items():
        T.append("| %s | %.3f × %.3f | %.2f | %.3f | %.3f | %s |" % (i, r["ring_breadth_cm"], r["ring_height_cm"], r["ring_globe_clearance_cm"], r["globe_cm"], r["vs_MF"]["globe_over_HH"], r["fits"]))
    er = rows_of(EC)
    T += ["", "## 13. Ears (`ears/ear_checks.json`; v2 families unchanged, re-attached): %d rows, %s" % (len(er), cnt(er)), ""]
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n")
    m = jl(EV, "candidates", "GO_meas.json"); geo = os.path.join(EV, "geometry", "GO_r6.npz")
    A = ["# RAC W1i ARM record — GO (Gorrund central, W1i structural-continuity re-solve)", "", "Generated by `tools/rac/w1/gen_w1i_docs.py`. **Technical verdict: CONSTRAIN — AUTHOR-ACCEPTED W1 ARM** (October 7, 2026; author ruling `reviews/chatgpt-rac-w1j-gorrund-final-author-acceptance.md`, issued by ChatGPT with Tyler's delegated authority, confirmed by Tyler in chat). This W1i geometry is the retained W1j point (identical meshes, `reviews/rac-w1j-evidence/geometry_identity.json`) and is accepted as the constrained central reference anatomy. The accepted anatomical relationships and this central reference outcome are canon; the construction values in `tools/rac/w1/cfg/w1i/GO.json` (including femur robusticity 1.3863) and the solver search bounds are reference-construction / tooling values for reproducibility, not species-wide biological constants, creator slider values or limits. Sensitivity and residuals as disclosed in `reviews/claude-rac-w1j-author-acceptance-gate.md` (22 / 32 single ±2 % perturbations keep every relation, 2 FAIL; upper-thorax construction locally narrow; small ALPC-1b base margin at 208 cm; ALPC-6 skin-half residuals diagnostic only; armpit band visually accepted, NOT DEMONSTRATED).", "",
         "- Geometry: `%s` (sha256 %s); skeleton: `reviews/rac-w1i-evidence/skeleton/GO-LEAN_r6.npz`; config `tools/rac/w1/cfg/w1i/GO.json`" % (os.path.relpath(geo, R), sha(geo)),
         "- Stature (R-6) %.2f cm; HH %.2f cm" % (m["stature_r6"], m["combined"]["cranio"]["HH"]), "", "## Skeletal checks", ""] + rows_md([x for x in SK if x["cand"] == "GO" and res(x) != "NOT RUN"], by_t=True, with_margin=True)
    A += ["", "## Directional checks", ""] + rows_md([x for x in DC if x["cand"] == "GO"]) + ["", "## Skin diagnostics (composition-inclusive)", ""] + rows_md([x for x in WC if x["cand"] == "GO" and res(x) != "NOT RUN"])
    open(os.path.join(ARM, "claude-rac-w1i-arm-GO.md"), "w").write("\n".join(A) + "\n")
    print("tables + ARM record written")

if __name__ == "__main__":
    main()
