"""Generate the RAC W1k (Grask W1 acceptance gate) evidence tables from the JSON in reviews/rac-w1k-gr-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
EV = os.path.join(R, "reviews", "rac-w1k-gr-evidence"); EH = os.path.join(R, "reviews", "rac-w1h-evidence"); EI = os.path.join(R, "reviews", "rac-w1i-evidence")
jl = lambda *p: json.load(open(os.path.join(*p)))
def res(r): return r.get("result") or r.get("result_ADG10") or ("PASS" if r.get("pass") else "FAIL")
def fv(v):
    if isinstance(v, (list, tuple)): return " / ".join("%.4f" % x for x in v)
    return "%.4f" % v if isinstance(v, (int, float)) else str(v)
def margin(r):
    va, vb, op = r.get("va"), r.get("vb"), r.get("op", "")
    if not isinstance(va, (int, float)) or not isinstance(vb, (int, float)) or op not in (">", "<", ">=", "<="): return "—"
    m = (va - vb) / abs(vb) * (1 if op in (">", ">=") else -1); return "%+.2f %%" % (100 * m)
def main():
    E = jl(EV, "eval.json"); C = jl(EV, "composition.json"); MH = jl(EV, "matched_height.json"); CC = jl(EH, "skeletal", "contour_clearance.json")
    T = ["# RAC W1k — Grask W1 acceptance gate: evidence tables", "", "Generated by `tools/rac/w1/gen_w1k_docs.py` from the JSON in this folder. Nothing here is canon. Rule: AD-G10 (strict > / < PASS beyond 1 %, else NOT DEMONSTRATED; ≥ / ≤ MARGINAL within 1 %; '~' ±0.010; T-SENSITIVE = result changes with t). Comparators: accepted MF-M-R, SK, and the accepted Gorrund point (W1i/W1j) in the GO slot. Skeletal rows = CIB validation layer (W1h method); skin rows = composition-inclusive diagnostics only (GRASK L229).", ""]
    T += ["## 1. Bodies", "", "| Body | Directory role | Stature R-6 (cm) |", "|---|---|---|"]
    for k, v in E.items(): T.append("| %s | %s | %.2f |" % (k, "own skeleton" if v.get("skeletal") else "candidate skeleton + generator tissue", v["stature"]))
    for k in E:
        v = E[k]; T += ["", "## 2.%s %s" % (list(E).index(k) + 1, k), ""]
        for layer in ("skeletal", "skin", "directional"):
            rows = v.get(layer)
            if not rows: continue
            T += ["### %s (%d rows: %d not PASS)" % (layer, len(rows), sum(res(r) != "PASS" for r in rows)), "", "| Cand | Check | Value | Op | Comparator | Margin | Result |", "|---|---|---|---|---|---|---|"]
            for r in rows:
                T.append("| %s | %s | %s | %s | %s %s | %s | %s |" % (r.get("cand"), r.get("check"), fv(r.get("va")), r.get("op"), r.get("b", ""), fv(r.get("vb")), margin(r), res(r) if res(r) == "PASS" else "**%s**" % res(r)))
            T.append("")
    T += ["## 3. Grask vs Gorrund (accepted) and Broad Skarn at overlapping stature (`matched_height.json`)", "", "Statures: " + ", ".join("%s %.1f cm" % (k, v) for k, v in MH["stature"].items()) + ".", "", "| Reading | GR | Op | Comparator | Value | Margin | Result | Canon |", "|---|---|---|---|---|---|---|---|"]
    for r in MH["rows"]: T.append("| %s | %.4f | %s | %s | %.4f | %+.2f %% | %s | %s |" % (r["reading"], r["GR"], r["op"], r["comparator"], r["value"], r["margin_pct"], r["result"] if r["result"] == "PASS" else "**%s**" % r["result"], r["canon"]))
    T += ["", "## 4. Trunk continuity readings (`composition.json`; W1i/W1j `gn6.cont`, `waist_rise`)", "", "| Body | hip / thorax | waist / thorax | waist / hip | d2b | waist rise |", "|---|---|---|---|---|---|"]
    for k, v in C["continuity"].items(): T.append("| %s | %.3f | %.3f | %.3f | %.4f | %.3f |" % (k, v["hip_over_thorax"], v["waist_over_thorax"], v["waist_over_hip"], v["d2b"], v["waist_rise"]))
    T += ["", "## 5. Low composition at the SAME composition (GR-LOW vs MF-M-R-LOW and SK-LOW, 0.25 / 0.25; skin diagnostics)", "", "| Check | GR | Op | Same-composition comparator | Result |", "|---|---|---|---|---|"]
    for r in C["low_same_composition_skin"]: T.append("| %s | %.4f | %s | %.4f | %s |" % (r["check"], r["va"], r["op"], r["vb"], r["result"]))
    T += ["", "## 6. Arm clearance (GR-G3; W1h, unchanged geometry; `reviews/rac-w1h-evidence/skeletal/contour_clearance.json`)", "", "| Body | Min arm–trunk vertex gap (cm) | Upper-arm vertices inside a closed trunk section | Testable band (cm below shoulder joint) | Arm-tube: trunk vertices inside (L / R) |", "|---|---|---|---|---|"]
    for n in ("GR W1h", "MF-M-R", "SK"):
        a = CC["arm_clearance"][n]; t = CC["arm_tube"][n]; su = a["shoulder_joint_u"]
        T.append("| %s | %.2f | %d of %d testable | %.1f–%.1f | %d / %d |" % (n, a["min_arm_trunk_gap_cm"], a["verts_inside_trunk_section"], a["n_testable_closed_section"], su - a["testable_band_cm"][1], su - a["testable_band_cm"][0], t["l"]["trunk_verts_inside_arm_tube"], t["r"]["trunk_verts_inside_arm_tube"]))
    T += ["", "## 7. Ears (W1i `ears/ear_checks.json`, GR rows)", "", "| Cand | Check | Value | Op | Comparator | Result |", "|---|---|---|---|---|---|"]
    for r in jl(EI, "ears", "ear_checks.json"):
        if "GR" in (r["cand"], r["b"]): T.append("| %s | %s | %s | %s | %s | %s |" % (r["cand"], r["check"], fv(r["va"]), r["op"], fv(r["vb"]), "REPORT" if r["report_only"] else ("PASS" if r["pass"] else "FAIL")))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written")
if __name__ == "__main__": main()
