"""Generate the RAC W1t (Durrim W1 acceptance gate) evidence tables from the JSON in reviews/rac-w1t-du-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w1t-du-evidence")
jl = lambda *p: json.load(open(os.path.join(*p)))
ex = lambda f: os.path.exists(os.path.join(EV, f))
def res(r): return r.get("result") or r.get("result_ADG10") or ("PASS" if r.get("pass") else "FAIL")
def fv(v):
    if isinstance(v, (list, tuple)): return " / ".join(fv(x) for x in v)
    return "%.4f" % v if isinstance(v, float) else str(v)
def margin(r):
    va, vb, op = r.get("va"), r.get("vb"), r.get("op", "")
    if not isinstance(va, float) or not isinstance(vb, float) or op not in (">", "<", ">=", "<="): return "—"
    return "%+.2f %%" % (100 * (va - vb) / abs(vb) * (1 if op in (">", ">=") else -1))
def rows_md(rows):
    T = ["| Cand | Check | Value | Op | Comparator | Margin | Result |", "|---|---|---|---|---|---|---|"]
    for r in rows: T.append("| %s | %s | %s | %s | %s %s | %s | %s |" % (r.get("cand"), r.get("check"), fv(r.get("va")), r.get("op"), r.get("b", ""), fv(r.get("vb")), margin(r), res(r) if res(r) in ("PASS", "REPORT") else "**%s**" % res(r)))
    return T
def skel_md(rows):
    T = ["| Check | Canon | t = 0 (DU / comparator) | t = 0.5 | t = 1.0 | Comparator | Result |", "|---|---|---|---|---|---|---|"]
    for r in rows: T.append("| %s | %s | %s | %s | %s | %s | %s |" % (r["check"], r["canon"], *("%.4f / %.4f" % tuple(r["by_t"][t]) for t in ("0.0", "0.5", "1.0")), r["b"], r["result"] if r["result"] in ("PASS", "REPORT") else "**%s**" % r["result"]))
    return T
NAMES = {"W1g": "DU central (DU-NAT as built)", "NARROWB": "DU Narrow, breadth-only write", "BROADB": "DU Broad, breadth-only, pelvis x1.08 (Durrim rule)", "BROADB_P112": "DU Broad, breadth-only, pelvis x1.12 (elf / short-race rule)",
         "LOW_same_composition": "DU low 0.25 / 0.25 vs MF-M-R-LOW / SK-LOW / PK-LOW / CG-LOW (same composition)", "COMP_LOWMUS": "DU low muscle 0 / 0.5", "COMP_HIMUS": "DU high muscle 1 / 0.5",
         "COMP_HIFAT": "DU higher fat 0.5 / 1", "COMP_HIBOTH": "DU high muscle + fat 1 / 1"}
SKN = {"W1g": "BASE", "NARROWB": "NARROWB", "BROADB": "BROADB", "BROADB_P112": "BROADB_P112"}
def main():
    T = ["# RAC W1t — Durrim W1 acceptance gate: evidence tables", "", "Generated by `tools/rac/w1/gen_w1t_docs.py` from the JSON in this folder. Nothing here is canon. Rule: AD-G10. Comparators: accepted MF-M-R, SK, SG, Aelari AEL1, Vael VAL4, Fenn FNL4, Gorrund, Grask W1l, Pipkin PK-NAT, Cogling CGJ7, Halvren HVC1. Skin pelvic rows are composition-inclusive diagnostics (PV-D16); skeletal rows are CIB stations on the W1i skeletal base. Joint rows per stature use the stature-scaled slab.", ""]
    C = {t: jl(EV, "central_%s.json" % t) for t in NAMES if ex("central_%s.json" % t)}
    T += ["## 1. Scored rows across bodies", "", "| Body | rows (skin + directional + added) | not PASS |", "|---|---|---|"]
    for t, c in C.items():
        bad = [r for k in ("skin", "directional", "added") for r in c[k] if res(r) not in ("PASS", "REPORT")]
        T.append("| %s | %d + %d + %d | %s |" % (NAMES[t], len(c["skin"]), len(c["directional"]), sum(r["result"] != "REPORT" for r in c["added"]), "; ".join("%s (%s) → %s" % (r["check"], r.get("b"), res(r)) for r in bad) or "none"))
    B = jl(EV, "boundary.json")
    T += ["", "## 2. Boundary and short-race cases", "", "Statures: " + ", ".join("%s %.1f cm" % kv for kv in B["statures"].items()) + ".", "", "Femur / tibia (segment plausibility): " + ", ".join("%s %.3f" % kv for kv in B["plausibility"].items()) + "."]
    for cid, c in B["cases"].items():
        T += ["", "### %s — %s (%s)" % (cid, c["title"], c["canon"]), "", "| Pair | Reading | A | Op | B | A vs B | Result |", "|---|---|---|---|---|---|---|"]
        for r in c["rows"]: T.append("| %s | %s | %.4f | %s | %.4f | %+.1f %% | %s |" % (r["check"], r["reading"], r["va"], r["op"], r["vb"], r["pct"], r["result"] if r["result"] in ("PASS", "REPORT") else "**%s**" % r["result"]))
    if ex("skeletal_B152.json"):
        T += ["", "### B152 skeletal proxy (DU152 vs matched-stature MF152 grids; PK / CG / SK rows here compare against central bodies at other statures and carry no B152 verdict)", ""] + skel_md(jl(EV, "skeletal_B152.json"))
    for i, (t, c) in enumerate(C.items()):
        T += ["", "## 3.%d %s" % (i + 1, NAMES[t]), ""]
        if t in SKN and ex("skeletal_%s.json" % SKN[t]): T += ["### skeletal (CIB)", ""] + skel_md(jl(EV, "skeletal_%s.json" % SKN[t])) + [""]
        note = " — scored against REFERENCE-composition comparators, not like for like" if t.startswith("COMP_") else ""
        for L in ("skin", "directional", "added"): T += ["### %s (%d rows)%s" % (L, len(c[L]), note), ""] + rows_md(c[L]) + [""]
    P = jl(EV, "composition.json")
    T += ["## 4. Trunk continuity readings", "", "| Body | hip / thorax | waist / thorax | waist / hip | d2b | waist rise |", "|---|---|---|---|---|---|"]
    for k, v in P["continuity"].items(): T.append("| %s | %.3f | %.3f | %.3f | %.4f | %.3f |" % (k, v["hip_over_thorax"], v["waist_over_thorax"], v["waist_over_hip"], v["d2b"], v["waist_rise"]))
    if ex("probes.json"):
        T += ["", "## 5. Probes (not proposed)", ""]
        for k, v in jl(EV, "probes.json").items(): T.append("- **%s**: %s" % (k, v))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
