"""Generate the RAC W2C (Grask boundary foundation) evidence tables from reviews/rac-w2c-gr-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2c-gr-evidence")
f4 = lambda v: "%.4f" % v if isinstance(v, float) else ("—" if v is None else str(v))
GROUPS = [("Stature foundation", ["GR198", "GR208", "GR218", "GR229", "GR239"]),
          ("Matched-height Skarn and human comparators", ["SK198", "SK208", "SK218", "SK229", "SKB218", "MF173", "MF203", "SG", "GO217", "GO224", "GOH208", "AE"]),
          ("Frames (final and probes)", ["GRN5", "GR218", "GRB2", "GRN", "GRN2", "GRN3", "GRN4", "GRB"]),
          ("Named extremes", ["GR-BODY-10", "GR-BODY-11", "GR-BODY-12", "GR-BODY-13", "GR-BODY-14", "GR-BODY-15", "GR-BODY-16", "GR-BODY-17", "GR-BODY-18"]),
          ("Composition (W1l skeleton) and same-composition Skarn / Marchfolk", ["GR-BODY-06", "GR-BODY-07", "GR-BODY-08", "GR-BODY-09", "GR-LOW", "SK-LOWMUS", "SK-HIMUS", "SK-HIFAT", "SK-HIBOTH", "SK-LOW", "MF-LOW"])]
CODES = {"U": "head allometry", "C": "continuity 198 -> 218 -> 239", "K": "joints vs allometry", "G": "canonical Grask rows per body", "D": "frame domains", "L": "frame keeps lengths",
         "S": "matched-height Grask vs Skarn", "B": "span vs Broad Skarn", "F": "frames stay Grask", "H": "minimum Grask vs Marchfolk / Sagekin", "M": "composition", "X": "named extremes",
         "AD2": "GR-BODY-10 vs Skarn (AD-2)", "AD3": "GR-BODY-10 vs Gorrund (AD-3, provisional)"}
def main():
    d = json.load(open(os.path.join(EV, "w2c.json"))); V = d["values"]
    T = ["# RAC W2C — Grask boundary foundation: evidence tables", "", "Generated by `tools/rac/w1/gen_w2c_docs.py`. NON-CANON diagnostics. Skeletal: CIB grids, exact-plane S7 (t = 0 shown). Joints: stature-scaled slab (knee: see the section diagnostic). Rule: AD-G10.", "",
         "## Construction", "", "```json", json.dumps(json.load(open(os.path.join(EV, "construction.json"))), indent=1, default=str)[:20000], "```", ""]
    for title, cols in GROUPS:
        cols = [c for c in cols if c in V]
        keys = [k for k in V[cols[0]] if "[t=0.5]" not in k and "[t=1.0]" not in k]
        for c in cols[1:]: keys += [k for k in V[c] if k not in keys and "[t=0.5]" not in k and "[t=1.0]" not in k]
        T += ["## %s" % title, "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for k in keys: T.append("| %s | %s |" % (k, " | ".join(f4(V[c].get(k)) for c in cols)))
        T.append("")
    T += ["## Checks", ""]
    for code, name in CODES.items():
        cc = [c for c in d["checks"] if c["code"] == code]
        if not cc: continue
        T += ["### %s — %s (%d; not PASS / REPORT: %d)" % (code, name, len(cc), sum(c["result"] != "PASS" and not c["result"].startswith("REPORT") for c in cc)), "", "| Check | A | Value | Op | B | Value | Margin | Result | Note |", "|---|---|---|---|---|---|---|---|---|"]
        for c in cc:
            va = " / ".join("%.4f" % x for x in c["va"]) if isinstance(c["va"], list) else f4(c["va"])
            T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (c["check"], c["a"], va, c["op"], c["b"], f4(c["vb"]), ("%+.2f %%" % c["margin_pct"]) if isinstance(c.get("margin_pct"), float) else "",
                                                                c["result"] if c["result"] == "PASS" or c["result"].startswith("REPORT") else "**%s**" % c["result"], c.get("note", "")))
        T.append("")
    T += ["## Canonical Grask rows per body (not PASS only)", "", "| Body | Layer | Row | Result | Values (t: Grask / reference) |", "|---|---|---|---|---|"]
    for b, rows in d["canonical_rows"].items():
        for x in rows:
            if x["result"] in ("PASS", "REPORT", None): continue
            v = "; ".join("%s: %.4f / %.4f" % (t, w["va"], w["vb"]) for t, w in x["by_t"].items() if isinstance(w, dict)) if x.get("by_t") else ("%.4f / %.4f" % (x["va"], x["vb"]) if x.get("va") else "")
            T.append("| %s | %s | %s | %s | %s |" % (b, x["kind"], x["check"], x["result"], v))
    T += ["", "## Stature-matched human reference for fixed-reference W1 rows (report)", "", "| Row | Body | Grask | MF 173 | vs MF 173 | MF at stature | vs MF at stature | Skarn matched | vs Skarn |", "|---|---|---|---|---|---|---|---|---|"]
    for r in json.load(open(os.path.join(EV, "drift.json"))):
        T.append("| %s | %s | %.4f | %.4f | %+.1f %% | %.4f%s | %+.1f %% | %s | %s |" % (r["row"], r["body"], r["grask"], r["MF173"], r["vs_MF173_pct"], r["MF_at_stature"], " (extrap.)" if r["extrapolated"] else "", r["vs_MF_at_stature_pct"],
                                                                         f4(r.get("SK_matched")), ("%+.1f %%" % r["vs_SK_matched_pct"]) if "vs_SK_matched_pct" in r else "—"))
    T += ["", "## Knee breadth: stature-scaled slab vs exact plane section (DIAGNOSTIC)", "", "| Body | slab (scaled) / stature | section (principal) / stature | slab ÷ section |", "|---|---|---|---|"]
    for n, v in json.load(open(os.path.join(EV, "knee_section_diagnostic.json"))).items():
        s = v.get("slab_scaled"); T.append("| %s | %s | %.4f | %s |" % (n, f4(s), v["section_principal_over_H"], ("%.3f" % (s / v["section_principal_over_H"])) if s else "—"))
    T += ["", "## Arm clearance (GR-G3)", "", "| Body | smallest gap (cm) | upper-arm vertices inside a closed trunk section | trunk vertices inside the arm tube (l / r) |", "|---|---|---|---|"]
    for n, v in json.load(open(os.path.join(EV, "arm_clearance.json"))).items():
        T.append("| %s | %.2f | %d | %d / %d |" % (n, v["arm_clearance"]["l"]["min_arm_trunk_gap_cm"], v["arm_clearance"]["l"]["verts_inside_trunk_section"], v["arm_tube"]["l"]["trunk_verts_inside_arm_tube"], v["arm_tube"]["r"]["trunk_verts_inside_arm_tube"]))
    T += ["", "## Hanging-hand reach (R-6; diagnostic)", "", "| Body | fingertip / stature | knee / stature | fingertip above knee (cm) |", "|---|---|---|---|"]
    for n, v in json.load(open(os.path.join(EV, "reach.json"))).items(): T.append("| %s | %.3f | %.3f | %.1f |" % (n, v["fingertip_h"], v["knee_h"], v["tip_above_knee_cm"]))
    T += ["", "## Named-extreme search probes (proportion rows; stature re-solved)", "", "| Probe | torso | leg | arm | span | forearm / arm | lower leg / leg | hand | thinnest row | non-PASS |", "|---|---|---|---|---|---|---|---|---|---|"]
    for f in ("search_gr10_uniform.json", "search_extremes.json"):
        for n, v in json.load(open(os.path.join(EV, f))).items():
            r = v["ratio"]; T.append("| %s | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f | %s %+.2f %% | %s |" % (n, r["torso_share"], r["leg_share"], r["arm_share"], r["span_der"], r["forearm_over_arm"], r["shin_over_leg"], r["hand_share"], v["thinnest"][0], v["thinnest"][1], "; ".join("%s %s" % tuple(x) for x in v["non_pass"]) or "—"))
    T += ["", "## Diagnostic envelope candidates (NON-CANON; GR198 / 208 / 218 / 229 / 239)", "", "| Reading | min | body | max | body |", "|---|---|---|---|---|"]
    for k, e in d["envelope_candidates"].items():
        if "[t=0.5]" in k or "[t=1.0]" in k: continue
        T.append("| %s | %.4f | %s | %.4f | %s |" % (k, e["min"], e["min_body"], e["max"], e["max_body"]))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
