"""Generate the RAC W2E (Sagekin W2) evidence tables from reviews/rac-w2e-sg-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2e-sg-evidence")
f4 = lambda v: "%.4f" % v if isinstance(v, float) else ("—" if v is None else str(v))
GROUPS = [("Sagekin stature family (152 native route; >= 163 macro route)", ["SG152", "SG163", "SG173", "SG178", "SG181", "SG190", "SG203", "SG208"]),
          ("Matched-height Marchfolk comparators", ["MF152", "MF163", "MF173", "MF178", "MF181", "MF190", "MF203", "MF147"]),
          ("Frames (accepted human W2A1 writes)", ["SGN178", "SG178", "SGB178", "MFN173", "MFB173", "SGN152", "SG152", "SGB152", "SGN208", "SG208", "SGB208"]),
          ("Named validators and probes", ["SG04", "SG04x175", "SG04x200", "SG09", "SG10", "SG06", "SG07", "SG08", "MF178"]),
          ("Composition at 173 cm (Sagekin vs Marchfolk, same composition)", ["SG173-LOWMUS", "MF-LOWMUS", "SG173-HIMUS", "MF-HIMUS", "SG173-HIFAT", "MF-HIFAT", "SG173-HIBOTH", "MF-HIBOTH", "SG173-LOW", "MF-LOW", "SG173-MIN", "MF-MIN"]),
          ("Skarn guard, provisional elf sanity, 152 cm dependency, route checks", ["SK190", "SK203", "SK208", "SKB208", "FN181", "AE190", "DU152", "SG152-W1T", "SG163N", "MF163N"])]
CODES = {"U": "allometry", "C": "continuity 152 -> 208", "G": "accepted Sagekin W1 directional rows (fixed Marchfolk 173 reference)", "O": "RM-OT-01 Sagekin vs Marchfolk at matched height",
         "P": "pelvis / axial diagnostics (RM-UB-06; REPORT)", "K": "Skarn guard (REPORT)", "E": "PROVISIONAL anti-elf sanity (W1 Fenn / Aelari)", "F": "frames", "M": "composition",
         "X": "named validators SG-04 / -09 / -10", "J": "joints and long bone (RM-UB-03; REPORT)", "D": "152 cm Durrim-Marchfolk-Sagekin dependency and route cross-checks (REPORT)"}
def main():
    d = json.load(open(os.path.join(EV, "w2e.json"))); V = d["values"]
    T = ["# RAC W2E — Sagekin W2: evidence tables", "", "Generated by `tools/rac/w1/gen_w2e_docs.py`. NON-CANON diagnostics. Skeletal: CIB grids, exact-plane S7 (t = 0 shown in the value tables; rows sweep t = 0 / 0.5 / 1). "
         "Joints: exact-plane section (REFERENCE_ANATOMY_V1 §10). Rule: AD-G10. Sagekin tendencies are population tendencies; E rows are PROVISIONAL (W1 elves) and scored only where the W1 elf is beyond matched Marchfolk by 1 %.", ""]
    for title, cols in GROUPS:
        cols = [c for c in cols if c in V]
        keys = []
        for c in cols: keys += [k for k in V[c] if k not in keys and "[t=0.5]" not in k and "[t=1.0]" not in k]
        T += ["## %s" % title, "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for k in keys: T.append("| %s | %s |" % (k, " | ".join(f4(V[c].get(k)) for c in cols)))
        T.append("")
    T += ["## Checks", ""]
    for code, name in CODES.items():
        cc = [c for c in d["checks"] if c["code"] == code]
        if not cc: continue
        T += ["### %s — %s (%d; not PASS / REPORT: %d)" % (code, name, len(cc), sum(c["result"] != "PASS" and not c["result"].startswith("REPORT") for c in cc)), "",
              "| Check | A | Value | Op | B | Value | Margin | Result | Note |", "|---|---|---|---|---|---|---|---|---|"]
        for c in cc:
            va = " / ".join("%.4f" % x for x in c["va"]) if isinstance(c["va"], list) else f4(c["va"])
            vb = " / ".join("%.4f" % x for x in c["vb"]) if isinstance(c["vb"], list) else f4(c["vb"])
            T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (c["check"], c["a"], va, c["op"], c["b"], vb, ("%+.2f %%" % c["margin_pct"]) if isinstance(c.get("margin_pct"), float) else "",
                                                                c["result"] if c["result"] == "PASS" or c["result"].startswith("REPORT") else "**%s**" % c["result"], str(c.get("note", "")).replace("|", "/")))
        T.append("")
    T += ["## Accepted Sagekin W1 directional rows per body (not PASS only)", "", "| Body | Row | Result | Value | Marchfolk 173 |", "|---|---|---|---|---|"]
    for b, rows in d["canonical_rows"].items():
        for x in rows:
            if x["result"] != "PASS": T.append("| %s | %s | %s | %s | %s |" % (b, x["check"], x["result"], f4(x.get("va")), f4(x.get("vb"))))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
