"""Generate the W1j evidence tables from the JSON in reviews/rac-w1j-evidence (no hand-typed numbers)."""
import json, os, sys
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
EV = os.path.join(R, "reviews", "rac-w1j-evidence"); EI = os.path.join(R, "reviews", "rac-w1i-evidence")
sys.path.insert(0, os.path.join(R, "tools", "rac", "w1", "w1j_drivers"))
def jl(*p): return json.load(open(os.path.join(*p)))
import sens_summary as SS

def main():
    import gn7
    N = gn7.NAMES; LO, HI = gn7.LO, gn7.HI
    FT = jl(EV, "femur_trade.json"); IA = jl(EV, "interior_analysis.json"); IB = jl(EV, "interior_bounds.json"); GI = jl(EV, "geometry_identity.json")
    LG = max(v["waist_over_hip"] for v in jl(EV, "low_comp_references.json").values())
    S = {k: SS.summ(os.path.join(EV, "sensitivity", "sens_%s.json" % k)) for k in ("W", "D", "C")}
    SW = jl(EV, "sensitivity", "sens_W.json"); SI = SS.summ(os.path.join(EI, "solver", "sensitivity_w1i.json"))
    CAND = {"W": jl(EV, "candidates", "cand_W1i.json"), "D": jl(EV, "candidates", "cand_D.json"), "C": jl(EV, "candidates", "cand_C.json")}
    T = ["# RAC W1j — evidence tables", "", "Generated by `tools/rac/w1/gen_w1j_docs.py` from the JSON in this folder. Nothing here is canon. All checks use the ordinary AD-G10 rule (strict > / < beyond 1 %; ≥ / ≤ with MARGINAL under 1 %; '~' ±0.010; T-SENSITIVE = changes with t). W1j stature series: reference, true 208 cm (height macro 0.685), 215 / 222 cm donors, 251 cm donor (GOR-BODY-03, 253.0 cm); ALPC-7 at every Gorrund / Broad Skarn pair with Skarn height ≥ Gorrund height including the equal-height 208 pair.", ""]
    # 1 candidates
    T += ["## 1. Candidates and the ±2 % protocol (`sensitivity/sens_*.json`; `w1j_drivers/sens7.py`)", "",
          "Protocol: each of the 16 values alone × (1 ± 2 %) (ka amplitude ± 0.05) → 32 perturbations; for each, the reference and the four stature bodies are rebuilt and every accepted relation is re-checked (all GO reference skeletal rows, ALPC-0…4 at each stature, every ALPC-7 pair, thoracic breadth > SK beyond 1 %).", "",
          "| Candidate | Femur | Origin | Base: rows not PASS | Base TB vs SK | Perturbations keeping every relation | Perturbations reaching FAIL |", "|---|---|---|---|---|---|---|"]
    org = {"W": "W1i point (I9 + centering C2), retained", "D": "W1j linear programme at the femur-1.294 point (`candidates/cand_D.json`)", "C": "femur trade point, ceiling 1.30 (`candidates/cand_C.json`)"}
    for k in ("W", "D", "C"):
        s = S[k]; T.append("| %s | %.3f | %s | %d | %+.2f %% | **%d / %d** | %d (%s) |" % (k, CAND[k]["x"][N.index("thigh")], org[k], sum(len(v) for v in s["base_not_pass"].values()), s["base_TB_pct"], s["all_preserving"], s["n"], len(s["fail"]), ", ".join(s["fail"])))
    T += ["", "Same point under the W1i protocol (W1i stature series: W1f 208 cm donor, no equal-height 208 pair; `reviews/rac-w1i-evidence/solver/sensitivity_w1i.json`): %d / %d keep every relation, FAIL %s." % (SI["all_preserving"], SI["n"], ", ".join(SI["fail"])), ""]
    for k in ("W", "D", "C"):
        T += ["### Candidate %s — perturbations that lose a relation" % k, "", "| Perturbation | Thoracic breadth > SK (result, margin) | Rows lost (body: rows) |", "|---|---|---|"]
        for p, v in S[k]["lost"].items():
            T.append("| %s | %s %+.2f %% | %s |" % (p, v["TB_result"] if v["TB_result"] == "PASS" else "**%s**" % v["TB_result"], v["TB_vs_SK_pct"], "; ".join("%s: %s" % (b, ", ".join(r)) for b, r in v["rows"].items()) or "—"))
        T.append("")
    # 2 femur trade
    T += ["## 2. Femur-robusticity trade (`femur_trade.json`; `w1j_drivers/femur_trade2.py`)", "",
          "Linear model of every W1j constraint at the W1i point (`solver/gn7_J1_pt0.json`, Jacobian `solver/gn7_J1_J0.npy`), re-optimised with femur ≤ ceiling (every value ≥ %.0f %% of its bound range from the bound, step ≤ %.2f): ordinary thresholds kept, then the largest first-order ±2 %% tolerance t1 for the 12 values that can be made robust together and the largest tolerance t2 for the upper-thorax group. Each predicted point was then BUILT and checked." % (100 * FT["gap"], FT["trust"]), "",
          "| Femur ceiling | Femur at the point | t1 (12 values) | t2 (upper thorax) | Built: canonical rows not PASS (ordinary rule) | TB vs SK | Low-comp waist/hip ref / 208 (W1j guard ≥ %.4f) | Low-comp waist rise ref / 208 |" % LG, "|---|---|---|---|---|---|---|---|"]
    for r in sorted(FT["rows"], key=lambda q: -q["femur_ceiling"]):
        if "evaluation" not in r: T.append("| %.2f | — | — | — | %s | — | — | — |" % (r["femur_ceiling"], r.get("note", "")) ); continue
        ev = r["evaluation"]; lc = list(r["low_comp"].values())
        bad = "; ".join("%s: %s" % (b, ", ".join(a)) for b, a in ev["not_pass"].items() if a) or "0 (all PASS)"
        g = lambda v: ("**%.4f (below)**" if v < LG else "%.4f") % v
        T.append("| %.2f | %.3f | %.2f | %.3f | %s | %+.2f %% | %s / %s | %.3f / %.3f |" % (r["femur_ceiling"], r["femur"], r["t1"], r["t2"], bad, 100 * ev["skin_TB_vs_SK"], g(lc[0]["waist_over_hip"]), g(lc[1]["waist_over_hip"]), lc[0]["waist_rise"], lc[1]["waist_rise"]))
    T += ["", "Visual comparison of femur 1.386 / 1.306 / 1.294 (skin and skeleton), Broad Skarn 229 and SK: `sheets/femur_trade_hips.jpg`.", ""]
    # 3 interior analysis
    T += ["## 3. First-order interior analysis (`interior_analysis.json`; `w1j_drivers/interior_analysis.py`, `maxmin.py`)", "",
          "For a point and its Jacobian: the largest set of values whose single ±2 % steps can ALL be tolerated together (linear programme, ordinary thresholds, every value ≥ 2 % of its bound range from the bound), then — with that set held — the largest tolerance reachable for the others, as a fraction of 2 % (1.0 = ±2 %).", ""]
    for k, v in IA.items():
        T += ["### %s" % k, "", "- robust together (±2 %%): %s" % ", ".join(v["robust_together"]), "- not reachable: %s; joint tolerance %.3f (= ±%.2f %%)" % (", ".join(v["not_robust"]), v["joint_tolerance_of_rest"], 2 * v["joint_tolerance_of_rest"]), "",
              "| Value | Tolerance alone (fraction of 2 %) | Binding relations |", "|---|---|---|"]
        for n, s in v["single"].items():
            T.append("| %s | %.3f | %s |" % (n, s["tolerance_fraction_of_2pct"], "; ".join("%s (%.3f)" % (l[:70], t) for t, l in (s["binding"] or []))))
        T.append("")
    T += ["### Search bounds, gap and trust region vs the competing relations (`interior_bounds.json`; `w1j_drivers/interior_bounds.py`)", "",
          "Same programme (12 values held at full ±2 % tolerance, maximal joint tolerance for the upper-thorax group) with the 2 % gap, without it, and with every search bound widened by 0.5 and the step limit raised to 0.25. 'Active limits' are values sitting on a search bound or on the step limit at the optimum.", "",
          "| Point | Case | Joint tolerance (fraction of 2 %) | Active limits | First binding relations |", "|---|---|---|---|---|"]
    for k, v in IB.items():
        for case, r in v.items():
            T.append("| %s | %s | %s | %s | %s |" % (k, case, "%.3f" % r["joint_tolerance_fraction_of_2pct"] if r["x"] else "infeasible", ", ".join(r["active_limits"]) or "—", "; ".join("%s (%.3f)" % (l[:60], t) for t, l in (r["binding_relations"] or [])[:3]) or "—"))
    T.append("")
    # 4 values and bounds
    x = CAND["W"]["x"]
    T += ["## 4. Retained construction values and W1j search bounds", "", "| Value | W1j (= W1i) | Bound [lo, hi] | Distance to nearest bound, % of range | % of value |", "|---|---|---|---|---|"]
    for n, v, lo, hi in zip(N, x, LO, HI):
        dr = min(v - lo, hi - v) / (hi - lo); dv = min(abs(v - lo), abs(hi - v)) / abs(v)
        T.append("| %s | %.4f | [%.2f, %.2f] | %s | %.2f %% |" % (n, v, lo, hi, ("**%.1f %%**" if dr < 0.05 else "%.1f %%") % (100 * dr), 100 * dv))
    # 5 base results of the retained point
    b = SW["base"]
    T += ["", "## 5. Retained point re-built on the W1j stature series (`sensitivity/sens_W.json` → base)", "",
          "Geometry identical to W1i (`geometry_identity.json`, max |ΔV|: " + ", ".join("%s %.1g" % (k, v) for k, v in GI.items()) + "). Rows not PASS: %s. Stature %.2f cm; thoracic breadth vs SK %+.2f %%; skin flank flare %.4f; arm section clearance %.2f cm." % (sum(len(v) for v in b["not_pass"].values()), b["stature"], 100 * b["skin_TB_vs_SK"], b["flank_flare"], b["arm_clearance_cm"]), "",
          "### Low composition against the references at the SAME composition (muscle 0.25 / weight 0.25)", "", "| Body | hip / thorax | waist / thorax | waist / hip | waist rise (crest ÷ narrowest level above) |", "|---|---|---|---|---|"]
    LR = jl(EV, "low_comp_references.json")
    for k, v in LR.items(): T.append("| %s (reference) | %.3f | %.3f | %.3f | %.4f |" % (k, v["hip_over_thorax"], v["waist_over_thorax"], v["waist_over_hip"], v["waist_rise"]))
    for k, v in b["low_comp"].items(): T.append("| GO %s low composition | %.3f | %.3f | %.3f | %.4f |" % ("reference" if not k.endswith("208") else "true 208 cm", v["hip_over_thorax"], v["waist_over_thorax"], v["waist_over_hip"], v["waist_rise"]))
    T += ["", "### Skeleton (minimum composition)", "", "| Body | hip / thorax | waist / thorax | waist / hip | d2 b | d2 d |", "|---|---|---|---|---|---|"]
    SKB = jl(EV, "skb_continuity.json")
    for k, c in (("GO reference skeleton", b["skeleton"]), ("GO true 208 cm skeleton", b["skeleton_208"])) + tuple((k, v) for k, v in SKB.items() if "skeleton" in k):
        T.append("| %s | %.3f | %.3f | %.3f | %.4f | %.4f |" % (k, c["hip_over_thorax"], c["waist_over_thorax"], c["waist_over_hip"], c["d2b"], c["d2d"]))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written")

if __name__ == "__main__":
    main()
