"""Generate the RAC W2C1 (joint normalization) evidence tables from reviews/rac-w2c1-joint-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2c1-joint-evidence")
def main():
    J = json.load(open(os.path.join(EV, "joint_sections.json"))); K = json.load(open(os.path.join(EV, "knee_normalization.json"))); E = json.load(open(os.path.join(EV, "elbow_wrist_ankle_check.json")))
    T = ["# RAC W2C1 — joint-breadth normalization: evidence tables", "", "Generated by `tools/rac/w1/gen_w2c1_docs.py`. Section = exact plane through the joint centre (`w2c1_drivers/joint_section.py`); slab = the accepted stature-scaled slab. Values are breadth ÷ R-6 stature.", "",
         "## Joint breadths, slab vs section", "", "| Body | stature | elbow slab / section | wrist slab / section | knee slab / section | ankle slab / section |", "|---|---|---|---|---|---|"]
    for n, r in J.items():
        T.append("| %s | %.1f | %s |" % (n, r["stature"], " | ".join("%.4f / %.4f (%.3f)" % (r["slab_scaled"][j], r["section"][j], r["slab_scaled"][j] / r["section"][j]) for j in ("elbow", "wrist", "knee", "ankle"))))
    T += ["", "## Normalized knee trends (section only; uncorrected bodies; the slab-derived 0.575 slope is not used)", "", "| Population | bodies | slope (share) | absolute exponent | max residual |", "|---|---|---|---|---|"]
    for p, f in K["fits"].items(): T.append("| %s | %s | %+.3f | %.3f | %.1f %% |" % (p, ", ".join(f["bodies"]), f["slope_share"], f["exponent_absolute"], f["max_abs_residual_pct"]))
    T += ["", "## Questioned knee corrections (leave-one-out expectation)", "", "| Correction | fit bodies | expected | uncorrected | corrected | verdict |", "|---|---|---|---|---|---|"]
    for n, v in K["corrections"].items():
        T.append("| %s | %s | %.4f | %s %.4f (%+.1f %%) | %s %.4f (%+.1f %%) | %s |" % (n, ", ".join(v["fit_bodies (leave-one-out)"]), v["expected_knee"], v["uncorrected"], v["uncorrected_knee"], v["uncorrected_residual_pct"], v["corrected"], v["corrected_knee"], v["corrected_residual_pct"], v["verdict"]))
    T += ["", "## Accepted knee decisions re-checked (section; reverted bodies where the verdict is revert)", "", "| Check | A | value | op | B | value | margin | result |", "|---|---|---|---|---|---|---|---|"]
    for r in K["rechecks"]: T.append("| %s | %s | %.4f | %s | %s | %.4f | %+.1f %% | %s |" % (r["check"], r["a"], r["va"], r["op"], r["b"], r["vb"], r["margin_pct"], r["result"]))
    T += ["", "## Elbow / wrist / ankle: accepted comparisons, slab vs section margins", "", "| Pair | joint | slab margin | section margin | class change |", "|---|---|---|---|---|"]
    for r in E["pairs"]: T.append("| %s (%s vs %s) | %s | %+.1f %% | %+.1f %% | %s |" % (r["pair"], r["a"], r["b"], r["joint"], r["slab_margin_pct"], r["section_margin_pct"], "yes" if r["ordering_or_1pct_class_changes"] else ""))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
