"""Generate the RAC W1r (Cogling W1 acceptance gate) evidence tables from the JSON in reviews/rac-w1r-cg-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w1r-cg-evidence")
jl = lambda *p: json.load(open(os.path.join(*p)))
def res(r): return r.get("result") or r.get("result_ADG10") or ("PASS" if r.get("pass") else "FAIL")
def fv(v):
    if isinstance(v, (list, tuple)): return " / ".join("%.4f" % x if isinstance(x, (int, float)) else str(x) for x in v)
    return "%.4f" % v if isinstance(v, (int, float)) else str(v)
def margin(r):
    va, vb, op = r.get("va"), r.get("vb"), r.get("op", "")
    if not isinstance(va, (int, float)) or not isinstance(vb, (int, float)) or op not in (">", "<", ">=", "<=", "~"): return "—"
    if op == "~": return "%+.4f" % (va - vb)
    return "%+.2f %%" % (100 * (va - vb) / abs(vb) * (1 if op in (">", ">=") else -1))
def rows_md(rows):
    T = ["| Check | Canon | Value | Op | Comparator | Margin | Result |", "|---|---|---|---|---|---|---|"]
    for r in rows: T.append("| %s | %s | %s | %s | %s %s | %s | %s |" % (r.get("check"), r.get("canon", ""), fv(r.get("va")), r.get("op"), r.get("b", ""), fv(r.get("vb")), margin(r), res(r) if res(r) in ("PASS", "REPORT") else "**%s**" % res(r)))
    return T
def skel_md(rows):
    T = ["| Check | Canon | t = 0 (CG / comparator) | t = 0.5 | t = 1.0 | Comparator | Result |", "|---|---|---|---|---|---|---|"]
    for r in rows: T.append("| %s | %s | %s | %s | %s | %s | %s |" % (r["check"], r["canon"], *("%.4f / %.4f" % tuple(r["by_t"][t]) for t in ("0.0", "0.5", "1.0")), r["b"], r["result"] if r["result"] in ("PASS", "REPORT") else "**%s**" % r["result"]))
    return T
NAMES = {"W1g": "CG as built (CG-NAT)", "W1r_CGJ5": "Probe CGJ5 (arms + ankle only)", "W1r_CGJ7": "CG W1r candidate CGJ7", "NARROWB": "CGJ7 Narrow, breadth-only write",
         "BROADB_P112": "CGJ7 Broad, breadth-only, pelvis x1.12", "LOW_same_composition": "CGJ7 low 0.25 / 0.25 vs MF-M-R-LOW / PK-LOW (same composition)",
         "COMP_LOWMUS": "CGJ7 low muscle 0 / 0.5", "COMP_HIMUS": "CGJ7 high muscle 1 / 0.5", "COMP_HIFAT": "CGJ7 higher fat 0.5 / 1", "COMP_HIBOTH": "CGJ7 high muscle + fat 1 / 1"}
SKN = {"W1g": "BASE", "W1r_CGJ5": "CGJ5", "W1r_CGJ7": "CGJ7", "NARROWB": "NARROWB", "BROADB_P112": "BROADB_P112"}
J = ("elbow", "wrist", "knee", "ankle")
def main():
    T = ["# RAC W1r — Cogling W1 acceptance gate: evidence tables", "", "Generated by `tools/rac/w1/gen_w1r_docs.py` from the JSON in this folder. Nothing here is canon. Rule: AD-G10 (strict rows must clear 1 %; non-strict rows missing by < 1 % are MARGINAL; ≈ means ±0.010). Comparators: accepted MF-M-R, SK, SG, Aelari (AEL1), Vael (VAL4), Fenn (FNL4), Gorrund, Grask (W1l), Pipkin (PK-NAT); Durrim (DU-NAT) as built = UNACCEPTED dependency; a 91 cm generator human-child proxy (age ~3 y) as diagnostic. Skeletal rows: CIB stations on the W1i skeletal base. Joint rows: joint breadth / stature with the measurement slab scaled with stature (see §1).", ""]
    JB = jl(EV, "joint_breadths.json"); JL = jl(EV, "joint_breadths_lean.json"); JW = jl(EV, "joint_breadths_low.json")
    T += ["## 1. Joint breadth / stature: fixed 1 cm slab (as measured) vs slab scaled with stature", "", "arm_measure takes each joint breadth inside a fixed ±1 cm slab. At 91 cm that slab samples about 1.9 times more of the limb, relative to stature, than at MF stature. The scaled reading uses a slab of 1 cm × stature / 173.14 (MF unchanged).", "",
          "| Set | Body | Stature | elbow abs | wrist abs | knee abs | ankle abs | elbow scaled | wrist scaled | knee scaled | ankle scaled |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for nm, src in (("reference composition", JB), ("minimum composition (muscle 0 / weight 0)", JL), ("low composition 0.25 / 0.25", JW)):
        for k, v in src.items(): T.append("| %s | %s | %.2f | %s | %s |" % (nm, {"MF-M-R": "MF-M-R-LOW", "PK-NAT": "PK-LOW", "DU-NAT": "DU-NAT (reference composition; no DU low body)"}.get(k, k) if src is JW else k, v["stature"], " | ".join("%.4f" % v["abs"][j] for j in J), " | ".join("%.4f" % v["scaled"][j] for j in J)))
    C = {t: jl(EV, "central_%s.json" % t) for t in NAMES if os.path.exists(os.path.join(EV, "central_%s.json" % t))}
    sc = lambda c: [r for r in c["added"] if r["result"] != "REPORT"]
    T += ["", "## 2. Scored rows across bodies", "", "| Body | rows | not PASS |", "|---|---|---|"]
    for t, c in C.items():
        bad = [r for r in sc(c) + c["directional"] if res(r) not in ("PASS", "REPORT")]
        T.append("| %s | %d added + %d directional | %s |" % (NAMES[t], len(sc(c)), len(c["directional"]), "; ".join("%s → %s" % (r["check"], res(r)) for r in bad) or "none"))
    D = C["W1r_CGJ7"]["distribution"]
    T += ["", "## 3. Proportion distribution (shares of stature; CG = CGJ7 central)", "", "| Reading | " + " | ".join(D) + " |", "|---|" + "---|" * len(D)]
    for k in D["CG"]: T.append("| %s | %s |" % (k, " | ".join("%.4f" % D[b][k] for b in D)))
    for i, t in enumerate(C):
        c = C[t]; T += ["", "## 4.%d %s" % (i + 1, NAMES[t]), ""]
        if t in SKN and os.path.exists(os.path.join(EV, "skeletal_%s.json" % SKN[t])):
            s = jl(EV, "skeletal_%s.json" % SKN[t]); T += ["### skeletal (CIB; %d rows: %d not PASS)" % (len(s), sum(res(r) not in ("PASS", "REPORT") for r in s)), ""] + skel_md(s) + [""]
        note = " — scored against REFERENCE-composition comparators, not like for like" if t.startswith("COMP_") else ""
        for L in ("added", "directional"):
            T += ["### %s (%d rows: %d not PASS)%s" % (L, len(c[L]), sum(res(r) not in ("PASS", "REPORT") for r in c[L]), note), ""] + rows_md(c[L]) + [""]
    P = jl(EV, "composition.json")
    T += ["## 5. Trunk continuity readings", "", "| Body | hip / thorax | waist / thorax | waist / hip | d2b | waist rise |", "|---|---|---|---|---|---|"]
    for k, v in P["continuity"].items(): T.append("| %s | %.3f | %.3f | %.3f | %.4f | %.3f |" % (k, v["hip_over_thorax"], v["waist_over_thorax"], v["waist_over_hip"], v["d2b"], v["waist_rise"]))
    SEP = jl(EV, "separation.json")
    T += ["", "## 6. Separation: % difference of CG (CGJ7) from each body (report only; DU unaccepted; child proxy diagnostic)", "", "Statures: " + ", ".join("%s %.1f cm" % (k, v) for k, v in SEP["stature"].items()) + ".", "", "| Reading | " + " | ".join(SEP["pct_CG_vs"]) + " |", "|---|" + "---|" * len(SEP["pct_CG_vs"])]
    for k in next(iter(SEP["pct_CG_vs"].values())): T.append("| %s | %s |" % (k, " | ".join("%+.1f %%" % SEP["pct_CG_vs"][b][k] for b in SEP["pct_CG_vs"])))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
