"""Generate the RAC W1q (Pipkin W1 acceptance gate) evidence tables from the JSON in reviews/rac-w1q-pk-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w1q-pk-evidence")
jl = lambda *p: json.load(open(os.path.join(*p)))
def res(r): return r.get("result") or r.get("result_ADG10") or ("PASS" if r.get("pass") else "FAIL")
def fv(v):
    if isinstance(v, (list, tuple)): return " / ".join("%.4f" % x if isinstance(x, (int, float)) else str(x) for x in v)
    return "%.4f" % v if isinstance(v, (int, float)) else str(v)
def margin(r):
    va, vb, op = r.get("va"), r.get("vb"), r.get("op", "")
    if not isinstance(va, (int, float)) or not isinstance(vb, (int, float)) or op not in (">", "<", ">=", "<="): return "—"
    return "%+.2f %%" % (100 * (va - vb) / abs(vb) * (1 if op in (">", ">=") else -1))
def rows_md(rows):
    T = ["| Cand | Check | Value | Op | Comparator | Margin | Result |", "|---|---|---|---|---|---|---|"]
    for r in rows: T.append("| %s | %s | %s | %s | %s %s | %s | %s |" % (r.get("cand"), r.get("check"), fv(r.get("va")), r.get("op"), r.get("b", ""), fv(r.get("vb")), margin(r), res(r) if res(r) in ("PASS", "REPORT") else "**%s**" % res(r)))
    return T
NAMES = {"W1g": "PK central (PK-NAT as built)", "NARROWB": "PK Narrow, breadth-only write", "BROADB_P112": "PK Broad, breadth-only, pelvis x1.12", "BROAD_vs_NARROW_DU": "PK Broad vs diagnostic Narrow Durrim",
         "LOWMUS": "PK low muscle 0 / 0.5", "HIMUS": "PK high muscle 1 / 0.5", "HIFAT": "PK higher fat 0.5 / 1", "HIBOTH": "PK high muscle + fat 1 / 1", "LOW": "PK low composition 0.25 / 0.25"}
def main():
    T = ["# RAC W1q — Pipkin W1 acceptance gate: evidence tables", "", "Generated by `tools/rac/w1/gen_w1q_docs.py` from the JSON in this folder. Nothing here is canon. Rule: AD-G10; balance rows ≈ MF ±0.010 (the convention accepted for Aelari); BM-3 accepts NOT DEMONSTRATED within 1 % for MF < VA < AE. Comparators: accepted MF-M-R, SK, SG, Aelari, Vael, Fenn, Gorrund, Grask; Durrim (DU-NAT) and Cogling (CG-NAT) as built — UNACCEPTED dependencies; a generator human-child proxy (107 cm, age ~6 y) and a breadth-only Narrow Durrim as diagnostics. Skeletal rows: CIB (W1h method) on the W1i skeletal base. Skin rows and joint readings: composition-inclusive measurement layer.", ""]
    C = {t: jl(EV, "central_%s.json" % t) for t in NAMES if os.path.exists(os.path.join(EV, "central_%s.json" % t))}
    T += ["## 1. Added canon-derived rows across bodies (PIPKIN L42, L68, L149, L161–167, L183–189; SRR SR-COMP-01…03, -11; order rows)", "", "| Body | " + " | ".join(r["check"][:38] for r in C["W1g"]["added"] if r["result"] != "REPORT") + " |", "|---|" + "---|" * sum(r["result"] != "REPORT" for r in C["W1g"]["added"])]
    for t, c in C.items(): T.append("| %s | %s |" % (NAMES[t], " | ".join(("%.4f %s" % (r["va"], r["result"] if r["result"] == "PASS" else "**%s**" % r["result"])) for r in c["added"] if r["result"] != "REPORT")))
    T += ["", "## 2. Proportion distribution (shares of stature)", "", "| Reading | PK central | PK low 0.25 / 0.25 | MF-M-R | DU | CG | SG | SK |", "|---|---|---|---|---|---|---|---|"]
    D0, D1 = C["W1g"]["distribution"], C["LOW"]["distribution"]
    for k in D0["PK"]: T.append("| %s | %.4f | %.4f | %s |" % (k, D0["PK"][k], D1["PK"][k], " | ".join("%.4f" % D0[b][k] for b in ("MF-M-R", "DU", "CG", "SG", "SK"))))
    for i, t in enumerate(C):
        c = C[t]; T += ["", "## 3.%d %s" % (i + 1, NAMES[t]), ""]
        sp = os.path.join(EV, "skeletal_%s.json" % {"BROAD_vs_NARROW_DU": "BROADB_P112_vs_NARROW_DU"}.get(t, t))
        if os.path.exists(sp):
            s = jl(sp); T += ["### skeletal (CIB; %d rows: %d not PASS)" % (len(s), sum(res(r) not in ("PASS", "REPORT") for r in s)), ""] + rows_md(s) + [""]
        for L in ("added", "skin", "directional"):
            T += ["### %s (%d rows: %d not PASS)%s" % (L, len(c[L]), sum(res(r) not in ("PASS", "REPORT") for r in c[L]), " — scored against REFERENCE-composition comparators, not like for like" if t in ("LOWMUS", "HIMUS", "HIFAT", "HIBOTH", "LOW") else ""), ""] + rows_md(c[L]) + [""]
    P = jl(EV, "composition.json")
    T += ["## 4. Low composition at the SAME composition (PK low vs MF-M-R-LOW / SK-LOW)", ""] + rows_md(P["low_same_composition_skin"])
    T += ["", "## 5. Trunk continuity readings", "", "| Body | hip / thorax | waist / thorax | waist / hip | d2b | waist rise |", "|---|---|---|---|---|---|"]
    for k, v in P["continuity"].items(): T.append("| %s | %.3f | %.3f | %.3f | %.4f | %.3f |" % (k, v["hip_over_thorax"], v["waist_over_thorax"], v["waist_over_hip"], v["d2b"], v["waist_rise"]))
    SEP = jl(EV, "separation.json")
    T += ["", "## 6. Separation: % difference of PK from each body (report only; DU / CG unaccepted; child proxy diagnostic)", "", "Statures: " + ", ".join("%s %.1f cm" % (k, v) for k, v in SEP["stature"].items()) + ".", "", "| Reading | " + " | ".join(SEP["pct_PK_vs"]) + " |", "|---|" + "---|" * len(SEP["pct_PK_vs"])]
    for k in next(iter(SEP["pct_PK_vs"].values())): T.append("| %s | %s |" % (k, " | ".join("%+.1f %%" % SEP["pct_PK_vs"][b][k] for b in SEP["pct_PK_vs"])))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written")
if __name__ == "__main__": main()
