"""Generate the RAC S7 normalization evidence tables from reviews/rac-s7n-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-s7n-evidence")
def main():
    V = json.load(open(os.path.join(EV, "s7_values.json"))); D = json.load(open(os.path.join(EV, "status_diff.json")))
    T = ["# RAC S7 normalization — evidence tables", "", "Generated by `tools/rac/w1/gen_s7n_docs.py`. S7 = femoral subtrochanteric section (20 % down the hip-knee axis), composition infimum (CIB).",
         "Old = ±0.8 cm vertex slab (control: recomputed on the same grid bodies, reproduces every recorded S7 to 0.01 cm). New = exact plane section (author ruling 2026-10-07).", "",
         "## Baseline reproduction (evaluations re-run unchanged on the old inputs)", "", "```", open(os.path.join(EV, "baseline_reproduction.txt")).read().rstrip(), "```", "",
         "## Evaluation rows", "", "| Evidence file | rows | rows with changed values | status changes |", "|---|---|---|---|"]
    for rel, r in D.items(): T.append("| `%s` | %d | %d | %d |" % (rel.replace("reviews/", ""), r["rows"], r["rows_with_changed_values"], len(r["status_changes"])))
    T += ["", "## Status changes (all)", "", "| Evidence file | Row | Old | New |", "|---|---|---|---|"]
    for rel, r in D.items():
        for c in r["status_changes"]: T.append("| `%s` | %s | %s | %s |" % (rel.replace("reviews/", ""), c["row"], c["old"], c["new"]))
    T += ["", "## S7 per SKP body (composition infimum, cm; t = 0 share of stature)", "", "| SKP copy / body | stature | old b / d (cm) | new b / d (cm) | change b / d | old t0 share b / d | new t0 share b / d | grid n | control |", "|---|---|---|---|---|---|---|---|---|"]
    for k, v in V.items():
        T.append("| %s | %.1f | %.2f / %.2f | %.2f / %.2f | %+.1f / %+.1f %% | %.4f / %.4f | %.4f / %.4f | %d | %s |" % (k, v["stature_cm"], *v["bony_vertex_cm"], *v["bony_section_cm"], *v["change_pct"], *v["t0_share_vertex"], *v["t0_share_section"], v["n_grid"], "reproduces" if v["control_reproduces_old"] else "**MISMATCH**"))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
