"""Generate the RAC W2H (short-race family) evidence tables from reviews/rac-w2h-sr-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2h-sr-evidence")
f4 = lambda v: "%.4f" % v if isinstance(v, float) else ("—" if v is None else str(v))
GROUPS = [("Durrim family (native route; DU137 = accepted DU-NAT)", ["DU122", "DU137", "DU152"]),
          ("Pipkin family (native route; PK107 = accepted PK-NAT)", ["PK91", "PK107", "PK122"]),
          ("Cogling family (native route; CG91 = accepted CGJ7)", ["CG76", "CG91", "CG107"]),
          ("Real-height overlaps", ["PK122", "DU122", "PKB122", "DUN122", "CG91", "PK91", "CG107", "PK107"]),
          ("Durrim 152 cm equal-height boundary", ["DU152", "MF152", "MF152s7n", "SG152"]),
          ("Normalized comparators", ["MF173", "FN181", "GR218"]),
          ("Frames: Durrim (Broad pelvis x1.08)", ["DUN122", "DUB122", "DUN137", "DUB137", "DUN152", "DUB152"]),
          ("Frames: Pipkin (Broad pelvis x1.12)", ["PKN91", "PKB91", "PKN107", "PKB107", "PKN122", "PKB122"]),
          ("Frames: Cogling (Broad pelvis x1.12)", ["CGN76", "CGB76", "CGN91", "CGB91", "CGN107", "CGB107"]),
          ("Composition at the references", ["DU137-LOWMUS", "DU137-HIMUS", "DU137-HIFAT", "DU137-HIBOTH", "DU137-LOW", "DU137-MIN", "PK107-LOWMUS", "PK107-HIMUS", "PK107-HIFAT", "PK107-HIBOTH", "PK107-LOW", "PK107-MIN",
                                             "CG91-LOWMUS", "CG91-HIMUS", "CG91-HIFAT", "CG91-HIBOTH", "CG91-LOW", "CG91-MIN"]),
          ("Marchfolk 173 composition states (normalized comparators)", ["MF173-LOWMUS", "MF173-HIMUS", "MF173-HIFAT", "MF173-HIBOTH", "MF173-LOW", "MF173-MIN"]),
          ("Named validators", ["COG04", "COG05", "COG12", "COG13", "PKBHM", "DUNLOW"]),
          ("DU-P4 composition at 152 cm", ["DU152-LOW", "MF152-LOW", "DU152-MIN", "MF152-MIN", "DU152-HIBOTH", "MF152-HIBOTH"]),
          ("Generator human-child proxies (diagnostic only)", ["CHILD1", "CHILD3", "CHILD6", "CHILD9"]),
          ("Route reproduction", ["DU137R", "PK107R", "CG91R"])]
CODES = {"U": "head height / allometry", "C": "continuity per family", "O": "real-height overlaps and Cogling-Durrim context", "P": "body-only collision (complete package)",
         "D": "Durrim 152 cm boundary (DU-P2...P6, RM-SR-06)", "P4": "DU-P4 closure", "R": "RM-SR-01 Pipkin trunk / pelvis (normalized)", "Q": "RM-SR-02 Cogling segment distribution (normalized)",
         "A": "RM-SR-03 structural-mass axis", "F": "frames", "M": "composition firewall", "K": "RM-SR-04 adult read (child proxies; report)", "S5": "RM-SR-05 craniofacial depth proxies (report)",
         "Z": "route reproduction", "G": "accepted W1 rows per body (normalized: fixed W1 references)"}
def main():
    src = os.environ.get("W2H_JSON", "w2h.json"); out = os.environ.get("W2H_TABLES", "tables.md")     # closure: W2F_JSON=closure/w2f_closure.json W2H_TABLES=closure/tables_closure.md
    d = json.load(open(os.path.join(EV, src))); V = d["values"]
    T = ["# RAC W2H — Short-race family (Durrim / Pipkin / Cogling): evidence tables", "", "Generated by `tools/rac/w1/gen_w2h_docs.py`. NON-CANON diagnostics. Skeletal: CIB grids, exact-plane S7 (t = 0 shown in the value tables; rows sweep t = 0 / 0.5 / 1). "
         "Joints: exact-plane section (REFERENCE_ANATOMY_V1 §10). Rule: AD-G10. Real matched height only where adult ranges overlap; everything else is a NORMALIZED (ratio) diagnostic against Marchfolk 173, never a same-height Marchfolk adult.", ""]
    for title, cols in GROUPS:
        cols = [c for c in cols if c in V]
        keys = []
        for c in cols: keys += [k for k in V[c] if k not in keys and "[t=0.5]" not in k and "[t=1.0]" not in k]
        T += ["## %s" % title, "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for k in keys: T.append("| %s | %s |" % (k, " | ".join(f4(V[c].get(k)) for c in cols)))
        T.append("")
    T += ["## Checks", ""]
    for code, name in CODES.items():
        cc = [c for c in d["checks"] if c["code"] == code]
        if not cc: continue
        T += ["### %s — %s (%d; not PASS / REPORT: %d)" % (code, name, len(cc), sum(c["result"] not in ("PASS", "OVERSHOOT") and not c["result"].startswith("REPORT") for c in cc) + sum(c["result"] == "OVERSHOOT" for c in cc)), "",
              "| Check | A | Value | Op | B | Value | Margin | Result | Note |", "|---|---|---|---|---|---|---|---|---|"]
        for c in cc:
            va = " / ".join("%.4f" % x for x in c["va"]) if isinstance(c["va"], list) else f4(c["va"])
            vb = " / ".join("%.4f" % x for x in c["vb"]) if isinstance(c["vb"], list) else f4(c["vb"])
            T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (c["check"], c["a"], va, c["op"], c["b"], vb, ("%+.2f %%" % c["margin_pct"]) if isinstance(c.get("margin_pct"), float) else "",
                                                                c["result"] if c["result"] == "PASS" or c["result"].startswith("REPORT") else "**%s**" % c["result"], str(c.get("note", "")).replace("|", "/")))
        T.append("")
    T += ["## Accepted W1 rows per body (not PASS only; fixed W1 references)", "", "| Body | Layer | Row | Result | Value | Reference |", "|---|---|---|---|---|---|"]
    for b, rows in d["canonical_rows"].items():
        if not b[:2] in ("DU", "PK", "CG", "CO"): continue
        for x in rows:
            if x["result"] != "PASS": T.append("| %s | %s | %s | %s | %s | %s |" % (b, x["layer"], x["check"], x["result"], f4(x.get("va")), f4(x.get("vb"))))
    open(os.path.join(EV, out), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
