"""Generate the RAC W1o (Vael Broad-frame correction) evidence tables from reviews/rac-w1o-va-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w1o-va-evidence")
jl = lambda *p: json.load(open(os.path.join(*p)))
def res(r): return r.get("result") or r.get("result_ADG10") or ("PASS" if r.get("pass") else "FAIL")
def fv(v):
    if isinstance(v, (list, tuple)): return " / ".join("%.4f" % x if isinstance(x, (int, float)) else str(x) for x in v)
    return "%.4f" % v if isinstance(v, (int, float)) else str(v)
def margin(r):
    va, vb, op = r.get("va"), r.get("vb"), r.get("op", "")
    if isinstance(va, list): va = min(va) if op in (">", ">=") else max(va)
    if isinstance(vb, list): vb = max(vb) if op in (">", ">=") else min(vb)
    if not isinstance(va, (int, float)) or not isinstance(vb, (int, float)) or op not in (">", "<", ">=", "<="): return "—"
    return "%+.2f %%" % (100 * (va - vb) / abs(vb) * (1 if op in (">", ">=") else -1))
def rows_md(rows):
    T = ["| Cand | Check | Value | Op | Comparator | Margin (worst t) | Result |", "|---|---|---|---|---|---|---|"]
    for r in rows: T.append("| %s | %s | %s | %s | %s %s | %s | %s |" % (r.get("cand"), r.get("check"), fv(r.get("va")), r.get("op"), r.get("b", ""), fv(r.get("vb")), margin(r), res(r) if res(r) in ("PASS", "REPORT") else "**%s**" % res(r)))
    return T
B = {"VAL4": "VAL4 central (accepted)", "BROADB": "Broad breadth-only W1n (pelvis x1.08)", "BROADB_P112": "Broad W1o (pelvis x1.12) — CHOSEN", "BROADB_P114": "Broad probe pelvis x1.14", "BROADB_P116": "Broad probe pelvis x1.16"}
def main():
    T = ["# RAC W1o — Vael Broad-frame correction: evidence tables", "", "Generated by `tools/rac/w1/gen_w1o_docs.py`. Nothing here is canon. Same rules and comparators as W1n (`reviews/rac-w1n-va-evidence/tables.md`). Broad = breadth-only write (+8 % clavicle, spine_01–03 X) with the pelvis X factor shown (the pelvis carries the hip joints); limb lengths, thoracic depth, joint robusticity, head and tissue unchanged.", ""]
    T += ["## 1. E-A2 and continuity across the Broad candidates", "", "| Body | E-A2 bitrochanteric ÷ crest (skeletal, worst t) vs MF | Result | hip ÷ thorax | waist ÷ hip | waist rise |", "|---|---|---|---|---|---|"]
    C = jl(EV, "continuity.json"); ck = {"VAL4": "VA VAL4 central", "BROADB": "VA Broad breadth-only (W1n, pelvis x1.08)", "BROADB_P112": "VA Broad W1o pelvis x1.12", "BROADB_P114": "VA Broad W1o pelvis x1.14", "BROADB_P116": "VA Broad W1o pelvis x1.16"}
    for t, n in B.items():
        s = jl(EV, "skeletal_%s.json" % t); e = [r for r in s if "bitroch" in r["check"]][0]; c = C[ck[t]]
        T.append("| %s | %s vs %s (%s) | %s | %.3f | %.3f | %.3f |" % (n, fv(e["va"]), fv(e["vb"]), margin(e), res(e), c["hip_over_thorax"], c["waist_over_hip"], c["waist_rise"]))
    for k in ("VA Narrow breadth-only", "MF-M-R", "AE AEL1 (accepted)", "FN (W1g)"):
        c = C[k]; T.append("| %s (reference) | — | — | %.3f | %.3f | %.3f |" % (k, c["hip_over_thorax"], c["waist_over_hip"], c["waist_rise"]))
    for t, n in B.items():
        T += ["", "## %s" % n, ""]
        s = jl(EV, "skeletal_%s.json" % t); T += ["### skeletal (%d rows: %d not PASS)" % (len(s), sum(res(r) not in ("PASS", "REPORT") for r in s)), ""] + rows_md(s)
        c = jl(EV, "central_%s.json" % t)
        for L in ("added", "skin", "directional"): T += ["", "### %s (%d rows: %d not PASS)" % (L, len(c[L]), sum(res(r) not in ("PASS", "REPORT") for r in c[L])), ""] + rows_md(c[L])
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written")
if __name__ == "__main__": main()
