"""Generate the RAC W2B1 (Skarn 229 cm bounded correction) evidence tables from the JSON in reviews/rac-w2b1-sk-evidence (no hand-typed numbers)."""
import json, os, collections
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2b1-sk-evidence")
W2B = os.path.join(R, "reviews", "rac-w2b-sk-evidence", "w2b.json")
f4 = lambda v: " / ".join("%.4f" % x for x in v) if isinstance(v, list) else ("%.4f" % v if isinstance(v, float) else str(v))
def main():
    P = json.load(open(os.path.join(EV, "probes.json"))); O = json.load(open(W2B)); B = json.load(open(os.path.join(EV, "w2b1.json"))); C = json.load(open(os.path.join(EV, "w2b1_s7_candidate.json")))
    S7 = json.load(open(os.path.join(EV, "s7_section.json"))); BP = json.load(open(os.path.join(EV, "s7_band_probe.json")))
    T = ["# RAC W2B1 — Skarn 229 cm bounded correction: evidence tables", "", "Generated by `tools/rac/w1/gen_w2b1_docs.py`. NON-CANON diagnostics.", "",
         "## Construction", "", "```json", json.dumps(json.load(open(os.path.join(EV, "construction.json"))), indent=1), "```", "",
         "## Configuration 1 · 229 cm knee probes (allometric expectation from the 208 cm anchor %.4f)" % P["knee_probes_config1_229"]["allometric_expectation_from_208"], "",
         "| Body | Write | knee / stature | vs slope | elbow | wrist | ankle |", "|---|---|---|---|---|---|---|"]
    for r in P["knee_probes_config1_229"]["rows"]:
        T.append("| %s | %s | %.4f | %+.1f %% | %.4f | %.4f | %.4f |" % (r["body"], r["write"], r["knee_over_stature"], r["vs_allometric_expectation_pct"], r["elbow"], r["wrist"], r["ankle"]))
    T += ["", "## Configuration 2 · 229 cm S7 probes (accepted vertex-slab CIB reading)", "", "| Probe | Write | torso | leg | femur / leg | arm | S7 depth / stature (vertex slab) | S7 skin depth / stature |", "|---|---|---|---|---|---|---|---|"]
    for r in P["s7_probes_config2_229"]:
        T.append("| %s | %s | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f |" % (r["probe"], r["write"], r["torso"], r["leg"], r["femur_over_leg"], r["arm"], r["S7_depth_vertex_slab_over_stature"], r["S7_skin_depth_over_stature"]))
    T += ["", "## S7 slab-band sensitivity on the minimum-composition body (depth, cm; vertices in the slab)", "", "| Body | " + " | ".join(k.split(" ", 1)[1] for k in next(iter(BP.values()))) + " |", "|---|" + "---|" * 6]
    for n, v in BP.items(): T.append("| %s | %s |" % (n, " | ".join("%.2f (%d)" % (x["depth"], x["n_vertices"]) for x in v.values())))
    T += ["", "## S7 composition infimum: accepted vertex slab vs CANDIDATE exact plane section (cm)", "", "| Body | vertex slab b / d | section b / d | argmin (section depth) |", "|---|---|---|---|"]
    for n, r in S7.items(): T.append("| %s | %.2f / %.2f | %.2f / %.2f | %s |" % (n, r["vertex_slab"][0], r["vertex_slab"][1], r["section"][0], r["section"][1], r["section_argmin"][1]))
    key = lambda c: (c["code"], c["check"]); ob = {key(c): c for c in O["checks"]}
    for title, X in (("W2B1 (accepted S7 reading)", B), ("W2B1 with the CANDIDATE S7 section reading", C)):
        cnt = collections.Counter("PASS" if c["result"] == "PASS" else ("REPORT" if c["result"].startswith("REPORT") else c["result"]) for c in X["checks"])
        T += ["", "## Checks — %s: %d checks; %s" % (title, len(X["checks"]), ", ".join("%s %d" % kv for kv in sorted(cnt.items()))), "", "| Code | Check | W2B result | W2B1 result | W2B note | W2B1 note |", "|---|---|---|---|---|---|"]
        for c in X["checks"]:
            o = ob[key(c)]
            if c["va"] != o["va"] or c["vb"] != o["vb"] or c["result"] != o["result"]:
                T.append("| %s | %s | %s | %s | %s | %s |" % (c["code"], c["check"], o["result"], c["result"] if c["result"] in ("PASS", "REPORT") else "**%s**" % c["result"], o["note"], c["note"]))
        T.append("")
        T.append("Rows not listed are identical to W2B (values and results).")
    T += ["", "## Diagnostic envelope candidates after W2B1 (NON-CANON)", "", "| Reading | min | body | max | body |", "|---|---|---|---|---|"]
    for k, e in B["envelope_candidates"].items():
        if "[t=0.5]" in k or "[t=1.0]" in k: continue
        T.append("| %s | %.4f | %s | %.4f | %s |" % (k, e["min"], e["min_body"], e["max"], e["max_body"]))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
