"""Generate the RAC W2F (Elf family W2) evidence tables from reviews/rac-w2f-elf-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2f-elf-evidence")
f4 = lambda v: "%.4f" % v if isinstance(v, float) else ("—" if v is None else str(v))
GROUPS = [("Fenn stature family", ["FN157", "FN163", "FN173", "FN178", "FN181", "FN190", "FN203", "FN211"]),
          ("Aelari stature family", ["AE168", "AE173", "AE178", "AE181", "AE190", "AE203", "AE211", "AE221"]),
          ("Vael stature family", ["VA157", "VA163", "VA173", "VA178", "VA181", "VA190", "VA203"]),
          ("Human comparators (Marchfolk, Sagekin) and Skarn guard", ["MF157", "MF163", "MF168", "MF173", "MF178", "MF181", "MF190", "MF203", "SG173", "SG178", "SG181", "SG190", "SG203", "SK190", "SK203", "SK208", "SK229"]),
          ("Frames (accepted elf breadth-only rule)", ["FNN157", "FNB157", "FNN181", "FNB181", "FNN211", "FNB211", "AEN168", "AEB168", "AEN190", "AEB190", "AEN221", "AEB221", "VAN157", "VAB157", "VAN178", "VAB178", "VAN203", "VAB203"]),
          ("Named validators and probes", ["FN15", "FN16", "FN09", "FN09x75", "FN08", "AE19", "AE20", "AE11", "AE24", "VA09", "VA10", "VA23", "VA24", "AEP175_190", "AEP200_190", "AEP250_190", "VAP0_190", "AE168N", "AE173N", "FN163N", "VA163N"]),
          ("Composition at 173 cm", ["FN173-LOWMUS", "FN173-HIMUS", "FN173-HIFAT", "FN173-HIBOTH", "FN173-LOW", "FN173-MIN", "AE173-LOWMUS", "AE173-HIMUS", "AE173-HIFAT", "AE173-HIBOTH", "AE173-LOW", "AE173-MIN",
                                     "VA173-LOWMUS", "VA173-HIMUS", "VA173-HIFAT", "VA173-HIBOTH", "VA173-LOW", "VA173-MIN", "MF-LOWMUS", "MF-HIMUS", "MF-HIFAT", "MF-HIBOTH", "MF-LOW", "MF-MIN"]),
          ("Frame x composition validators at the references", ["FN-NLOW", "FN-BHM", "FN-NHM", "FN-BHF", "FN-HF", "AE-NLOW", "AE-BHM", "AE-NHM", "AE-BHF", "AE-HF", "VA-NLOW", "VA-BHM", "VA-NHM", "VA-BHF", "VA-HF"])]
CODES = {"U": "allometry", "C": "continuity per population", "G": "accepted W1 rows per body (fixed W1 references)", "R": "RM-OT-02 family matrix at matched height",
         "H": "each population vs Marchfolk at matched height", "S": "Sagekin W2E dependency at matched height", "K": "large-human (Skarn) guard (REPORT)", "F": "frames",
         "M": "composition", "X": "named validators", "J": "exact-plane joint re-measurement (REPORT)", "P": "pelvic / axial diagnostics (REPORT)",
         "D": "route cross-checks (REPORT)", "Q": "diagnostic leg probes for the author ruling (NOT applied)"}
def main():
    d = json.load(open(os.path.join(EV, "w2f.json"))); V = d["values"]
    T = ["# RAC W2F — Elf family W2: evidence tables", "", "Generated by `tools/rac/w1/gen_w2f_docs.py`. NON-CANON diagnostics. Skeletal: CIB grids, exact-plane S7 (t = 0 shown in the value tables; rows sweep t = 0 / 0.5 / 1). "
         "Joints: exact-plane section (REFERENCE_ANATOMY_V1 §10). Rule: AD-G10. Elf directions are scored only where the elf canon states them; complete-anatomy reading per the W2E ruling.", ""]
    for title, cols in GROUPS:
        cols = [c for c in cols if c in V]
        keys = []
        for c in cols: keys += [k for k in V[c] if k not in keys and "[t=0.5]" not in k and "[t=1.0]" not in k]
        T += ["## %s" % title, "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for k in keys: T.append("| %s | %s |" % (k, " | ".join(f4(V[c].get(k)) for c in cols)))
        T.append("")
    T += ["## Checks", ""]
    for code, name in CODES.items():
        cc = [c for c in d["checks"] if c["code"] == code]
        if not cc: continue
        T += ["### %s — %s (%d; not PASS / REPORT: %d)" % (code, name, len(cc), sum(c["result"] != "PASS" and not c["result"].startswith("REPORT") for c in cc)), "",
              "| Check | A | Value | Op | B | Value | Margin | Result | Note |", "|---|---|---|---|---|---|---|---|---|"]
        for c in cc:
            va = " / ".join("%.4f" % x for x in c["va"]) if isinstance(c["va"], list) else f4(c["va"])
            vb = " / ".join("%.4f" % x for x in c["vb"]) if isinstance(c["vb"], list) else f4(c["vb"])
            T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (c["check"], c["a"], va, c["op"], c["b"], vb, ("%+.2f %%" % c["margin_pct"]) if isinstance(c.get("margin_pct"), float) else "",
                                                                c["result"] if c["result"] == "PASS" or c["result"].startswith("REPORT") else "**%s**" % c["result"], str(c.get("note", "")).replace("|", "/")))
        T.append("")
    T += ["## Accepted W1 rows per body (not PASS only; fixed W1 references)", "", "| Body | Layer | Row | Result | Value | Reference |", "|---|---|---|---|---|---|"]
    for b, rows in d["canonical_rows"].items():
        for x in rows:
            if x["result"] != "PASS": T.append("| %s | %s | %s | %s | %s | %s |" % (b, x["layer"], x["check"], x["result"], f4(x.get("va")), f4(x.get("vb"))))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
