"""Generate the RAC W2A1 (Marchfolk frame closure) evidence tables from the JSON in reviews/rac-w2a1-mf-frame-evidence (no hand-typed numbers)."""
import json, os, glob
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w2a1-mf-frame-evidence")
fv = lambda v: " – ".join("%.4f" % x for x in v) if isinstance(v, list) else ("%.4f" % v if isinstance(v, float) else str(v))
def main():
    T = ["# RAC W2A1 — Marchfolk frame closure: evidence tables", "", "Generated by `tools/rac/w1/gen_w2a1_docs.py` from the JSON in this folder. NON-CANON diagnostics. Skeletal readings: CIB stations on the frame bodies' own grids (t = 0 / 0.5 / 1.0); Balanced = the accepted W1 ARMs on the W1i skeletal base. Joints: stature-scaled slab.", ""]
    W = json.load(open(os.path.join(EV, "writes.json")))
    T += ["## Frame writes", ""] + ["- **%s**: `%s`" % (k, json.dumps(v)) for k, v in W.items()] + [""]
    for f in sorted(glob.glob(os.path.join(EV, "frames_*.json"))):
        d = json.load(open(f)); V = d["values"]; cols = [c for c in ("M Narrow", "M Balanced", "M Broad", "F Narrow", "F Balanced", "F Broad", "SK", "SG", "FN", "AE") if c in V]
        T += ["## Set %s" % d["set"], "", "| Reading | " + " | ".join(cols) + " |", "|---|" + "---|" * len(cols)]
        for k in V["M Balanced"]: T.append("| %s | %s |" % (k, " | ".join(("%.4f" % V[c][k]) if k in V[c] else "—" for c in cols)))
        T += ["", "| Code | Check | A | Value | Op | B | Value | Result | Note |", "|---|---|---|---|---|---|---|---|---|"]
        for c in d["checks"]: T.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (c["code"], c["check"], c["a"], fv(c["va"]), c["op"], c["b"], fv(c["vb"]), c["result"] if c["result"] in ("PASS", "REPORT") else "**%s**" % c["result"], c["note"]))
        T.append("")
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
