"""Generate the W1g evidence tables and ARM records from the evidence JSON (no hand-typed numbers).
Writes reviews/rac-w1g-evidence/tables.md and reviews/rac-w1g-arm/claude-rac-w1g-arm-<ID>.md."""
import json, os, hashlib, re
from collections import Counter
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
EV = os.path.join(R, "reviews", "rac-w1g-evidence"); ARM = os.path.join(R, "reviews", "rac-w1g-arm"); CFG = os.path.join(R, "tools", "rac", "w1", "cfg", "w1g")
EF = os.path.join(R, "reviews", "rac-w1f-evidence")
def jl(*p): return json.load(open(os.path.join(*p)))
def f4(x): return "—" if x is None else (("[%.4f, %.4f]" % tuple(x)) if isinstance(x, list) else ("%.4f" % x if isinstance(x, (int, float)) else str(x)))
def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()[:16]
STRICT = (">", "<")
def res(x):
    if "result" in x: return x["result"]
    if x.get("report_only"): return "REPORT"
    if "HISTORICAL" in x.get("check", ""): return "HISTORICAL (non-vetoing)"
    if not x["pass"]: return "FAIL"
    if x["op"] in STRICT and isinstance(x["vb"], float) and abs(x["va"] - x["vb"]) / max(abs(x["vb"]), 1e-9) < 0.01: return "NOT DEMONSTRATED"
    return "PASS"
def cnt(rows): c = Counter(res(x) for x in rows); return ", ".join("%s %d" % (k, v) for k, v in sorted(c.items()))
def bold(r): return "**%s**" % r if r.split(" ")[0] in ("FAIL", "NOT", "MARGINAL", "T-SENSITIVE") else r
def rows_md(rows, by_t=False):
    h = "| Cand | Check | Canon | %s | Op | Comparator%s | Result |" % ("Value t=0 / 0.5 / 1.0" if by_t else "Value", " t=0 / 0.5 / 1.0" if by_t else "")
    out = [h, "|---|---|---|---|---|---|---|"]
    for x in rows:
        if by_t and x.get("by_t"): v = " / ".join(f4(t["va"]) for t in x["by_t"].values()); cv = " / ".join(f4(t["vb"]) for t in x["by_t"].values())
        else: v = f4(x.get("va")); cv = f4(x.get("vb")) if x.get("vb") is not None else ""
        out.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], x.get("canon", ""), v, x["op"], x.get("b", ""), cv, bold(res(x))))
    return out
def key(x): return (x["cand"], x["check"], x.get("b"))

def main():
    os.makedirs(ARM, exist_ok=True)
    SK = jl(EV, "skeletal", "skeletal_checks.json"); SKf = jl(EF, "skeletal", "skeletal_checks.json"); SKm = jl(EV, "skeletal", "method_attribution_checks.json")
    AL = jl(EV, "skeletal", "alpc_w1g.json"); A8 = jl(EV, "skeletal", "alpc8.json"); CC = jl(EV, "skeletal", "contour_clearance.json")
    DC = jl(EV, "directional_checks.json"); DCf = jl(EF, "directional_checks.json"); WC = jl(EV, "w1e_checks.json"); WCf = jl(EF, "w1e_checks.json")
    OC = jl(EV, "ocular", "ocular_w1g.json"); GS = jl(EV, "ocular", "gs1.json"); GSr = jl(EV, "ocular", "gs1_refs.json")
    EC = jl(EV, "ears", "ear_checks.json"); BJ = jl(EV, "joints", "bony_joints.json"); GOp = jl(CFG, "GO.json"); SH = open(os.path.join(EV, "solver", "shrink.log")).read()
    cib = lambda i: jl(EV, "cib", i + "_cib.json"); skp = lambda i: jl(EV, "skeletal", i + "_skp.json"); skpf = lambda i: jl(EF, "skeletal", i + "_skp.json")
    T = ["# RAC W1g — evidence tables", "", "Generated by `tools/rac/w1/gen_w1g_docs.py` from the JSON in this folder. Nothing here is canon. Skeletal readings (CIB bony stations, t sweep) are the PV-D16 / AD-G10 validation layer; skin readings are composition-inclusive diagnostics.", ""]
    # 1 method
    T += ["## 1. Bony-station method (AD-W1G-1, M-1(a)): composition-infimum bony envelope (CIB)", "",
          "Each body's skeleton is built across the generator composition grid {muscle, weight} ∈ {0, 0.25, 0.5}² (9 bodies; AD-G14 bodies through their own route). Each grid body is aligned to the reference rig joints and its ALPC stations are read; the bony station value is the minimum over the grid (breadth and depth separately), then inset 2t (t sweep 0 / 0.5 / 1.0 cm × H/173). Bone cannot be wider than the thinnest skin of the same skeleton, so every tested composition lies on or outside it by construction. It is an upper bound on bone, not a measurement of bone. The proximal-femur scale is reduced by half the S6 correction. Girdle landmarks, joints and vertical intervals are unchanged from W1f.", "",
          "| Body (W1g) | S5 crest, W1f method (minimum-composition body, cm) | S5 CIB (cm) | CIB / W1f method | argmin composition | S5 reference skin (cm) | min tissue per side over the grid at S5 (cm) |", "|---|---|---|---|---|---|---|"]
    for i in ("MF-M-R", "MF-F-R", "SK", "SG", "FN", "AE", "VA", "HV", "DU-NAT", "PK-NAT", "CG-NAT", "GR", "GO", "SKB229", "SKB208"):
        try: c = cib(i); s = skp(i)
        except FileNotFoundError: continue
        w = s["w1f_stations"]["S5"][0]; b = c["bony"]["S5"][0]; tmin = min(v["S5"][0] for v in c["tissue_per_side_min_cm"].values())
        T.append("| %s | %.2f | %.2f | %.3f | %s | %.2f | %.2f |" % (i, w, b, b / w, c["argmin"]["S5"][0], c["ref_skin"]["S5"][0], tmin))
    T += ["", "CIB replaces every station S2–S7 (S1 = glenohumeral breadth is unchanged). S5 moves for every body; at the other stations the minimum-composition body is the grid minimum for most bodies, but not all (e.g. Broad Skarn 229 S4 breadth −12 %, GOR-BODY-03 S4 −11 %; per-station argmins in `cib/<ID>_cib.json`). The W1f-body CIB inputs for the attribution are `cib/GO-W1f_cib.json` and `cib/GR-W1f_cib.json` (procedure: `tools/rac/w1/w1g_drivers/attribution.md`).", "",
          "### Method attribution: W1f bodies read with CIB (`skeletal/method_attribution_checks.json`; GO and GR are the W1f bodies, everything else as W1g)", ""]
    T += rows_md([x for x in SKm if x["cand"] in ("GO", "GR") and res(x) not in ("PASS", "REPORT", "NOT RUN")], by_t=True) + [""]
    # 2 construction values
    T += ["## 2. Builder-chosen construction values (R-14; all CONSTRAINED)", "", "| Body | Item | W1f | W1g |", "|---|---|---|---|"]
    wf = GOp["w1f"]; wg = GOp["w1g"]
    for k in wg["bone_scales"]: T.append("| GO | bone scale %s | %s | %s |" % (k, wf["bone_scales"].get(k), wg["bone_scales"][k]))
    for k in ("ka", "kp", "kb"): T.append("| GO | trunk sculpt %s at r = %s | %s | %s |" % (k, wg["sculpt"]["r"], wf["sculpt"][k], wg["sculpt"][k]))
    T.append("| GO | height macro / stature (R-6) | 0.8369 / 228.77 | 0.8369 / %.2f |" % GOp["stature_r6"])
    for i in ("GR", "AE", "VA", "FN"):
        c = jl(CFG, i + ".json"); T.append("| %s | %s | %s | %s |" % (i, c["item"], c["w1f"], c["w1g"]))
    T += ["| Frames | GOR-BODY-04 / -12 / -14 writes | W1f writes | unchanged writes on the W1g skeleton |",
          "| Stature stress | GO donors | 208 cm (macro 0.7019) | + 215 / 222 / 251 cm (macros 0.7438 / 0.7911 / 0.985) |",
          "| Broad Skarn | equal-height comparator write | 208 / 229 cm | + 215 / 222 cm (same write) |", ""]
    # 3 skeletal checks
    T += ["## 3. Skeletal / bony-landmark validation (`skeletal/skeletal_checks.json`; %d rows: %s)" % (len(SK), cnt(SK)), "",
          "Rule (AD-G10 / PV-D10): strict > / < must hold by ≥ 1 % (else NOT DEMONSTRATED); ≥ / ≤ missing by < 1 % = MARGINAL; '~' = ±0.010; T-SENSITIVE = result changes with t. ALPC-7 here is the 229 cm pair; the other pairs and ALPC-5 / -6 / -8 are in §5–6.", ""] + rows_md(SK, by_t=True)
    # 4 before / after
    F = {key(x): x for x in SKf}; ch = []
    for x in SK:
        y = F.get(key(x))
        if y and (res(y) != "PASS" or res(x) != "PASS") and res(y) not in ("REPORT", "NOT RUN"): ch.append((x, y))
    T += ["", "## 4. Before / after for every W1f non-PASS row and every row whose result changed", "", "### Skeletal rows", "", "| Cand | Check | W1f value (t=0.5) | W1f result | W1g value (t=0.5) | W1g comparator | W1g result |", "|---|---|---|---|---|---|---|"]
    for x, y in ch: T.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], f4(y["va"]), bold(res(y)), f4(x["va"]), x["op"], f4(x["vb"]), bold(res(x))))
    Df = {key(x): x for x in DCf}
    T += ["", "### Directional rows", "", "| Cand | Check | W1f value | W1f result | W1g value | Comparator | W1g result |", "|---|---|---|---|---|---|---|"]
    for x in DC:
        y = Df.get(key(x))
        if (y is None and x["cand"] == "AE") or (y and (res(y) != "PASS" or res(x) != "PASS")):
            T.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], f4(y["va"]) if y else "— (row added W1g)", bold(res(y)) if y else "—", f4(x["va"]), x["op"], f4(x["vb"]), bold(res(x))))
    AIf = jl(EF, "skeletal", "alpc_invariance.json")["rows"]
    T += ["", "### ALPC-5 frame rows (W1f `alpc_invariance.json` vs W1g `alpc_w1g.json`; non-PASS in either)", "", "| Body | Check | W1f t=0 / 0.5 / 1.0 | W1f result | W1g t=0 / 0.5 / 1.0 (MF comparator) | W1g result per t | W1g result |", "|---|---|---|---|---|---|---|"]
    for b in ("GOR-BODY-04", "GOR-BODY-12", "GOR-BODY-14"):
        Fr = {r["check"]: r for r in AIf.get("ALPC-5 " + b, [])}
        for r in AL["rows"]["ALPC-5 " + b]:
            y = Fr.get(r["check"])
            if y and (res(y) != "PASS" or res(r) != "PASS"):
                T.append("| %s | %s | %s | %s | %s (%s) | %s | %s |" % (b, r["check"], " / ".join(f4(v["va"]) for v in y["by_t"].values()), bold(res(y)),
                         " / ".join(f4(v["va"]) for v in r["by_t"].values()), " / ".join(f4(v["vb"]) for v in r["by_t"].values()), " / ".join(v["result"] for v in r["by_t"].values()), bold(res(r))))
    # 5 ALPC
    T += ["", "## 5. Gorrund ALPC stress tests (`skeletal/alpc_w1g.json`)", "", "| Test | Result |", "|---|---|"]
    for k, rows in AL["rows"].items(): T.append("| %s | %s |" % (k, cnt(rows)))
    for k, rows in AL["rows"].items():
        bad = [r for r in rows if res(r) != "PASS"]
        if bad: T += ["", "### %s — non-PASS rows" % k, ""] + rows_md(bad, by_t="skin" not in k)
    c16 = cib("GO")["tissue_per_side_min_cm"]["GO-C025025"]
    T += ["", "GOR-BODY-16 physical validity (tissue per side over the CIB bony station, cm; ≥ 0 = skin outside bone): " + ", ".join("%s %.2f / %.2f" % (S, *c16[S]) for S in ("S2", "S3", "S4", "S5", "S6")) + ". W1f: S5 breadth tissue −3.1 cm per side (skin inside the skeleton).", ""]
    T += ["### ALPC-8 (AD-W1G-2 shape reading; `skeletal/alpc8.json`)", "", "| Reading | GO | DU | GO > DU |", "|---|---|---|---|"]
    for k, v in A8["checks"].items():
        if isinstance(v, list): T.append("| %s | %s | %s | %s |" % (k, f4(v[0]), f4(v[1]), "yes" if v[2] else "no (not a failure under AD-W1G-2)" if "axial) vertical contribution" in k else "**no**"))
    T += ["", "Silhouette IoU: front %.3f, side %.3f; identical: %s." % (A8["checks"]["silhouette_IoU"]["front"], A8["checks"]["silhouette_IoU"]["side"], A8["checks"]["identical_silhouettes"]), ""]
    # 6 solver / least extreme
    T += ["## 6. Gorrund re-solve and least-extreme record (`solver/`)", "", "Feasibility = every GO skeletal row with margin, shares vs GR, chest-lead not below W1f, buttock-lead ≤ 0.023, stature 229 ± 2, arm clearance ≥ 0.25 cm. Then each parameter was moved one third of the way toward the generator value, largest deviation first, twice; a move was kept only if feasibility held. Moves (from `solver/shrink.log`):", "", "```"]
    T += [l for l in SH.splitlines() if l.startswith(("pass", "start", "DONE"))] + ["```", ""]
    # 7 contour / clearance
    T += ["## 7. Contour and arm clearance (R-6; `skeletal/contour_clearance.json`)", "", "Arm test (W1g): each upper-arm vertex is tested against the trunk's own cross-section polygon at its height (signed clearance < 0 = interpenetration). The test is decidable only where that section is closed; near the axilla the trunk-only section is open (arm attachment), so only the lower part of the upper arm is tested (count and height band below). Above that band only the W1f vertex-to-vertex gap is available. The W1f 'medial of the trunk wall' count is kept for comparison (it over-reports).", "",
          "| Body | chest-lead | buttock-lead | vertices inside trunk section (left) | testable vertices (left) | testable band (cm) | signed clearance in band, both sides (cm) | min vertex gap, all upper-arm vertices (cm) | W1f 'medial' count |", "|---|---|---|---|---|---|---|---|---|"]
    for k in CC["contour"]:
        a = CC["arm_clearance"][k]; T.append("| %s | %.4f | %.4f | %d | %d of %d | %.1f–%.1f | %.3f | %.2f | %d |" % (k, CC["contour"][k]["chest_lead"], CC["contour"][k]["buttock_lead"], a["verts_inside_trunk_section"], a["n_testable_closed_section"], a["n_upperarm"], a["testable_band_cm"][0], a["testable_band_cm"][1], a["signed_clearance_both_sides_cm"], a["min_arm_trunk_gap_cm"], a["upperarm_verts_medial_of_trunk_wall"]))
    # 8 SK joints
    T += ["", "## 8. Skarn joint rows (AD-W1G-8; `joints/bony_joints.json`)", "", "Canon: SKARN L24 'heavier joints', L78 'larger joints'. W1c measure = skin joint breadth ÷ adjacent bone length. Bony reading = composition-infimum joint breadth ÷ the same bone length. Skarn anatomy unchanged.", "",
          "| Joint | SK skin ratio | MF skin ratio | skin SK/MF | SK bony ratio | MF bony ratio | bony SK/MF | bony SK/MF excluding the minimum-composition bodies (sensitivity) |", "|---|---|---|---|---|---|---|---|"]
    BONE = {"elbow_breadth": "upperarm", "knee_breadth": "thigh", "wrist_breadth": "forearm"}
    def nolean(c, j):
        pb = BJ[c]["per_body"]; ref = pb[c + "_rest.npz"]; return min(v[j] for k, v in pb.items() if "LEAN" not in k) / ref[BONE[j]]
    for j in ("elbow_breadth", "knee_breadth", "wrist_breadth"):
        s, m = BJ["SK"][j], BJ["MF-M-R"][j]
        T.append("| %s | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f |" % (j.split("_")[0], s["skin_ratio"], m["skin_ratio"], s["skin_ratio"] / m["skin_ratio"], s["ratio"], m["ratio"], s["ratio"] / m["ratio"], nolean("SK", j) / nolean("MF-M-R", j)))
    T += ["", "The knee magnitude is driven by MF's minimum-composition knee (9.25 cm vs 10.9–12.0 cm in every other MF grid body); without the minimum-composition bodies the direction holds but the magnitudes are about ×1.05–1.06 (elbow, knee). These are composition-infimum skin breadths (upper bounds on bone), not bony landmarks."]
    # 9 ocular
    T += ["", "## 9. Ocular (`ocular/`)", "", "### Rings and globes (O-1; FN δ = 0.03)", "", "| Body | Ring (cm) | Inside skin | Ring-globe clr (cm) | Globe (cm) | globe/HH vs MF | ORB b / h vs MF | Fits |", "|---|---|---|---|---|---|---|---|"]
    for i, r in OC["bodies"].items():
        v = r["vs_MF"]; T.append("| %s | %.3f × %.3f | %.0f %% | %.2f | %.3f | %.3f | %.3f / %.3f | %s |" % (i, r["ring_breadth_cm"], r["ring_height_cm"], 100 * r["ring_inside_skin_frac"], r["ring_globe_clearance_cm"], r["globe_cm"], v["globe_over_HH"], v["ORB_breadth"], v["ORB_height"], r["fits"]))
    T += ["", "### G-S1 smallest physically sound adult globe (`ocular/gs1.json`; method in `tools/rac/w1/ocular_gs1.py`)", "", "| Body | Current globe (cm) | g_min aperture backing (cm) | g_max collision (cm) | g_cap adult (cm) | Viable interval (cm) | Solution (cm) | Solution globe/HH vs MF | Skin clearance at solution (cm) |", "|---|---|---|---|---|---|---|---|---|"]
    for i, r in list(GS["bodies"].items()) + list(GSr["bodies"].items()):
        T.append("| %s | %.3f | %.3f | %.3f | %.3f | %s | %s | %s | %s |" % (i, r["globe_current_cm"], r["g_min_cm"], r["g_max_collision_cm"], r["g_cap_adult_cm"], f4(r["viable_interval_cm"]), f4(r["solution_cm"]), f4(r["solution_globe_over_HH_vs_MF"]), f4(r["solution_skin_clearance_cm"])))
    T += ["", "Method check on accepted references: SK and SG (male, accepted) sit 0.9 % and 0.1 % below their own g_min, so g_min carries about 1 % method uncertainty. MF-F-R and DU have an aperture geometry that differs from MF-M-R and are not valid tests of a male-reference bound (their intervals are empty by this method).", ""]
    # 10 directional / skin / ears
    T += ["## 10. Directional checks (`directional_checks.json`; %d rows: %s)" % (len(DC), cnt(DC)), ""] + rows_md([x for x in DC if res(x) != "PASS"])
    T += ["", "## 11. Skin diagnostics (`w1e_checks.json`; composition-inclusive, never a pass condition; %d rows: %s)" % (len(WC), cnt(WC)), ""]
    Wf = {key(x): x for x in WCf}
    T += ["| Cand | Check | W1f value | W1f result | W1g value | Comparator | W1g result |", "|---|---|---|---|---|---|---|"]
    for x in WC:
        y = Wf.get(key(x))
        if res(x) in ("PASS", "NOT RUN") and (y is None or res(y) in ("PASS", "NOT RUN")): continue
        T.append("| %s | %s | %s | %s | %s | %s %s | %s |" % (x["cand"], x["check"], f4(y["va"]) if y else "—", bold(res(y)) if y else "—", f4(x["va"]), x["op"], f4(x["vb"]) if isinstance(x["vb"], float) else x["vb"], bold(res(x))))
    T += ["", "## 12. Ears (`ears/`; %d rows: %s)" % (len(EC), cnt(EC)), ""]
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n")
    for i, desc in (("GO", "Gorrund central — AD-G14 skeleton re-solved with the CIB bony stations"), ("GR", "Grask central — pelvis X 1.12, W1e lumbar narrowing removed"),
                    ("AE", "Aelari central — leg / torso / neck / foot bone lengths"), ("VA", "Vael central — leg / upper-thorax bone lengths"), ("FN", "Fenn central — forearm length +0.5 %")):
        m = jl(EV, "candidates", i + "_meas.json"); geo = os.path.join(EV, "geometry", i + "_r6.npz"); sk = skp(i)
        L = ["# RAC W1g ARM record — %s (%s)" % (i, desc), "", "Generated by `tools/rac/w1/gen_w1g_docs.py`. Status: see `reviews/claude-rac-w1g-author-acceptance-gate.md`. Nothing here is accepted.", "",
             "- Geometry: `%s` (sha256 %s); skeleton: `reviews/rac-w1g-evidence/skeleton/%s-LEAN_r6.npz`; config `tools/rac/w1/cfg/w1g/%s.json`" % (os.path.relpath(geo, R), sha(geo), i, i),
             "- Stature (R-6) %.2f cm; HH %.2f cm; landmark globe %.3f cm" % (m["stature_r6"], m["combined"]["cranio"]["HH"], m["combined"]["cranio"]["eye_diam_cm"]),
             "- Bony stations: CIB (`reviews/rac-w1g-evidence/cib/%s_cib.json`); skeletal-envelope alignment scale %.4f, joint residual %.3f cm" % (i, sk["align_scale"], sk["align_joint_resid_cm"]), "",
             "## Skeletal checks", ""] + rows_md([x for x in SK if x["cand"] == i and x["result"] != "NOT RUN"], by_t=True)
        L += ["", "## Directional checks", ""] + rows_md([x for x in DC if x["cand"] == i])
        L += ["", "## Skin diagnostics (composition-inclusive)", ""] + rows_md([x for x in WC if x["cand"] == i and x["result"] != "NOT RUN"])
        open(os.path.join(ARM, "claude-rac-w1g-arm-%s.md" % i), "w").write("\n".join(L) + "\n")
    print("tables + ARM records written")

if __name__ == "__main__":
    main()
