"""Generate the RAC W1s (Halvren W1 acceptance gate) evidence tables from the JSON in reviews/rac-w1s-hv-evidence (no hand-typed numbers)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."); EV = os.path.join(R, "reviews", "rac-w1s-hv-evidence")
jl = lambda *p: json.load(open(os.path.join(*p)))
ex = lambda f: os.path.exists(os.path.join(EV, f))
SRC = ("MF", "SK", "SG", "FN", "AE", "VA")
def fv(v):
    if isinstance(v, (list, tuple)): return " / ".join(fv(x) for x in v)
    if isinstance(v, dict): return ", ".join("%s %s" % (k, fv(x)) for k, x in v.items())
    return "%.4f" % v if isinstance(v, float) else str(v)
def rows_md(rows):
    T = ["| Check | Canon | Value | Op | Comparator | Result | Note |", "|---|---|---|---|---|---|---|"]
    for r in rows: T.append("| %s | %s | %s | %s | %s %s | %s | %s |" % (r.get("check"), r.get("canon", ""), fv(r.get("va")), r.get("op"), r.get("b", ""), fv(r.get("vb")),
                                                                     r["result"] if r["result"] in ("PASS", "REPORT") else "**%s**" % r["result"], r.get("note", "")))
    return T
NAMES = {"W1g": "HV central (as built)", "HVC1": "Probe HVC1 (eye-scale target removed)", "HVC2": "Probe HVC2 (eye-scale 0.05)", "HVC3": "Probe HVC3 (eye-scale removed, cheek-bones 0.1)",
         "NARROWB": "HV Narrow, breadth-only write", "BROADB_P112": "HV Broad, breadth-only, pelvis x1.12",
         "PANEL_HVH3": "Panel: human-leaning mixed (HVH3, diagnostic)", "PANEL_HVE3": "Panel: elf-leaning mixed (HVE3, diagnostic)"}
def main():
    T = ["# RAC W1s — Halvren W1 acceptance gate: evidence tables", "", "Generated by `tools/rac/w1/gen_w1s_docs.py` from the JSON in this folder. Nothing here is canon. Sources used directly (no averaged Human or Elf parent): accepted MF-M-R, SK, SG, Fenn FNL4, Aelari AEL1, Vael VAL4. Rule: AD-G10 (span rows: outside by < 1 % = MARGINAL). Joint rows: joint breadth / stature with the stature-scaled slab (Cogling ruling). Percent columns are HV relative to each source.", ""]
    C = jl(EV, "sources_W1g.json")
    T += ["## 1. Central HV: expression recipe by domain (nearest accepted source per reading)", "", "| Domain | Reading | HV | " + " | ".join("vs " + s for s in SRC) + " | Nearest | In span |", "|---|---|---|" + "---|" * len(SRC) + "---|---|"]
    for r in C["rows"]: T.append("| %s | %s | %.4f | %s | %s | %s |" % (r["domain"], r["reading"], r["values"]["HV"], " | ".join("%+.1f %%" % r["pct_HV_vs"][s] for s in SRC), r["nearest_source"],
                                                                           "yes" if r["in_span"] else "**no (%+.2f %%)**" % r["beyond_span_pct"]))
    T += ["", "| Domain | nearest human source | nearest elven source | nearest-source counts | outside span |", "|---|---|---|---|---|"]
    for d, v in C["summary"]["by_domain"].items(): T.append("| %s | %d | %d | %s | %s |" % (d, v["human_nearest"], v["elven_nearest"], ", ".join("%s %d" % kv for kv in v["nearest_counts"].items() if kv[1]), ", ".join(v["out_of_span"]) or "none"))
    T += ["", "| Source | readings within 1 % of it (all domains) | median abs difference | by domain |", "|---|---|---|---|"]
    for s, v in C["summary"]["by_source"].items(): T.append("| %s | %d / %d | %.1f %% | %s |" % (s, v["within_1pct"], v["n"], v["median_abs_pct"], ", ".join("%s %s" % kv for kv in v["by_domain_within_1pct"].items())))
    T += ["", "Context: accepted sources against each other on the same readings (within 1 %; body = axial + appendicular + distal).", "", "| Pair | body | all |", "|---|---|---|"]
    body = [r for r in C["rows"] if r["domain"] != "craniofacial"]
    for a, b in (("VA", "MF"), ("SG", "MF"), ("VA", "SG"), ("AE", "MF"), ("FN", "MF"), ("SK", "MF")):
        cnt = lambda rr: sum(abs(r["values"][a] / r["values"][b] - 1) < 0.01 for r in rr)
        T.append("| %s vs %s | %d / %d | %d / %d |" % (a, b, cnt(body), len(body), cnt(C["rows"]), len(C["rows"])))
    T += ["", "## 2. Scored rows across bodies", "", "| Body | rows (added + directional) | not PASS |", "|---|---|---|"]
    B = {t: jl(EV, "central_%s.json" % t) for t in NAMES if ex("central_%s.json" % t)}
    for t, c in B.items():
        bad = [r for r in c["added"] + c["directional"] if r["result"] not in ("PASS", "REPORT")]
        T.append("| %s | %d + %d | %s |" % (NAMES[t], sum(r["result"] != "REPORT" for r in c["added"]), len(c["directional"]), "; ".join("%s → %s" % (r["check"], r["result"]) for r in bad) or "none"))
    T += ["", "## 3. Eye-region probes (body identical; only the eye / cheek target changes)", "", "| Body | orbit breadth / head length | orbit height / head height | eye diameter / head height | % orbit breadth vs MF |", "|---|---|---|---|---|"]
    for t in ("W1g", "HVC1", "HVC2", "HVC3"):
        if not ex("sources_%s.json" % t): continue
        rr = {r["reading"]: r for r in jl(EV, "sources_%s.json" % t)["rows"]}
        T.append("| %s | %.4f | %.4f | %.4f | %+.1f %% |" % (NAMES[t], rr["orbit breadth / head length"]["values"]["HV"], rr["orbit height / head height"]["values"]["HV"], rr["eye diameter / head height"]["values"]["HV"], rr["orbit breadth / head length"]["pct_HV_vs"]["MF"]))
    for t, c in B.items():
        T += ["", "## 4.%d %s" % (list(B).index(t) + 1, NAMES[t]), ""]
        sk = "skeletal_%s.json" % t
        if ex(sk):
            s = jl(EV, sk); T += ["### skeletal proxy (CIB; control vs W1i base HV: %s)" % (fv(s["control_max_abs_diff_vs_W1i_base_HV"]) if t == "W1g" else "n/a (frame body)"), "",
                                  "| Check | t = 0 HV | t = 0 span | t = 0.5 HV | t = 1.0 HV | Result |", "|---|---|---|---|---|---|"]
            for r in s["rows"]:
                if "by_t" in r:
                    sp = [r["by_t"]["0.0"][x] for x in SRC] if all(x in r["by_t"]["0.0"] for x in SRC) else [0]
                    T.append("| %s | %.4f | %.4f – %.4f | %.4f | %.4f | %s |" % (r["check"], r["by_t"]["0.0"]["HV"], min(sp), max(sp), r["by_t"]["0.5"]["HV"], r["by_t"]["1.0"]["HV"], r["result"] if r["result"] == "PASS" else "**%s**" % r["result"]))
                else: T.append("| %s | %s | | | | REPORT |" % (r["check"], ", ".join("%s %.2f" % kv for kv in r["fractions"].items())))
            T.append("")
        note = " — breadth-only frame scored against central (Balanced) sources, not like for like" if t in ("NARROWB", "BROADB_P112") else ""
        for L in ("added", "directional"): T += ["### %s (%d rows)%s" % (L, len(c[L]), note), ""] + rows_md(c[L]) + [""]
    P = jl(EV, "composition.json")
    T += ["## 5. Trunk continuity readings", "", "| Body | hip / thorax | waist / thorax | waist / hip | d2b | waist rise |", "|---|---|---|---|---|---|"]
    for k, v in P["continuity"].items(): T.append("| %s | %.3f | %.3f | %.3f | %.4f | %.3f |" % (k, v["hip_over_thorax"], v["waist_over_thorax"], v["waist_over_hip"], v["d2b"], v["waist_rise"]))
    T += ["", "## 6. Same-composition low check (HV low 0.25 / 0.25)", "", "| Comparator | within 1 % | " + " | ".join(next(iter(P["low_same_composition"].values()))["pct_HVLOW_vs"]) + " |", "|---|---|" + "---|" * 21]
    for k, v in P["low_same_composition"].items(): T.append("| %s | %d / %d | %s |" % (k, v["within_1pct"], v["n"], " | ".join("%+.1f %%" % x for x in v["pct_HVLOW_vs"].values())))
    for t in ("PANEL_HVH3", "PANEL_HVE3"):
        if not ex("sources_%s.json" % t): continue
        c = jl(EV, "sources_%s.json" % t)
        T += ["", "## 7. %s: recipe by domain" % NAMES[t], "", "| Domain | nearest human | nearest elven | counts | outside span |", "|---|---|---|---|---|"]
        for d, v in c["summary"]["by_domain"].items(): T.append("| %s | %d | %d | %s | %s |" % (d, v["human_nearest"], v["elven_nearest"], ", ".join("%s %d" % kv for kv in v["nearest_counts"].items() if kv[1]), ", ".join(v["out_of_span"]) or "none"))
    open(os.path.join(EV, "tables.md"), "w").write("\n".join(T) + "\n"); print("tables written", len(T))
if __name__ == "__main__": main()
